using DAL.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DAL
{
	public class TransportationContext : DbContext
	{
		public DbSet<Route> Routes { get; set; }
		public DbSet<Stop> Stops { get; set; }
		public DbSet<BoundedWalk> BoundedWalks { get; set; }
		public DbSet<Walk> Walks { get; set; }
		public DbSet<Itinerary> Itineraries { get; set; }
		public DbSet<Recording> Recordings { get; set; }
		public DbSet<RouteJourney> RouteJourneys { get; set; }
		public DbSet<RouteStop> RouteStops { get; set; }


		public TransportationContext() : base() { }

		public TransportationContext(DbContextOptions<TransportationContext> options) : base(options) { }

		protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
		{
			optionsBuilder.UseSqlServer(@"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=master;Integrated Security=True;Connect Timeout=30;Encrypt=False;Trust Server Certificate=False;Application Intent=ReadWrite;Multi Subnet Failover=False");
		}

		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			base.OnModelCreating(modelBuilder);

			modelBuilder.Entity<Route>()
				.HasMany(r => r.Stops)
				.WithMany(s => s.Routes)
				.UsingEntity<RouteStop>();

			var recordingTypeConverter = new EnumToStringConverter<RecordingType>();
			modelBuilder.Entity<Recording>()
				.Property(r => r.RecordingType)
				.HasConversion(recordingTypeConverter);

			var directionTypeConverter = new EnumToStringConverter<Direction>();
			modelBuilder.Entity<RouteStop>()
				.Property(rs => rs.Direction)
				.HasConversion(directionTypeConverter);

			#region Seeding
			modelBuilder.Entity<Route>().HasData(
				new Route { ID = 01, Provider = "BKK", RouteNumber = "7" },
				new Route { ID = 02, Provider = "BKK", RouteNumber = "7E" },
				new Route { ID = 03, Provider = "BKK", RouteNumber = "82" },
				new Route { ID = 04, Provider = "BKK", RouteNumber = "82A" },
				new Route { ID = 05, Provider = "BKK", RouteNumber = "M1" },
				new Route { ID = 06, Provider = "BKK", RouteNumber = "M2" },
				new Route { ID = 07, Provider = "BKK", RouteNumber = "M3" },
				new Route { ID = 08, Provider = "BKK", RouteNumber = "M4" },
				new Route { ID = 09, Provider = "BKK", RouteNumber = "H5" },
				new Route { ID = 10, Provider = "BKK", RouteNumber = "H6" },
				new Route { ID = 11, Provider = "BKK", RouteNumber = "H7" },
				new Route { ID = 12, Provider = "BKK", RouteNumber = "H8" },
				new Route { ID = 13, Provider = "BKK", RouteNumber = "H9" },
				new Route { ID = 14, Provider = "BKK", RouteNumber = "1" },
				new Route { ID = 15, Provider = "BKK", RouteNumber = "1A" },
				new Route { ID = 16, Provider = "BKK", RouteNumber = "2" },
				new Route { ID = 17, Provider = "BKK", RouteNumber = "3" },
				new Route { ID = 18, Provider = "BKK", RouteNumber = "4" },
				new Route { ID = 19, Provider = "BKK", RouteNumber = "6" },
				new Route { ID = 20, Provider = "BKK", RouteNumber = "5" }//,
				//new Route { ID = 21, Provider = "BKK", RouteNumber = "8E" },
				//new Route { ID = 22, Provider = "BKK", RouteNumber = "9" },
				//new Route { ID = 23, Provider = "BKK", RouteNumber = "72" },
				//new Route { ID = 24, Provider = "BKK", RouteNumber = "80" },
				//new Route { ID = 25, Provider = "BKK", RouteNumber = "77" }
				);

			modelBuilder.Entity<Stop>().HasData(
				new Stop { ID = 001, Name = "Albertfalva vasútállomás" },
				new Stop { ID = 002, Name = "Fonyód utca / Sáfrány utca" },
				new Stop { ID = 003, Name = "Herend utca" },
				new Stop { ID = 004, Name = "Nyírbátor utca" },
				new Stop { ID = 005, Name = "Csurgói utca" },
				new Stop { ID = 006, Name = "Andor utca / Tétényi utca" },
				new Stop { ID = 007, Name = "Bornemissza tér" },
				new Stop { ID = 008, Name = "Puskás Tivadar utca" },
				new Stop { ID = 009, Name = "Bikás park M" },
				new Stop { ID = 010, Name = "Tétényi út 30." },
				new Stop { ID = 011, Name = "Szent Imre Kórház" },
				new Stop { ID = 012, Name = "Karolina út" },
				new Stop { ID = 013, Name = "Kosztolány Dezső tér" },
				new Stop { ID = 014, Name = "Móricz Zsigmond körtér M" },
				new Stop { ID = 015, Name = "Gárdonyi tér" },
				new Stop { ID = 016, Name = "Szent Gellért tér - Műegyetem M" },
				new Stop { ID = 017, Name = "Rudas Gyógyfürdő" },
				new Stop { ID = 018, Name = "Március 15. tér" },
				new Stop { ID = 019, Name = "Ferenciek tere M" },
				new Stop { ID = 020, Name = "Astoria M" },
				new Stop { ID = 021, Name = "Uránia" },
				new Stop { ID = 022, Name = "Blaha Lujza tér M" },
				new Stop { ID = 023, Name = "Huszár utca" },
				new Stop { ID = 024, Name = "Keleti pályaudvar M" },
				new Stop { ID = 025, Name = "Reiner Frigyes park" },
				new Stop { ID = 026, Name = "Cházár András utca" },
				new Stop { ID = 027, Name = "Stefánia út / Thököly út" },
				new Stop { ID = 028, Name = "Zugló vasútállomás" },
				new Stop { ID = 029, Name = "Tisza István tér" },
				new Stop { ID = 030, Name = "Bosnyák tér" },
				new Stop { ID = 031, Name = "Rákospatak utca / Csömöri út" },
				new Stop { ID = 032, Name = "Miskolci utca / Csömöri út" },
				new Stop { ID = 033, Name = "Cinkotai út" },
				new Stop { ID = 034, Name = "Molnár Viktor utca" },
				new Stop { ID = 035, Name = "Apolló utca" },
				new Stop { ID = 036, Name = "Madách utca" },
				new Stop { ID = 037, Name = "Fő tér" },
				new Stop { ID = 038, Name = "Vásárcsarnok" },
				new Stop { ID = 039, Name = "Újpalota, Nyírpalota út" },
				new Stop { ID = 040, Name = "Mexikói út M" },
				new Stop { ID = 041, Name = "Kassai tér" },
				new Stop { ID = 042, Name = "Uzsoki Utcai Kórház" },
				new Stop { ID = 043, Name = "Szugló utca / Róna utca" },
				new Stop { ID = 044, Name = "Szugló utca / Nagy Lajos király útja" },
				new Stop { ID = 045, Name = "Fűrész utca / Szugló utca" },
				new Stop { ID = 046, Name = "Komócsy utca" },
				new Stop { ID = 047, Name = "Egressy út / Vezér utca" },
				new Stop { ID = 048, Name = "Mogyoródi út" },
				new Stop { ID = 049, Name = "Gödöllői utca" },
				new Stop { ID = 050, Name = "Fogarasi út" },
				new Stop { ID = 051, Name = "Tihamér utca" },
				new Stop { ID = 052, Name = "Füredi utca" },
				new Stop { ID = 053, Name = "Álmos vezér útja" },
				new Stop { ID = 054, Name = "Örs vezér tere M+H" },
				new Stop { ID = 055, Name = "Erzsébet királyné útja / Róna utca" },
				new Stop { ID = 056, Name = "Laky Adolf utca" },
				new Stop { ID = 057, Name = "Erzsébet királyné útja, aluljáró" },
				new Stop { ID = 058, Name = "Vörösmarty tér M" },
				new Stop { ID = 059, Name = "Deák Ferenc tér M" },
				new Stop { ID = 060, Name = "Bajcsy-Zsilinszky út M" },
				new Stop { ID = 061, Name = "Opera M" },
				new Stop { ID = 062, Name = "Oktogon M" },
				new Stop { ID = 063, Name = "Vörösmarty utca M" },
				new Stop { ID = 064, Name = "Kodály körönd M" },
				new Stop { ID = 065, Name = "Bajza utca M" },
				new Stop { ID = 066, Name = "Hősök tere M" },
				new Stop { ID = 067, Name = "Széchenyi fürdő M" },
				new Stop { ID = 068, Name = "Déli pályaudvar M" },
				new Stop { ID = 069, Name = "Széll Kálmán tér M" },
				new Stop { ID = 070, Name = "Batthyány tér M+H" },
				new Stop { ID = 071, Name = "Kossuth Lajos tér M" },
				new Stop { ID = 072, Name = "Puskás Ferenc Stadion M" },
				new Stop { ID = 073, Name = "Pillangó utca M" },
				new Stop { ID = 074, Name = "Újpest-központ M" },
				new Stop { ID = 075, Name = "Újpest-városkapu M" },
				new Stop { ID = 076, Name = "Gyöngyösi utca M" },
				new Stop { ID = 077, Name = "Forgách utca M" },
				new Stop { ID = 078, Name = "Göncz Árpád városközpont M" },
				new Stop { ID = 079, Name = "Dózsa György út M" },
				new Stop { ID = 080, Name = "Lehel tér M" },
				new Stop { ID = 081, Name = "Nyugati pályaudvar M" },
				new Stop { ID = 082, Name = "Arany János utca M" },
				new Stop { ID = 083, Name = "Kálvin tér M" },
				new Stop { ID = 084, Name = "Corvin-negyed M" },
				new Stop { ID = 085, Name = "Semmelweis Klinikák M" },
				new Stop { ID = 086, Name = "Nagyvárad tér M" },
				new Stop { ID = 087, Name = "Népliget M" },
				new Stop { ID = 088, Name = "Ecseri út M" },
				new Stop { ID = 089, Name = "Pöttyös utca M" },
				new Stop { ID = 090, Name = "Határ út M" },
				new Stop { ID = 091, Name = "Kőbánya-Kispest M" },
				new Stop { ID = 092, Name = "II. János Pál pápa tér M" },
				new Stop { ID = 093, Name = "Rákóczi tér M" },
				new Stop { ID = 094, Name = "Fővám tér M" },
				new Stop { ID = 095, Name = "Újbuda-központ M" },
				new Stop { ID = 096, Name = "Kelenföld vasútállomás M" },
				new Stop { ID = 097, Name = "Margit híd, budai hídfő H" },
				new Stop { ID = 098, Name = "Szépvölgyi út H" },
				new Stop { ID = 099, Name = "Tímár utca H" },
				new Stop { ID = 100, Name = "Szentlélek tér H" },
				new Stop { ID = 101, Name = "Filatorigát" },
				new Stop { ID = 102, Name = "Kaszásdűlő H" },
				new Stop { ID = 103, Name = "Aquincum H" },
				new Stop { ID = 104, Name = "Rómaifürdő H" },
				new Stop { ID = 105, Name = "Csillaghegy H" },
				new Stop { ID = 106, Name = "Békásmegyer H" },
				new Stop { ID = 107, Name = "Budakalász" },
				new Stop { ID = 108, Name = "Budakalász, Lenfonó H" },
				new Stop { ID = 109, Name = "Szentistvántelep H" },
				new Stop { ID = 110, Name = "Pomáz H" },
				new Stop { ID = 111, Name = "Pannóniatelep" },
				new Stop { ID = 112, Name = "Szentendre" },
				new Stop { ID = 113, Name = "Közvágóhíd H" },
				new Stop { ID = 114, Name = "Kén utca H" },
				new Stop { ID = 115, Name = "Pesterzsébet felső H" },
				new Stop { ID = 116, Name = "Torontál utca H" },
				new Stop { ID = 117, Name = "Soroksár felső H" },
				new Stop { ID = 118, Name = "Soroksár, Hősök tere H" },
				new Stop { ID = 119, Name = "Szent István utca H" },
				new Stop { ID = 120, Name = "Milleniumtelep H" },
				new Stop { ID = 121, Name = "Dunaharaszti felső H" },
				new Stop { ID = 122, Name = "Dunaharaszti külső H" },
				new Stop { ID = 123, Name = "Szigetszentmiklós" },
				new Stop { ID = 124, Name = "József Attila-telep" },
				new Stop { ID = 125, Name = "Szigetszentmiklós alsó H" },
				new Stop { ID = 126, Name = "Szigetszentmiklós-Gyártelep" },
				new Stop { ID = 127, Name = "Szigethalom H" },
				new Stop { ID = 128, Name = "Szigethalom alsó" },
				new Stop { ID = 129, Name = "Tököl" },
				new Stop { ID = 130, Name = "Szigetcsép" },
				new Stop { ID = 131, Name = "Szigetszentmárton-Szigetújfalu" },
				new Stop { ID = 132, Name = "Horgásztanyák" },
				new Stop { ID = 133, Name = "Angyalsziget" },
				new Stop { ID = 134, Name = "Ráckeve" },
				new Stop { ID = 135, Name = "Boráros tér H" },
				new Stop { ID = 136, Name = "Müpa - Nemzeti Színház H" },
				new Stop { ID = 137, Name = "Szabadkikötő H" },
				new Stop { ID = 138, Name = "Szent Imre tér H" },
				new Stop { ID = 139, Name = "Karácsony Sándor utca H" },
				new Stop { ID = 140, Name = "Csepel H" },
				new Stop { ID = 141, Name = "Rákosfalva H" },
				new Stop { ID = 142, Name = "Nagyicce H" },
				new Stop { ID = 143, Name = "Sashalom H" },
				new Stop { ID = 144, Name = "Mátyásföld, repülőtér H" },
				new Stop { ID = 145, Name = "Mátyásföld, Imre utca H" },
				new Stop { ID = 146, Name = "Mátyásföld alsó H" },
				new Stop { ID = 147, Name = "Cinkota H" },
				new Stop { ID = 148, Name = "Cinkota alsó H" },
				new Stop { ID = 149, Name = "Árpádföld H" },
				new Stop { ID = 150, Name = "Szabadságtelep H" },
				new Stop { ID = 151, Name = "Csömör H" },
				new Stop { ID = 152, Name = "Ilonatelep H" },
				new Stop { ID = 153, Name = "Kistarcsa, kórház H" },
				new Stop { ID = 154, Name = "Kistarcsa H" },
				new Stop { ID = 155, Name = "Zsófialiget" },
				new Stop { ID = 156, Name = "Kerepes" },
				new Stop { ID = 157, Name = "Szilasliget" },
				new Stop { ID = 158, Name = "Mogyoród" },
				new Stop { ID = 159, Name = "Szentjakab" },
				new Stop { ID = 160, Name = "Gödöllő, Erzsébet park" },
				new Stop { ID = 161, Name = "Gödöllő, Szabadság tér" },
				new Stop { ID = 162, Name = "Gödöllő, Palotakert" },
				new Stop { ID = 163, Name = "Gödöllő" },
				new Stop { ID = 164, Name = "Bártfai utca" },
				new Stop { ID = 165, Name = "Etele út / Fehérvári út" },
				new Stop { ID = 166, Name = "Hengermalom út / Szerémi út" },
				new Stop { ID = 167, Name = "Hauszmann Alajos utca / Szerémi út" },
				new Stop { ID = 168, Name = "Budafoki út / Dombóvári út" },
				new Stop { ID = 169, Name = "Infopark" },
				new Stop { ID = 170, Name = "Mester utca / Könyves Kálmán körút" },
				new Stop { ID = 171, Name = "Ferencváros vasútállomás - Málenkij Robot Emlékhely" },
				new Stop { ID = 172, Name = "Albert Flórián út" },
				new Stop { ID = 173, Name = "Vajda Péter utca" },
				new Stop { ID = 174, Name = "Kőbányai út / Könyves Kálmán körút" },
				new Stop { ID = 175, Name = "Hidegkuti Nándor Stadion" },
				new Stop { ID = 176, Name = "Hős utca" },
				new Stop { ID = 177, Name = "Egressy út / Hungária körút" },
				new Stop { ID = 178, Name = "Ajtói Dürer sor" },
				new Stop { ID = 179, Name = "Kacsóh Pongrác út" },
				new Stop { ID = 180, Name = "Vágány utca / Róbert Károly körút" },
				new Stop { ID = 181, Name = "Lehel utca / Róbert Károly körút" },
				new Stop { ID = 182, Name = "Honvédkórház" },
				new Stop { ID = 183, Name = "Népfürdő utca / Árpád híd" },
				new Stop { ID = 184, Name = "Flórián tér" },
				new Stop { ID = 185, Name = "Óbudai rendelőintézet" },
				new Stop { ID = 186, Name = "Bécsi út / Vörösvári út" },
				new Stop { ID = 187, Name = "Jászai Mari tér" },
				new Stop { ID = 188, Name = "Országház, látogatóközpont" },
				new Stop { ID = 189, Name = "Széchenyi István tér" },
				new Stop { ID = 190, Name = "Eötvös tér" },
				new Stop { ID = 191, Name = "Vigadó tér" },
				new Stop { ID = 192, Name = "Zsil utca" },
				new Stop { ID = 193, Name = "Haller utca / Soroksári utca" },
				new Stop { ID = 194, Name = "Nagy Lajos király útja / Czobor utca" },
				new Stop { ID = 195, Name = "Kerékgyártó utca" },
				new Stop { ID = 196, Name = "Egressy tér" },
				new Stop { ID = 197, Name = "Jeszenák János utca" },
				new Stop { ID = 198, Name = "Pongrátz Gergely tér" },
				new Stop { ID = 199, Name = "Tihamér utca" },
				new Stop { ID = 200, Name = "Fehér úti ipari park" },
				new Stop { ID = 201, Name = "Terebesi utca" },
				new Stop { ID = 202, Name = "Élessarok" },
				new Stop { ID = 203, Name = "Ónodi utca" },
				new Stop { ID = 204, Name = "Szent László tér" },
				new Stop { ID = 205, Name = "Kőbánya alsó vasútállomás" },
				new Stop { ID = 206, Name = "Kocsis Sándor Sportközpont" },
				new Stop { ID = 207, Name = "Fertő utca / Bihari utca" },
				new Stop { ID = 208, Name = "Balkán utca" },
				new Stop { ID = 209, Name = "Közterületfenntartó Zrt." },
				new Stop { ID = 210, Name = "Csengettyű utca" },
				new Stop { ID = 211, Name = "Epreserdő utca" },
				new Stop { ID = 212, Name = "Nagykőrösi út / Határ út" },
				new Stop { ID = 213, Name = "Mártírok útja / Határ út" },
				new Stop { ID = 214, Name = "Jókai Mór utca / Határ út" },
				new Stop { ID = 215, Name = "Ősz utca" },
				new Stop { ID = 216, Name = "Gubacsi út / Határ út" },
				new Stop { ID = 217, Name = "Kőbánya alsó vasútállomás (Mázsa tér)" },
				new Stop { ID = 218, Name = "Széna tér" },
				new Stop { ID = 219, Name = "Mechwart liget" },
				new Stop { ID = 220, Name = "Margitsziget / Margit híd" },
				new Stop { ID = 221, Name = "Király utca / Erzsébet körút" },
				new Stop { ID = 222, Name = "Wesselényi utca / Erzsébet körút" },
				new Stop { ID = 223, Name = "Harminckettesek tere" },
				new Stop { ID = 224, Name = "Mester utca / Ferenc körút" },
				new Stop { ID = 225, Name = "Petőfi híd, budai hídfő" },
				new Stop { ID = 226, Name = "Budafoki út / Szerémi sor" },
				new Stop { ID = 227, Name = "Budafoki út / Karinthy Frigyes út" },
				new Stop { ID = 228, Name = "Pasaréti tér" },
				new Stop { ID = 229, Name = "Harangvirág utca" },
				new Stop { ID = 230, Name = "Virág árok" },
				new Stop { ID = 231, Name = "Gábor Áron utca / Pasaréti út" },
				new Stop { ID = 232, Name = "Júlia utca" },
				new Stop { ID = 233, Name = "Vasas sportpálya" },
				new Stop { ID = 234, Name = "Városmajor" },
				new Stop { ID = 235, Name = "Nyúl utca" },
				new Stop { ID = 236, Name = "Körmöci utca" },
				new Stop { ID = 237, Name = "Korlát utca" },
				new Stop { ID = 238, Name = "Mikó utca" },
				new Stop { ID = 239, Name = "Alagút utca" },
				new Stop { ID = 240, Name = "Dózsa György tér" },
				new Stop { ID = 241, Name = "Döbrentei tér" },
				new Stop { ID = 242, Name = "Korong utca" },
				new Stop { ID = 243, Name = "Fűrész utca" },
				new Stop { ID = 244, Name = "Rákospatak utca" },
				new Stop { ID = 245, Name = "Miskolci utca" },
				new Stop { ID = 246, Name = "Öv utca" },
				new Stop { ID = 247, Name = "Tóth István utca" },
				new Stop { ID = 248, Name = "Vág utca" },
				new Stop { ID = 249, Name = "Opál utca" },
				new Stop { ID = 250, Name = "Széchenyi út" },
				new Stop { ID = 251, Name = "Szent Korona útja" },
				new Stop { ID = 252, Name = "Wesselényi utca" },
				new Stop { ID = 253, Name = "Szerencs utca" },
				new Stop { ID = 254, Name = "Rákos úti szakrendelő" },
				new Stop { ID = 255, Name = "Illyés Gyula utca" },
				new Stop { ID = 256, Name = "Epres sor" },
				new Stop { ID = 257, Name = "Juhos utca" },
				new Stop { ID = 258, Name = "Kossuth utca, lakótelep" },
				new Stop { ID = 259, Name = "Rákospalota, Kossuth utca" },
				new Stop { ID = 260, Name = "Szarvas tér" }//,
				//new Stop { ID = 226, Name = "" },
				);

			modelBuilder.Entity<RouteStop>().HasData(
				new RouteStop { ID = 1, RouteID = 01, StopID = 001, Direction = Direction.Outbound, Order = 1 },
				new RouteStop { ID = 2, RouteID = 01, StopID = 002, Direction = Direction.Outbound, Order = 2 },
				new RouteStop {ID = 3, RouteID = 01, StopID = 003, Direction = Direction.Outbound, Order = 3 },
				new RouteStop {ID = 4, RouteID = 01, StopID = 004, Direction = Direction.Outbound, Order = 4 },
				new RouteStop {ID = 5, RouteID = 01, StopID = 005, Direction = Direction.Outbound, Order = 5 },
				new RouteStop {ID = 6, RouteID = 01, StopID = 006, Direction = Direction.Outbound, Order = 6 },
				new RouteStop {ID = 7, RouteID = 01, StopID = 007, Direction = Direction.Outbound, Order = 7 },
				new RouteStop {ID = 8, RouteID = 01, StopID = 008, Direction = Direction.Outbound, Order = 8 },
				new RouteStop {ID = 9, RouteID = 01, StopID = 009, Direction = Direction.Outbound, Order = 9 },
				new RouteStop {ID = 10, RouteID = 01, StopID = 010, Direction = Direction.Outbound, Order = 10 },
				new RouteStop {ID = 11, RouteID = 01, StopID = 011, Direction = Direction.Outbound, Order = 11 },
				new RouteStop {ID = 12, RouteID = 01, StopID = 012, Direction = Direction.Outbound, Order = 12 },
				new RouteStop {ID = 13, RouteID = 01, StopID = 013, Direction = Direction.Outbound, Order = 13 },
				new RouteStop {ID = 14, RouteID = 01, StopID = 014, Direction = Direction.Outbound, Order = 14 },
				new RouteStop {ID = 15, RouteID = 01, StopID = 015, Direction = Direction.Outbound, Order = 15 },
				new RouteStop {ID = 16, RouteID = 01, StopID = 016, Direction = Direction.Outbound, Order = 16 },
				new RouteStop {ID = 17, RouteID = 01, StopID = 017, Direction = Direction.Outbound, Order = 17 },
				new RouteStop {ID = 18, RouteID = 01, StopID = 018, Direction = Direction.Outbound, Order = 18 },
				new RouteStop {ID = 19, RouteID = 01, StopID = 019, Direction = Direction.Outbound, Order = 19 },
				new RouteStop {ID = 20, RouteID = 01, StopID = 020, Direction = Direction.Outbound, Order = 20 },
				new RouteStop {ID = 21, RouteID = 01, StopID = 021, Direction = Direction.Outbound, Order = 21 },
				new RouteStop {ID = 22, RouteID = 01, StopID = 022, Direction = Direction.Outbound, Order = 22 },
				new RouteStop {ID = 23, RouteID = 01, StopID = 023, Direction = Direction.Outbound, Order = 23 },
				new RouteStop {ID = 24, RouteID = 01, StopID = 024, Direction = Direction.Outbound, Order = 24 },
				new RouteStop {ID = 25, RouteID = 01, StopID = 025, Direction = Direction.Outbound, Order = 25 },
				new RouteStop {ID = 26, RouteID = 01, StopID = 026, Direction = Direction.Outbound, Order = 26 },
				new RouteStop {ID = 27, RouteID = 01, StopID = 027, Direction = Direction.Outbound, Order = 27 },
				new RouteStop {ID = 28, RouteID = 01, StopID = 028, Direction = Direction.Outbound, Order = 28 },
				new RouteStop {ID = 29, RouteID = 01, StopID = 029, Direction = Direction.Outbound, Order = 29 },
				new RouteStop {ID = 30, RouteID = 01, StopID = 030, Direction = Direction.Outbound, Order = 30 },
				new RouteStop {ID = 31, RouteID = 01, StopID = 031, Direction = Direction.Outbound, Order = 31 },
				new RouteStop {ID = 32, RouteID = 01, StopID = 032, Direction = Direction.Outbound, Order = 32 },
				new RouteStop {ID = 33, RouteID = 01, StopID = 033, Direction = Direction.Outbound, Order = 33 },
				new RouteStop {ID = 34, RouteID = 01, StopID = 034, Direction = Direction.Outbound, Order = 34 },
				new RouteStop {ID = 35, RouteID = 01, StopID = 035, Direction = Direction.Outbound, Order = 35 },
				new RouteStop {ID = 36, RouteID = 01, StopID = 036, Direction = Direction.Outbound, Order = 36 },
				new RouteStop {ID = 37, RouteID = 01, StopID = 037, Direction = Direction.Outbound, Order = 37 },
				new RouteStop {ID = 38, RouteID = 01, StopID = 038, Direction = Direction.Outbound, Order = 38 },
				new RouteStop {ID = 39, RouteID = 01, StopID = 039, Direction = Direction.Outbound, Order = 39 },
				new RouteStop { ID = 40, RouteID = 01, StopID = 039, Direction = Direction.Inbound, Order = 1 },
				new RouteStop { ID = 41, RouteID = 01, StopID = 038, Direction = Direction.Inbound, Order = 2 },
				new RouteStop { ID = 42, RouteID = 01, StopID = 037, Direction = Direction.Inbound, Order = 3 },
				new RouteStop { ID = 43, RouteID = 01, StopID = 036, Direction = Direction.Inbound, Order = 4 },
				new RouteStop { ID = 44, RouteID = 01, StopID = 035, Direction = Direction.Inbound, Order = 5 },
				new RouteStop { ID = 45, RouteID = 01, StopID = 034, Direction = Direction.Inbound, Order = 6 },
				new RouteStop { ID = 46, RouteID = 01, StopID = 033, Direction = Direction.Inbound, Order = 7 },
				new RouteStop { ID = 47, RouteID = 01, StopID = 032, Direction = Direction.Inbound, Order = 8 },
				new RouteStop { ID = 48, RouteID = 01, StopID = 031, Direction = Direction.Inbound, Order = 9 },
				new RouteStop { ID = 49, RouteID = 01, StopID = 030, Direction = Direction.Inbound, Order = 10 },
				new RouteStop { ID = 50, RouteID = 01, StopID = 029, Direction = Direction.Inbound, Order = 11 },
				new RouteStop { ID = 51, RouteID = 01, StopID = 028, Direction = Direction.Inbound, Order = 12 },
				new RouteStop { ID = 52, RouteID = 01, StopID = 027, Direction = Direction.Inbound, Order = 13 },
				new RouteStop { ID = 53, RouteID = 01, StopID = 026, Direction = Direction.Inbound, Order = 14 },
				new RouteStop { ID = 54, RouteID = 01, StopID = 025, Direction = Direction.Inbound, Order = 15 },
				new RouteStop { ID = 55, RouteID = 01, StopID = 024, Direction = Direction.Inbound, Order = 16 },
				new RouteStop { ID = 56, RouteID = 01, StopID = 023, Direction = Direction.Inbound, Order = 17 },
				new RouteStop { ID = 57, RouteID = 01, StopID = 022, Direction = Direction.Inbound, Order = 18 },
				new RouteStop { ID = 58, RouteID = 01, StopID = 021, Direction = Direction.Inbound, Order = 19 },
				new RouteStop { ID = 59, RouteID = 01, StopID = 020, Direction = Direction.Inbound, Order = 20 },
				new RouteStop { ID = 60, RouteID = 01, StopID = 019, Direction = Direction.Inbound, Order = 21 },
				new RouteStop { ID = 61, RouteID = 01, StopID = 018, Direction = Direction.Inbound, Order = 22 },
				new RouteStop { ID = 62, RouteID = 01, StopID = 017, Direction = Direction.Inbound, Order = 23 },
				new RouteStop { ID = 63, RouteID = 01, StopID = 016, Direction = Direction.Inbound, Order = 24 },
				new RouteStop { ID = 64, RouteID = 01, StopID = 015, Direction = Direction.Inbound, Order = 25 },
				new RouteStop { ID = 65, RouteID = 01, StopID = 014, Direction = Direction.Inbound, Order = 26 },
				new RouteStop { ID = 66, RouteID = 01, StopID = 013, Direction = Direction.Inbound, Order = 27 },
				new RouteStop { ID = 67, RouteID = 01, StopID = 012, Direction = Direction.Inbound, Order = 28 },
				new RouteStop { ID = 68, RouteID = 01, StopID = 011, Direction = Direction.Inbound, Order = 29 },
				new RouteStop { ID = 69, RouteID = 01, StopID = 010, Direction = Direction.Inbound, Order = 30 },
				new RouteStop { ID = 70, RouteID = 01, StopID = 009, Direction = Direction.Inbound, Order = 31 },
				new RouteStop { ID = 71, RouteID = 01, StopID = 008, Direction = Direction.Inbound, Order = 32 },
				new RouteStop { ID = 72, RouteID = 01, StopID = 007, Direction = Direction.Inbound, Order = 33 },
				new RouteStop { ID = 73, RouteID = 01, StopID = 005, Direction = Direction.Inbound, Order = 34 },
				new RouteStop { ID = 74, RouteID = 01, StopID = 004, Direction = Direction.Inbound, Order = 35 },
				new RouteStop { ID = 75, RouteID = 01, StopID = 003, Direction = Direction.Inbound, Order = 36 },
				new RouteStop { ID = 76, RouteID = 01, StopID = 002, Direction = Direction.Inbound, Order = 37 },
				new RouteStop { ID = 77, RouteID = 01, StopID = 001, Direction = Direction.Inbound, Order = 38 },
				new RouteStop { ID = 78, RouteID = 02, StopID = 022, Direction = Direction.Outbound, Order = 1},
				new RouteStop { ID = 79, RouteID = 02, StopID = 022, Direction = Direction.Outbound, Order = 2},
				new RouteStop { ID = 80, RouteID = 02, StopID = 024, Direction = Direction.Outbound, Order = 3},
				new RouteStop { ID = 81, RouteID = 02, StopID = 028, Direction = Direction.Outbound, Order = 4},
				new RouteStop { ID = 82, RouteID = 02, StopID = 030, Direction = Direction.Outbound, Order = 5},
				new RouteStop { ID = 83, RouteID = 02, StopID = 034, Direction = Direction.Outbound, Order = 6},
				new RouteStop { ID = 84, RouteID = 02, StopID = 037, Direction = Direction.Outbound, Order = 7},
				new RouteStop { ID = 85, RouteID = 02, StopID = 038, Direction = Direction.Outbound, Order = 8},
				new RouteStop { ID = 86, RouteID = 02, StopID = 039, Direction = Direction.Outbound, Order = 9},
				new RouteStop { ID = 87, RouteID = 02, StopID = 039, Direction = Direction.Inbound, Order = 1},
				new RouteStop { ID = 88, RouteID = 02, StopID = 038, Direction = Direction.Inbound, Order = 2},
				new RouteStop { ID = 89, RouteID = 02, StopID = 037, Direction = Direction.Inbound, Order = 3},
				new RouteStop { ID = 90, RouteID = 02, StopID = 034, Direction = Direction.Inbound, Order = 4},
				new RouteStop { ID = 91, RouteID = 02, StopID = 030, Direction = Direction.Inbound, Order = 5},
				new RouteStop { ID = 92, RouteID = 02, StopID = 028, Direction = Direction.Inbound, Order = 6},
				new RouteStop { ID = 93, RouteID = 02, StopID = 024, Direction = Direction.Inbound, Order = 7},
				new RouteStop { ID = 94, RouteID = 02, StopID = 022, Direction = Direction.Inbound, Order = 8},
				new RouteStop { ID = 95, RouteID = 02, StopID = 022, Direction = Direction.Inbound, Order = 9},
				new RouteStop { ID = 96, RouteID = 03, StopID = 040, Direction = Direction.Outbound, Order = 1},
				new RouteStop { ID = 97, RouteID = 03, StopID = 041, Direction = Direction.Outbound, Order = 2},
				new RouteStop { ID = 98, RouteID = 03, StopID = 042, Direction = Direction.Outbound, Order = 3},
				new RouteStop { ID = 99, RouteID = 03, StopID = 029, Direction = Direction.Outbound, Order = 4},
				new RouteStop { ID = 100, RouteID = 03, StopID = 043, Direction = Direction.Outbound, Order = 5},
				new RouteStop { ID = 101, RouteID = 03, StopID = 044, Direction = Direction.Outbound, Order = 6},
				new RouteStop { ID = 102, RouteID = 03, StopID = 045, Direction = Direction.Outbound, Order = 7},
				new RouteStop { ID = 103, RouteID = 03, StopID = 046, Direction = Direction.Outbound, Order = 8},
				new RouteStop { ID = 104, RouteID = 03, StopID = 047, Direction = Direction.Outbound, Order = 9},
				new RouteStop { ID = 105, RouteID = 03, StopID = 048, Direction = Direction.Outbound, Order = 10},
				new RouteStop { ID = 106, RouteID = 03, StopID = 049, Direction = Direction.Outbound, Order = 11},
				new RouteStop { ID = 107, RouteID = 03, StopID = 050, Direction = Direction.Outbound, Order = 12},
				new RouteStop { ID = 108, RouteID = 03, StopID = 051, Direction = Direction.Outbound, Order = 13},
				new RouteStop { ID = 109, RouteID = 03, StopID = 052, Direction = Direction.Outbound, Order = 14},
				new RouteStop { ID = 110, RouteID = 03, StopID = 053, Direction = Direction.Outbound, Order = 15},
				new RouteStop { ID = 111, RouteID = 03, StopID = 054, Direction = Direction.Outbound, Order = 16},
				new RouteStop { ID = 112, RouteID = 03, StopID = 054, Direction = Direction.Inbound, Order = 1},
				new RouteStop { ID = 113, RouteID = 03, StopID = 053, Direction = Direction.Inbound, Order = 2},
				new RouteStop { ID = 114, RouteID = 03, StopID = 052, Direction = Direction.Inbound, Order = 3},
				new RouteStop { ID = 115, RouteID = 03, StopID = 051, Direction = Direction.Inbound, Order = 4},
				new RouteStop { ID = 116, RouteID = 03, StopID = 050, Direction = Direction.Inbound, Order = 5},
				new RouteStop { ID = 117, RouteID = 03, StopID = 049, Direction = Direction.Inbound, Order = 6},
				new RouteStop { ID = 118, RouteID = 03, StopID = 048, Direction = Direction.Inbound, Order = 7},
				new RouteStop { ID = 119, RouteID = 03, StopID = 047, Direction = Direction.Inbound, Order = 8},
				new RouteStop { ID = 120, RouteID = 03, StopID = 046, Direction = Direction.Inbound, Order = 9},
				new RouteStop { ID = 121, RouteID = 03, StopID = 045, Direction = Direction.Inbound, Order = 10},
				new RouteStop { ID = 122, RouteID = 03, StopID = 044, Direction = Direction.Inbound, Order = 11},
				new RouteStop { ID = 123, RouteID = 03, StopID = 043, Direction = Direction.Inbound, Order = 12},
				new RouteStop { ID = 124, RouteID = 03, StopID = 029, Direction = Direction.Inbound, Order = 13},
				new RouteStop { ID = 125, RouteID = 03, StopID = 042, Direction = Direction.Inbound, Order = 14},
				new RouteStop { ID = 126, RouteID = 03, StopID = 055, Direction = Direction.Inbound, Order = 15},
				new RouteStop { ID = 127, RouteID = 03, StopID = 056, Direction = Direction.Inbound, Order = 16},
				new RouteStop { ID = 128, RouteID = 03, StopID = 057, Direction = Direction.Inbound, Order = 17},
				new RouteStop { ID = 129, RouteID = 03, StopID = 040, Direction = Direction.Inbound, Order = 18},
				new RouteStop { ID = 130, RouteID = 04, StopID = 055, Direction = Direction.Outbound, Order = 1},
				new RouteStop { ID = 131, RouteID = 04, StopID = 042, Direction = Direction.Outbound, Order = 2},
				new RouteStop { ID = 132, RouteID = 04, StopID = 029, Direction = Direction.Outbound, Order = 3},
				new RouteStop { ID = 133, RouteID = 04, StopID = 043, Direction = Direction.Outbound, Order = 4},
				new RouteStop { ID = 134, RouteID = 04, StopID = 044, Direction = Direction.Outbound, Order = 5},
				new RouteStop { ID = 135, RouteID = 04, StopID = 045, Direction = Direction.Outbound, Order = 6},
				new RouteStop { ID = 136, RouteID = 04, StopID = 046, Direction = Direction.Outbound, Order = 7},
				new RouteStop { ID = 137, RouteID = 04, StopID = 047, Direction = Direction.Outbound, Order = 8},
				new RouteStop { ID = 138, RouteID = 04, StopID = 048, Direction = Direction.Outbound, Order = 9},
				new RouteStop { ID = 139, RouteID = 04, StopID = 049, Direction = Direction.Outbound, Order = 10},
				new RouteStop { ID = 140, RouteID = 04, StopID = 050, Direction = Direction.Outbound, Order = 11},
				new RouteStop { ID = 141, RouteID = 04, StopID = 051, Direction = Direction.Outbound, Order = 12},
				new RouteStop { ID = 142, RouteID = 04, StopID = 052, Direction = Direction.Outbound, Order = 13},
				new RouteStop { ID = 143, RouteID = 04, StopID = 053, Direction = Direction.Outbound, Order = 14},
				new RouteStop { ID = 144, RouteID = 04, StopID = 054, Direction = Direction.Outbound, Order = 15},
				new RouteStop { ID = 145, RouteID = 04, StopID = 054, Direction = Direction.Inbound, Order = 1},
				new RouteStop { ID = 146, RouteID = 04, StopID = 053, Direction = Direction.Inbound, Order = 2},
				new RouteStop { ID = 147, RouteID = 04, StopID = 052, Direction = Direction.Inbound, Order = 3},
				new RouteStop { ID = 148, RouteID = 04, StopID = 051, Direction = Direction.Inbound, Order = 4},
				new RouteStop { ID = 149, RouteID = 04, StopID = 050, Direction = Direction.Inbound, Order = 5},
				new RouteStop { ID = 150, RouteID = 04, StopID = 049, Direction = Direction.Inbound, Order = 6},
				new RouteStop { ID = 151, RouteID = 04, StopID = 048, Direction = Direction.Inbound, Order = 7},
				new RouteStop { ID = 152, RouteID = 04, StopID = 047, Direction = Direction.Inbound, Order = 8},
				new RouteStop { ID = 153, RouteID = 04, StopID = 046, Direction = Direction.Inbound, Order = 9},
				new RouteStop { ID = 154, RouteID = 04, StopID = 045, Direction = Direction.Inbound, Order = 10},
				new RouteStop { ID = 155, RouteID = 04, StopID = 044, Direction = Direction.Inbound, Order = 11},
				new RouteStop { ID = 156, RouteID = 04, StopID = 043, Direction = Direction.Inbound, Order = 12},
				new RouteStop { ID = 157, RouteID = 04, StopID = 029, Direction = Direction.Inbound, Order = 13},
				new RouteStop { ID = 158, RouteID = 04, StopID = 042, Direction = Direction.Inbound, Order = 14},
				new RouteStop { ID = 159, RouteID = 04, StopID = 055, Direction = Direction.Inbound, Order = 15},
				new RouteStop { ID = 160, RouteID = 05, StopID = 058, Direction = Direction.Outbound, Order = 1},
				new RouteStop { ID = 161, RouteID = 05, StopID = 059, Direction = Direction.Outbound, Order = 2},
				new RouteStop { ID = 162, RouteID = 05, StopID = 060, Direction = Direction.Outbound, Order = 3},
				new RouteStop { ID = 163, RouteID = 05, StopID = 061, Direction = Direction.Outbound, Order = 4},
				new RouteStop { ID = 164, RouteID = 05, StopID = 062, Direction = Direction.Outbound, Order = 5},
				new RouteStop { ID = 165, RouteID = 05, StopID = 063, Direction = Direction.Outbound, Order = 6},
				new RouteStop { ID = 166, RouteID = 05, StopID = 064, Direction = Direction.Outbound, Order = 7},
				new RouteStop { ID = 167, RouteID = 05, StopID = 065, Direction = Direction.Outbound, Order = 8},
				new RouteStop { ID = 168, RouteID = 05, StopID = 066, Direction = Direction.Outbound, Order = 9},
				new RouteStop { ID = 169, RouteID = 05, StopID = 067, Direction = Direction.Outbound, Order = 10},
				new RouteStop { ID = 170, RouteID = 05, StopID = 040, Direction = Direction.Outbound, Order = 11},
				new RouteStop { ID = 171, RouteID = 05, StopID = 040, Direction = Direction.Inbound, Order = 1},
				new RouteStop { ID = 172, RouteID = 05, StopID = 067, Direction = Direction.Inbound, Order = 2},
				new RouteStop { ID = 173, RouteID = 05, StopID = 066, Direction = Direction.Inbound, Order = 3},
				new RouteStop { ID = 174, RouteID = 05, StopID = 065, Direction = Direction.Inbound, Order = 4},
				new RouteStop { ID = 175, RouteID = 05, StopID = 064, Direction = Direction.Inbound, Order = 5},
				new RouteStop { ID = 176, RouteID = 05, StopID = 063, Direction = Direction.Inbound, Order = 6},
				new RouteStop { ID = 177, RouteID = 05, StopID = 062, Direction = Direction.Inbound, Order = 7},
				new RouteStop { ID = 178, RouteID = 05, StopID = 061, Direction = Direction.Inbound, Order = 8},
				new RouteStop { ID = 179, RouteID = 05, StopID = 060, Direction = Direction.Inbound, Order = 9},
				new RouteStop { ID = 180, RouteID = 05, StopID = 059, Direction = Direction.Inbound, Order = 10},
				new RouteStop { ID = 181, RouteID = 05, StopID = 058, Direction = Direction.Inbound, Order = 11},
				new RouteStop { ID = 182, RouteID = 06, StopID = 068, Direction = Direction.Outbound, Order = 1},
				new RouteStop { ID = 183, RouteID = 06, StopID = 069, Direction = Direction.Outbound, Order = 2},
				new RouteStop { ID = 184, RouteID = 06, StopID = 070, Direction = Direction.Outbound, Order = 3},
				new RouteStop { ID = 185, RouteID = 06, StopID = 071, Direction = Direction.Outbound, Order = 4},
				new RouteStop { ID = 186, RouteID = 06, StopID = 059, Direction = Direction.Outbound, Order = 5},
				new RouteStop { ID = 187, RouteID = 06, StopID = 020, Direction = Direction.Outbound, Order = 6},
				new RouteStop { ID = 188, RouteID = 06, StopID = 022, Direction = Direction.Outbound, Order = 7},
				new RouteStop { ID = 189, RouteID = 06, StopID = 024, Direction = Direction.Outbound, Order = 8},
				new RouteStop { ID = 190, RouteID = 06, StopID = 072, Direction = Direction.Outbound, Order = 9},
				new RouteStop { ID = 191, RouteID = 06, StopID = 073, Direction = Direction.Outbound, Order = 10},
				new RouteStop { ID = 192, RouteID = 06, StopID = 054, Direction = Direction.Outbound, Order = 11},
				new RouteStop { ID = 193, RouteID = 06, StopID = 054, Direction = Direction.Inbound, Order = 1},
				new RouteStop { ID = 194, RouteID = 06, StopID = 073, Direction = Direction.Inbound, Order = 2},
				new RouteStop { ID = 195, RouteID = 06, StopID = 072, Direction = Direction.Inbound, Order = 3},
				new RouteStop { ID = 196, RouteID = 06, StopID = 024, Direction = Direction.Inbound, Order = 4},
				new RouteStop { ID = 197, RouteID = 06, StopID = 022, Direction = Direction.Inbound, Order = 5},
				new RouteStop { ID = 198, RouteID = 06, StopID = 020, Direction = Direction.Inbound, Order = 6},
				new RouteStop { ID = 199, RouteID = 06, StopID = 059, Direction = Direction.Inbound, Order = 7},
				new RouteStop { ID = 200, RouteID = 06, StopID = 071, Direction = Direction.Inbound, Order = 8},
				new RouteStop { ID = 201, RouteID = 06, StopID = 070, Direction = Direction.Inbound, Order = 9},
				new RouteStop { ID = 202, RouteID = 06, StopID = 069, Direction = Direction.Inbound, Order = 10},
				new RouteStop { ID = 203, RouteID = 06, StopID = 068, Direction = Direction.Inbound, Order = 11},
				new RouteStop { ID = 204, RouteID = 07, StopID = 074, Direction = Direction.Outbound, Order = 1},
				new RouteStop { ID = 205, RouteID = 07, StopID = 075, Direction = Direction.Outbound, Order = 2},
				new RouteStop { ID = 206, RouteID = 07, StopID = 076, Direction = Direction.Outbound, Order = 3},
				new RouteStop { ID = 207, RouteID = 07, StopID = 077, Direction = Direction.Outbound, Order = 4},
				new RouteStop { ID = 208, RouteID = 07, StopID = 078, Direction = Direction.Outbound, Order = 5},
				new RouteStop { ID = 209, RouteID = 07, StopID = 079, Direction = Direction.Outbound, Order = 6},
				new RouteStop { ID = 210, RouteID = 07, StopID = 080, Direction = Direction.Outbound, Order = 7},
				new RouteStop { ID = 211, RouteID = 07, StopID = 081, Direction = Direction.Outbound, Order = 8},
				new RouteStop { ID = 212, RouteID = 07, StopID = 082, Direction = Direction.Outbound, Order = 9},
				new RouteStop { ID = 213, RouteID = 07, StopID = 059, Direction = Direction.Outbound, Order = 10},
				new RouteStop { ID = 214, RouteID = 07, StopID = 019, Direction = Direction.Outbound, Order = 11},
				new RouteStop { ID = 215, RouteID = 07, StopID = 083, Direction = Direction.Outbound, Order = 12},
				new RouteStop { ID = 216, RouteID = 07, StopID = 084, Direction = Direction.Outbound, Order = 13},
				new RouteStop { ID = 217, RouteID = 07, StopID = 085, Direction = Direction.Outbound, Order = 14},
				new RouteStop { ID = 218, RouteID = 07, StopID = 086, Direction = Direction.Outbound, Order = 15},
				new RouteStop { ID = 219, RouteID = 07, StopID = 087, Direction = Direction.Outbound, Order = 16},
				new RouteStop { ID = 220, RouteID = 07, StopID = 088, Direction = Direction.Outbound, Order = 17},
				new RouteStop { ID = 221, RouteID = 07, StopID = 089, Direction = Direction.Outbound, Order = 18},
				new RouteStop { ID = 222, RouteID = 07, StopID = 090, Direction = Direction.Outbound, Order = 19},
				new RouteStop { ID = 223, RouteID = 07, StopID = 091, Direction = Direction.Outbound, Order = 20},
				new RouteStop { ID = 224, RouteID = 07, StopID = 091, Direction = Direction.Inbound, Order = 1},
				new RouteStop { ID = 225, RouteID = 07, StopID = 090, Direction = Direction.Inbound, Order = 2},
				new RouteStop { ID = 226, RouteID = 07, StopID = 089, Direction = Direction.Inbound, Order = 3},
				new RouteStop { ID = 227, RouteID = 07, StopID = 088, Direction = Direction.Inbound, Order = 4},
				new RouteStop { ID = 228, RouteID = 07, StopID = 087, Direction = Direction.Inbound, Order = 5},
				new RouteStop { ID = 229, RouteID = 07, StopID = 086, Direction = Direction.Inbound, Order = 6},
				new RouteStop { ID = 230, RouteID = 07, StopID = 085, Direction = Direction.Inbound, Order = 7},
				new RouteStop { ID = 231, RouteID = 07, StopID = 084, Direction = Direction.Inbound, Order = 8},
				new RouteStop { ID = 232, RouteID = 07, StopID = 083, Direction = Direction.Inbound, Order = 9},
				new RouteStop { ID = 233, RouteID = 07, StopID = 019, Direction = Direction.Inbound, Order = 10},
				new RouteStop { ID = 234, RouteID = 07, StopID = 059, Direction = Direction.Inbound, Order = 11},
				new RouteStop { ID = 235, RouteID = 07, StopID = 082, Direction = Direction.Inbound, Order = 12},
				new RouteStop { ID = 236, RouteID = 07, StopID = 081, Direction = Direction.Inbound, Order = 13},
				new RouteStop { ID = 237, RouteID = 07, StopID = 080, Direction = Direction.Inbound, Order = 14},
				new RouteStop { ID = 238, RouteID = 07, StopID = 079, Direction = Direction.Inbound, Order = 15},
				new RouteStop { ID = 239, RouteID = 07, StopID = 078, Direction = Direction.Inbound, Order = 16},
				new RouteStop { ID = 240, RouteID = 07, StopID = 077, Direction = Direction.Inbound, Order = 17},
				new RouteStop { ID = 241, RouteID = 07, StopID = 076, Direction = Direction.Inbound, Order = 18},
				new RouteStop { ID = 242, RouteID = 07, StopID = 075, Direction = Direction.Inbound, Order = 19},
				new RouteStop { ID = 243, RouteID = 07, StopID = 074, Direction = Direction.Inbound, Order = 20},
				new RouteStop { ID = 244, RouteID = 08, StopID = 024, Direction = Direction.Outbound, Order = 1},
				new RouteStop { ID = 245, RouteID = 08, StopID = 092, Direction = Direction.Outbound, Order = 2},
				new RouteStop { ID = 246, RouteID = 08, StopID = 093, Direction = Direction.Outbound, Order = 3},
				new RouteStop { ID = 247, RouteID = 08, StopID = 083, Direction = Direction.Outbound, Order = 4},
				new RouteStop { ID = 248, RouteID = 08, StopID = 094, Direction = Direction.Outbound, Order = 5},
				new RouteStop { ID = 249, RouteID = 08, StopID = 016, Direction = Direction.Outbound, Order = 6},
				new RouteStop { ID = 250, RouteID = 08, StopID = 014, Direction = Direction.Outbound, Order = 7},
				new RouteStop { ID = 251, RouteID = 08, StopID = 095, Direction = Direction.Outbound, Order = 8},
				new RouteStop { ID = 252, RouteID = 08, StopID = 009, Direction = Direction.Outbound, Order = 9},
				new RouteStop { ID = 253, RouteID = 08, StopID = 096, Direction = Direction.Outbound, Order = 10},
				new RouteStop { ID = 254, RouteID = 08, StopID = 096, Direction = Direction.Inbound, Order = 1},
				new RouteStop { ID = 255, RouteID = 08, StopID = 009, Direction = Direction.Inbound, Order = 2},
				new RouteStop { ID = 256, RouteID = 08, StopID = 095, Direction = Direction.Inbound, Order = 3},
				new RouteStop { ID = 257, RouteID = 08, StopID = 014, Direction = Direction.Inbound, Order = 4},
				new RouteStop { ID = 258, RouteID = 08, StopID = 016, Direction = Direction.Inbound, Order = 5},
				new RouteStop { ID = 259, RouteID = 08, StopID = 094, Direction = Direction.Inbound, Order = 6},
				new RouteStop { ID = 260, RouteID = 08, StopID = 083, Direction = Direction.Inbound, Order = 7},
				new RouteStop { ID = 261, RouteID = 08, StopID = 093, Direction = Direction.Inbound, Order = 8},
				new RouteStop { ID = 262, RouteID = 08, StopID = 092, Direction = Direction.Inbound, Order = 9},
				new RouteStop { ID = 263, RouteID = 08, StopID = 024, Direction = Direction.Inbound, Order = 10},
				new RouteStop { ID = 264, RouteID = 09, StopID = 070, Direction = Direction.Outbound, Order = 1},
				new RouteStop { ID = 265, RouteID = 09, StopID = 097, Direction = Direction.Outbound, Order = 2},
				new RouteStop { ID = 266, RouteID = 09, StopID = 098, Direction = Direction.Outbound, Order = 3},
				new RouteStop { ID = 267, RouteID = 09, StopID = 099, Direction = Direction.Outbound, Order = 4},
				new RouteStop { ID = 268, RouteID = 09, StopID = 100, Direction = Direction.Outbound, Order = 5},
				new RouteStop { ID = 269, RouteID = 09, StopID = 101, Direction = Direction.Outbound, Order = 6},
				new RouteStop { ID = 270, RouteID = 09, StopID = 102, Direction = Direction.Outbound, Order = 7},
				new RouteStop { ID = 271, RouteID = 09, StopID = 103, Direction = Direction.Outbound, Order = 8},
				new RouteStop { ID = 272, RouteID = 09, StopID = 104, Direction = Direction.Outbound, Order = 9},
				new RouteStop { ID = 273, RouteID = 09, StopID = 105, Direction = Direction.Outbound, Order = 10},
				new RouteStop { ID = 274, RouteID = 09, StopID = 106, Direction = Direction.Outbound, Order = 11},
				new RouteStop { ID = 275, RouteID = 09, StopID = 107, Direction = Direction.Outbound, Order = 12},
				new RouteStop { ID = 276, RouteID = 09, StopID = 108, Direction = Direction.Outbound, Order = 13},
				new RouteStop { ID = 277, RouteID = 09, StopID = 109, Direction = Direction.Outbound, Order = 14},
				new RouteStop { ID = 278, RouteID = 09, StopID = 110, Direction = Direction.Outbound, Order = 15},
				new RouteStop { ID = 279, RouteID = 09, StopID = 111, Direction = Direction.Outbound, Order = 16},
				new RouteStop { ID = 280, RouteID = 09, StopID = 112, Direction = Direction.Outbound, Order = 17},
				new RouteStop { ID = 281, RouteID = 09, StopID = 112, Direction = Direction.Inbound, Order = 1},
				new RouteStop { ID = 282, RouteID = 09, StopID = 111, Direction = Direction.Inbound, Order = 2},
				new RouteStop { ID = 283, RouteID = 09, StopID = 110, Direction = Direction.Inbound, Order = 3},
				new RouteStop { ID = 284, RouteID = 09, StopID = 109, Direction = Direction.Inbound, Order = 4},
				new RouteStop { ID = 285, RouteID = 09, StopID = 108, Direction = Direction.Inbound, Order = 5},
				new RouteStop { ID = 286, RouteID = 09, StopID = 107, Direction = Direction.Inbound, Order = 6},
				new RouteStop { ID = 287, RouteID = 09, StopID = 106, Direction = Direction.Inbound, Order = 7},
				new RouteStop { ID = 288, RouteID = 09, StopID = 105, Direction = Direction.Inbound, Order = 8},
				new RouteStop { ID = 289, RouteID = 09, StopID = 104, Direction = Direction.Inbound, Order = 9},
				new RouteStop { ID = 290, RouteID = 09, StopID = 103, Direction = Direction.Inbound, Order = 10},
				new RouteStop { ID = 291, RouteID = 09, StopID = 102, Direction = Direction.Inbound, Order = 11},
				new RouteStop { ID = 292, RouteID = 09, StopID = 101, Direction = Direction.Inbound, Order = 12},
				new RouteStop { ID = 293, RouteID = 09, StopID = 100, Direction = Direction.Inbound, Order = 13},
				new RouteStop { ID = 294, RouteID = 09, StopID = 099, Direction = Direction.Inbound, Order = 14},
				new RouteStop { ID = 295, RouteID = 09, StopID = 098, Direction = Direction.Inbound, Order = 15},
				new RouteStop { ID = 296, RouteID = 09, StopID = 097, Direction = Direction.Inbound, Order = 16},
				new RouteStop { ID = 297, RouteID = 09, StopID = 070, Direction = Direction.Inbound, Order = 17},
				new RouteStop { ID = 298, RouteID = 10, StopID = 113, Direction = Direction.Outbound, Order = 1},
				new RouteStop { ID = 299, RouteID = 10, StopID = 114, Direction = Direction.Outbound, Order = 2},
				new RouteStop { ID = 300, RouteID = 10, StopID = 115, Direction = Direction.Outbound, Order = 3},
				new RouteStop { ID = 301, RouteID = 10, StopID = 116, Direction = Direction.Outbound, Order = 4},
				new RouteStop { ID = 302, RouteID = 10, StopID = 117, Direction = Direction.Outbound, Order = 5},
				new RouteStop { ID = 303, RouteID = 10, StopID = 118, Direction = Direction.Outbound, Order = 6},
				new RouteStop { ID = 304, RouteID = 10, StopID = 119, Direction = Direction.Outbound, Order = 7},
				new RouteStop { ID = 305, RouteID = 10, StopID = 120, Direction = Direction.Outbound, Order = 8},
				new RouteStop { ID = 306, RouteID = 10, StopID = 121, Direction = Direction.Outbound, Order = 9},
				new RouteStop { ID = 307, RouteID = 10, StopID = 122, Direction = Direction.Outbound, Order = 10},
				new RouteStop { ID = 308, RouteID = 10, StopID = 123, Direction = Direction.Outbound, Order = 11},
				new RouteStop { ID = 309, RouteID = 10, StopID = 124, Direction = Direction.Outbound, Order = 12},
				new RouteStop { ID = 310, RouteID = 10, StopID = 125, Direction = Direction.Outbound, Order = 13},
				new RouteStop { ID = 311, RouteID = 10, StopID = 126, Direction = Direction.Outbound, Order = 14},
				new RouteStop { ID = 312, RouteID = 10, StopID = 127, Direction = Direction.Outbound, Order = 15},
				new RouteStop { ID = 313, RouteID = 10, StopID = 128, Direction = Direction.Outbound, Order = 16},
				new RouteStop { ID = 314, RouteID = 10, StopID = 129, Direction = Direction.Outbound, Order = 17},
				new RouteStop { ID = 315, RouteID = 10, StopID = 130, Direction = Direction.Outbound, Order = 18},
				new RouteStop { ID = 316, RouteID = 10, StopID = 131, Direction = Direction.Outbound, Order = 19},
				new RouteStop { ID = 317, RouteID = 10, StopID = 132, Direction = Direction.Outbound, Order = 20},
				new RouteStop { ID = 318, RouteID = 10, StopID = 133, Direction = Direction.Outbound, Order = 21},
				new RouteStop { ID = 319, RouteID = 10, StopID = 134, Direction = Direction.Outbound, Order = 22},
				new RouteStop { ID = 320, RouteID = 10, StopID = 134, Direction = Direction.Inbound, Order = 1},
				new RouteStop { ID = 321, RouteID = 10, StopID = 133, Direction = Direction.Inbound, Order = 2},
				new RouteStop { ID = 322, RouteID = 10, StopID = 132, Direction = Direction.Inbound, Order = 3},
				new RouteStop { ID = 323, RouteID = 10, StopID = 131, Direction = Direction.Inbound, Order = 4},
				new RouteStop { ID = 324, RouteID = 10, StopID = 130, Direction = Direction.Inbound, Order = 5},
				new RouteStop { ID = 325, RouteID = 10, StopID = 129, Direction = Direction.Inbound, Order = 6},
				new RouteStop { ID = 326, RouteID = 10, StopID = 128, Direction = Direction.Inbound, Order = 7},
				new RouteStop { ID = 327, RouteID = 10, StopID = 127, Direction = Direction.Inbound, Order = 8},
				new RouteStop { ID = 328, RouteID = 10, StopID = 126, Direction = Direction.Inbound, Order = 9},
				new RouteStop { ID = 329, RouteID = 10, StopID = 125, Direction = Direction.Inbound, Order = 10},
				new RouteStop { ID = 330, RouteID = 10, StopID = 124, Direction = Direction.Inbound, Order = 11},
				new RouteStop { ID = 331, RouteID = 10, StopID = 123, Direction = Direction.Inbound, Order = 12},
				new RouteStop { ID = 332, RouteID = 10, StopID = 122, Direction = Direction.Inbound, Order = 13},
				new RouteStop { ID = 333, RouteID = 10, StopID = 121, Direction = Direction.Inbound, Order = 14},
				new RouteStop { ID = 334, RouteID = 10, StopID = 120, Direction = Direction.Inbound, Order = 15},
				new RouteStop { ID = 335, RouteID = 10, StopID = 119, Direction = Direction.Inbound, Order = 16},
				new RouteStop { ID = 336, RouteID = 10, StopID = 118, Direction = Direction.Inbound, Order = 17},
				new RouteStop { ID = 337, RouteID = 10, StopID = 117, Direction = Direction.Inbound, Order = 18},
				new RouteStop { ID = 338, RouteID = 10, StopID = 116, Direction = Direction.Inbound, Order = 19},
				new RouteStop { ID = 339, RouteID = 10, StopID = 115, Direction = Direction.Inbound, Order = 20},
				new RouteStop { ID = 340, RouteID = 10, StopID = 114, Direction = Direction.Inbound, Order = 21},
				new RouteStop { ID = 341, RouteID = 10, StopID = 113, Direction = Direction.Inbound, Order = 22},
				new RouteStop { ID = 342, RouteID = 11, StopID = 135, Direction = Direction.Outbound, Order = 1},
				new RouteStop { ID = 343, RouteID = 11, StopID = 136, Direction = Direction.Outbound, Order = 2},
				new RouteStop { ID = 344, RouteID = 11, StopID = 137, Direction = Direction.Outbound, Order = 3},
				new RouteStop { ID = 345, RouteID = 11, StopID = 138, Direction = Direction.Outbound, Order = 4},
				new RouteStop { ID = 346, RouteID = 11, StopID = 139, Direction = Direction.Outbound, Order = 5},
				new RouteStop { ID = 347, RouteID = 11, StopID = 140, Direction = Direction.Outbound, Order = 6},
				new RouteStop { ID = 348, RouteID = 11, StopID = 140, Direction = Direction.Inbound, Order = 1},
				new RouteStop { ID = 349, RouteID = 11, StopID = 139, Direction = Direction.Inbound, Order = 2},
				new RouteStop { ID = 350, RouteID = 11, StopID = 138, Direction = Direction.Inbound, Order = 3},
				new RouteStop { ID = 351, RouteID = 11, StopID = 137, Direction = Direction.Inbound, Order = 4},
				new RouteStop { ID = 352, RouteID = 11, StopID = 136, Direction = Direction.Inbound, Order = 5},
				new RouteStop { ID = 353, RouteID = 11, StopID = 135, Direction = Direction.Inbound, Order = 6},
				new RouteStop { ID = 354, RouteID = 12, StopID = 054, Direction = Direction.Outbound, Order = 1},
				new RouteStop { ID = 355, RouteID = 12, StopID = 141, Direction = Direction.Outbound, Order = 2},
				new RouteStop { ID = 356, RouteID = 12, StopID = 142, Direction = Direction.Outbound, Order = 3},
				new RouteStop { ID = 357, RouteID = 12, StopID = 143, Direction = Direction.Outbound, Order = 4},
				new RouteStop { ID = 358, RouteID = 12, StopID = 144, Direction = Direction.Outbound, Order = 5},
				new RouteStop { ID = 359, RouteID = 12, StopID = 145, Direction = Direction.Outbound, Order = 6},
				new RouteStop { ID = 360, RouteID = 12, StopID = 146, Direction = Direction.Outbound, Order = 7},
				new RouteStop { ID = 361, RouteID = 12, StopID = 147, Direction = Direction.Outbound, Order = 8},
				new RouteStop { ID = 362, RouteID = 12, StopID = 152, Direction = Direction.Outbound, Order = 9},
				new RouteStop { ID = 363, RouteID = 12, StopID = 153, Direction = Direction.Outbound, Order = 10},
				new RouteStop { ID = 364, RouteID = 12, StopID = 154, Direction = Direction.Outbound, Order = 11},
				new RouteStop { ID = 365, RouteID = 12, StopID = 155, Direction = Direction.Outbound, Order = 12},
				new RouteStop { ID = 366, RouteID = 12, StopID = 156, Direction = Direction.Outbound, Order = 13},
				new RouteStop { ID = 367, RouteID = 12, StopID = 157, Direction = Direction.Outbound, Order = 14},
				new RouteStop { ID = 368, RouteID = 12, StopID = 158, Direction = Direction.Outbound, Order = 15},
				new RouteStop { ID = 369, RouteID = 12, StopID = 159, Direction = Direction.Outbound, Order = 16},
				new RouteStop { ID = 370, RouteID = 12, StopID = 160, Direction = Direction.Outbound, Order = 17},
				new RouteStop { ID = 371, RouteID = 12, StopID = 161, Direction = Direction.Outbound, Order = 18},
				new RouteStop { ID = 372, RouteID = 12, StopID = 162, Direction = Direction.Outbound, Order = 19},
				new RouteStop { ID = 373, RouteID = 12, StopID = 163, Direction = Direction.Outbound, Order = 20},
				new RouteStop { ID = 374, RouteID = 12, StopID = 163, Direction = Direction.Inbound, Order = 1},
				new RouteStop { ID = 375, RouteID = 12, StopID = 162, Direction = Direction.Inbound, Order = 2},
				new RouteStop { ID = 376, RouteID = 12, StopID = 161, Direction = Direction.Inbound, Order = 3},
				new RouteStop { ID = 377, RouteID = 12, StopID = 160, Direction = Direction.Inbound, Order = 4},
				new RouteStop { ID = 378, RouteID = 12, StopID = 159, Direction = Direction.Inbound, Order = 5},
				new RouteStop { ID = 379, RouteID = 12, StopID = 158, Direction = Direction.Inbound, Order = 6},
				new RouteStop { ID = 380, RouteID = 12, StopID = 157, Direction = Direction.Inbound, Order = 7},
				new RouteStop { ID = 381, RouteID = 12, StopID = 156, Direction = Direction.Inbound, Order = 8},
				new RouteStop { ID = 382, RouteID = 12, StopID = 155, Direction = Direction.Inbound, Order = 9},
				new RouteStop { ID = 383, RouteID = 12, StopID = 154, Direction = Direction.Inbound, Order = 10},
				new RouteStop { ID = 384, RouteID = 12, StopID = 153, Direction = Direction.Inbound, Order = 11},
				new RouteStop { ID = 385, RouteID = 12, StopID = 152, Direction = Direction.Inbound, Order = 12},
				new RouteStop { ID = 386, RouteID = 12, StopID = 147, Direction = Direction.Inbound, Order = 13},
				new RouteStop { ID = 387, RouteID = 12, StopID = 146, Direction = Direction.Inbound, Order = 14},
				new RouteStop { ID = 388, RouteID = 12, StopID = 145, Direction = Direction.Inbound, Order = 15},
				new RouteStop { ID = 389, RouteID = 12, StopID = 144, Direction = Direction.Inbound, Order = 16},
				new RouteStop { ID = 390, RouteID = 12, StopID = 143, Direction = Direction.Inbound, Order = 17},
				new RouteStop { ID = 391, RouteID = 12, StopID = 142, Direction = Direction.Inbound, Order = 18},
				new RouteStop { ID = 392, RouteID = 12, StopID = 141, Direction = Direction.Inbound, Order = 19},
				new RouteStop { ID = 393, RouteID = 12, StopID = 054, Direction = Direction.Inbound, Order = 20},
				new RouteStop { ID = 394, RouteID = 13, StopID = 054, Direction = Direction.Outbound, Order = 1},
				new RouteStop { ID = 395, RouteID = 13, StopID = 141, Direction = Direction.Outbound, Order = 2},
				new RouteStop { ID = 396, RouteID = 13, StopID = 142, Direction = Direction.Outbound, Order = 3},
				new RouteStop { ID = 397, RouteID = 13, StopID = 143, Direction = Direction.Outbound, Order = 4},
				new RouteStop { ID = 398, RouteID = 13, StopID = 144, Direction = Direction.Outbound, Order = 5},
				new RouteStop { ID = 399, RouteID = 13, StopID = 145, Direction = Direction.Outbound, Order = 6},
				new RouteStop { ID = 400, RouteID = 13, StopID = 146, Direction = Direction.Outbound, Order = 7},
				new RouteStop { ID = 401, RouteID = 13, StopID = 147, Direction = Direction.Outbound, Order = 8},
				new RouteStop { ID = 402, RouteID = 13, StopID = 148, Direction = Direction.Outbound, Order = 9},
				new RouteStop { ID = 403, RouteID = 13, StopID = 149, Direction = Direction.Outbound, Order = 10},
				new RouteStop { ID = 404, RouteID = 13, StopID = 150, Direction = Direction.Outbound, Order = 11},
				new RouteStop { ID = 405, RouteID = 13, StopID = 151, Direction = Direction.Outbound, Order = 12},
				new RouteStop { ID = 406, RouteID = 13, StopID = 151, Direction = Direction.Inbound, Order = 1},
				new RouteStop { ID = 407, RouteID = 13, StopID = 150, Direction = Direction.Inbound, Order = 2},
				new RouteStop { ID = 408, RouteID = 13, StopID = 149, Direction = Direction.Inbound, Order = 3},
				new RouteStop { ID = 409, RouteID = 13, StopID = 148, Direction = Direction.Inbound, Order = 4},
				new RouteStop { ID = 410, RouteID = 13, StopID = 147, Direction = Direction.Inbound, Order = 5},
				new RouteStop { ID = 411, RouteID = 13, StopID = 146, Direction = Direction.Inbound, Order = 6},
				new RouteStop { ID = 412, RouteID = 13, StopID = 145, Direction = Direction.Inbound, Order = 7},
				new RouteStop { ID = 413, RouteID = 13, StopID = 144, Direction = Direction.Inbound, Order = 8},
				new RouteStop { ID = 414, RouteID = 13, StopID = 143, Direction = Direction.Inbound, Order = 9},
				new RouteStop { ID = 415, RouteID = 13, StopID = 142, Direction = Direction.Inbound, Order = 10},
				new RouteStop { ID = 416, RouteID = 13, StopID = 141, Direction = Direction.Inbound, Order = 11},
				new RouteStop { ID = 417, RouteID = 13, StopID = 054, Direction = Direction.Inbound, Order = 12},
				new RouteStop { ID = 418, RouteID = 14, StopID = 096, Direction = Direction.Outbound, Order = 1},
				new RouteStop { ID = 419, RouteID = 14, StopID = 164, Direction = Direction.Outbound, Order = 2},
				new RouteStop { ID = 420, RouteID = 14, StopID = 009, Direction = Direction.Outbound, Order = 3},
				new RouteStop { ID = 421, RouteID = 14, StopID = 165, Direction = Direction.Outbound, Order = 4},
				new RouteStop { ID = 422, RouteID = 14, StopID = 166, Direction = Direction.Outbound, Order = 5},
				new RouteStop { ID = 423, RouteID = 14, StopID = 167, Direction = Direction.Outbound, Order = 6},
				new RouteStop { ID = 424, RouteID = 14, StopID = 168, Direction = Direction.Outbound, Order = 7},
				new RouteStop { ID = 425, RouteID = 14, StopID = 169, Direction = Direction.Outbound, Order = 8},
				new RouteStop { ID = 426, RouteID = 14, StopID = 113, Direction = Direction.Outbound, Order = 9},
				new RouteStop { ID = 427, RouteID = 14, StopID = 170, Direction = Direction.Outbound, Order = 10},
				new RouteStop { ID = 428, RouteID = 14, StopID = 171, Direction = Direction.Outbound, Order = 11},
				new RouteStop { ID = 429, RouteID = 14, StopID = 172, Direction = Direction.Outbound, Order = 12},
				new RouteStop { ID = 430, RouteID = 14, StopID = 087, Direction = Direction.Outbound, Order = 13},
				new RouteStop { ID = 431, RouteID = 14, StopID = 173, Direction = Direction.Outbound, Order = 14},
				new RouteStop { ID = 432, RouteID = 14, StopID = 174, Direction = Direction.Outbound, Order = 15},
				new RouteStop { ID = 433, RouteID = 14, StopID = 175, Direction = Direction.Outbound, Order = 16},
				new RouteStop { ID = 434, RouteID = 14, StopID = 176, Direction = Direction.Outbound, Order = 17},
				new RouteStop { ID = 435, RouteID = 14, StopID = 072, Direction = Direction.Outbound, Order = 18},
				new RouteStop { ID = 436, RouteID = 14, StopID = 177, Direction = Direction.Outbound, Order = 19},
				new RouteStop { ID = 437, RouteID = 14, StopID = 028, Direction = Direction.Outbound, Order = 20},
				new RouteStop { ID = 438, RouteID = 14, StopID = 178, Direction = Direction.Outbound, Order = 21},
				new RouteStop { ID = 439, RouteID = 14, StopID = 057, Direction = Direction.Outbound, Order = 22},
				new RouteStop { ID = 440, RouteID = 14, StopID = 179, Direction = Direction.Outbound, Order = 23},
				new RouteStop { ID = 441, RouteID = 14, StopID = 180, Direction = Direction.Outbound, Order = 24},
				new RouteStop { ID = 442, RouteID = 14, StopID = 181, Direction = Direction.Outbound, Order = 25},
				new RouteStop { ID = 443, RouteID = 14, StopID = 182, Direction = Direction.Outbound, Order = 26},
				new RouteStop { ID = 444, RouteID = 14, StopID = 078, Direction = Direction.Outbound, Order = 27},
				new RouteStop { ID = 445, RouteID = 14, StopID = 183, Direction = Direction.Outbound, Order = 28},
				new RouteStop { ID = 446, RouteID = 14, StopID = 100, Direction = Direction.Outbound, Order = 29},
				new RouteStop { ID = 447, RouteID = 14, StopID = 184, Direction = Direction.Outbound, Order = 30},
				new RouteStop { ID = 448, RouteID = 14, StopID = 185, Direction = Direction.Outbound, Order = 31},
				new RouteStop { ID = 449, RouteID = 14, StopID = 186, Direction = Direction.Outbound, Order = 32},
				new RouteStop { ID = 450, RouteID = 14, StopID = 186, Direction = Direction.Inbound, Order = 1},
				new RouteStop { ID = 451, RouteID = 14, StopID = 185, Direction = Direction.Inbound, Order = 2},
				new RouteStop { ID = 452, RouteID = 14, StopID = 184, Direction = Direction.Inbound, Order = 3},
				new RouteStop { ID = 453, RouteID = 14, StopID = 100, Direction = Direction.Inbound, Order = 4},
				new RouteStop { ID = 454, RouteID = 14, StopID = 183, Direction = Direction.Inbound, Order = 5},
				new RouteStop { ID = 455, RouteID = 14, StopID = 078, Direction = Direction.Inbound, Order = 6},
				new RouteStop { ID = 456, RouteID = 14, StopID = 182, Direction = Direction.Inbound, Order = 7},
				new RouteStop { ID = 457, RouteID = 14, StopID = 181, Direction = Direction.Inbound, Order = 8},
				new RouteStop { ID = 458, RouteID = 14, StopID = 180, Direction = Direction.Inbound, Order = 9},
				new RouteStop { ID = 459, RouteID = 14, StopID = 179, Direction = Direction.Inbound, Order = 10},
				new RouteStop { ID = 460, RouteID = 14, StopID = 057, Direction = Direction.Inbound, Order = 11},
				new RouteStop { ID = 461, RouteID = 14, StopID = 178, Direction = Direction.Inbound, Order = 12},
				new RouteStop { ID = 462, RouteID = 14, StopID = 028, Direction = Direction.Inbound, Order = 13},
				new RouteStop { ID = 463, RouteID = 14, StopID = 177, Direction = Direction.Inbound, Order = 14},
				new RouteStop { ID = 464, RouteID = 14, StopID = 072, Direction = Direction.Inbound, Order = 15},
				new RouteStop { ID = 465, RouteID = 14, StopID = 176, Direction = Direction.Inbound, Order = 16},
				new RouteStop { ID = 466, RouteID = 14, StopID = 175, Direction = Direction.Inbound, Order = 17},
				new RouteStop { ID = 467, RouteID = 14, StopID = 174, Direction = Direction.Inbound, Order = 18},
				new RouteStop { ID = 468, RouteID = 14, StopID = 173, Direction = Direction.Inbound, Order = 19},
				new RouteStop { ID = 469, RouteID = 14, StopID = 087, Direction = Direction.Inbound, Order = 20},
				new RouteStop { ID = 470, RouteID = 14, StopID = 172, Direction = Direction.Inbound, Order = 21},
				new RouteStop { ID = 471, RouteID = 14, StopID = 171, Direction = Direction.Inbound, Order = 22},
				new RouteStop { ID = 472, RouteID = 14, StopID = 170, Direction = Direction.Inbound, Order = 23},
				new RouteStop { ID = 473, RouteID = 14, StopID = 113, Direction = Direction.Inbound, Order = 24},
				new RouteStop { ID = 474, RouteID = 14, StopID = 169, Direction = Direction.Inbound, Order = 25},
				new RouteStop { ID = 475, RouteID = 14, StopID = 168, Direction = Direction.Inbound, Order = 26},
				new RouteStop { ID = 476, RouteID = 14, StopID = 167, Direction = Direction.Inbound, Order = 27},
				new RouteStop { ID = 477, RouteID = 14, StopID = 166, Direction = Direction.Inbound, Order = 28},
				new RouteStop { ID = 478, RouteID = 14, StopID = 165, Direction = Direction.Inbound, Order = 29},
				new RouteStop { ID = 479, RouteID = 14, StopID = 009, Direction = Direction.Inbound, Order = 30},
				new RouteStop { ID = 480, RouteID = 14, StopID = 164, Direction = Direction.Inbound, Order = 31},
				new RouteStop { ID = 481, RouteID = 14, StopID = 096, Direction = Direction.Inbound, Order = 32},
				new RouteStop { ID = 482, RouteID = 15, StopID = 087, Direction = Direction.Outbound, Order = 1},
				new RouteStop { ID = 483, RouteID = 15, StopID = 173, Direction = Direction.Outbound, Order = 2},
				new RouteStop { ID = 484, RouteID = 15, StopID = 174, Direction = Direction.Outbound, Order = 3},
				new RouteStop { ID = 485, RouteID = 15, StopID = 175, Direction = Direction.Outbound, Order = 4},
				new RouteStop { ID = 486, RouteID = 15, StopID = 176, Direction = Direction.Outbound, Order = 5},
				new RouteStop { ID = 487, RouteID = 15, StopID = 072, Direction = Direction.Outbound, Order = 6},
				new RouteStop { ID = 488, RouteID = 15, StopID = 177, Direction = Direction.Outbound, Order = 7},
				new RouteStop { ID = 489, RouteID = 15, StopID = 028, Direction = Direction.Outbound, Order = 8},
				new RouteStop { ID = 490, RouteID = 15, StopID = 178, Direction = Direction.Outbound, Order = 9},
				new RouteStop { ID = 491, RouteID = 15, StopID = 057, Direction = Direction.Outbound, Order = 10},
				new RouteStop { ID = 492, RouteID = 15, StopID = 179, Direction = Direction.Outbound, Order = 11},
				new RouteStop { ID = 493, RouteID = 15, StopID = 180, Direction = Direction.Outbound, Order = 12},
				new RouteStop { ID = 494, RouteID = 15, StopID = 181, Direction = Direction.Outbound, Order = 13},
				new RouteStop { ID = 495, RouteID = 15, StopID = 182, Direction = Direction.Outbound, Order = 14},
				new RouteStop { ID = 496, RouteID = 15, StopID = 078, Direction = Direction.Outbound, Order = 15},
				new RouteStop { ID = 497, RouteID = 15, StopID = 183, Direction = Direction.Outbound, Order = 16},
				new RouteStop { ID = 498, RouteID = 15, StopID = 100, Direction = Direction.Outbound, Order = 17},
				new RouteStop { ID = 499, RouteID = 15, StopID = 184, Direction = Direction.Outbound, Order = 18},
				new RouteStop { ID = 500, RouteID = 15, StopID = 185, Direction = Direction.Outbound, Order = 19},
				new RouteStop { ID = 501, RouteID = 15, StopID = 186, Direction = Direction.Outbound, Order = 20},
				new RouteStop { ID = 502, RouteID = 15, StopID = 186, Direction = Direction.Inbound, Order = 1},
				new RouteStop { ID = 503, RouteID = 15, StopID = 185, Direction = Direction.Inbound, Order = 2},
				new RouteStop { ID = 504, RouteID = 15, StopID = 184, Direction = Direction.Inbound, Order = 3},
				new RouteStop { ID = 505, RouteID = 15, StopID = 100, Direction = Direction.Inbound, Order = 4},
				new RouteStop { ID = 506, RouteID = 15, StopID = 183, Direction = Direction.Inbound, Order = 5},
				new RouteStop { ID = 507, RouteID = 15, StopID = 078, Direction = Direction.Inbound, Order = 6},
				new RouteStop { ID = 508, RouteID = 15, StopID = 182, Direction = Direction.Inbound, Order = 7},
				new RouteStop { ID = 509, RouteID = 15, StopID = 181, Direction = Direction.Inbound, Order = 8},
				new RouteStop { ID = 510, RouteID = 15, StopID = 180, Direction = Direction.Inbound, Order = 9},
				new RouteStop { ID = 511, RouteID = 15, StopID = 179, Direction = Direction.Inbound, Order = 10},
				new RouteStop { ID = 512, RouteID = 15, StopID = 057, Direction = Direction.Inbound, Order = 11},
				new RouteStop { ID = 513, RouteID = 15, StopID = 178, Direction = Direction.Inbound, Order = 12},
				new RouteStop { ID = 514, RouteID = 15, StopID = 028, Direction = Direction.Inbound, Order = 13},
				new RouteStop { ID = 515, RouteID = 15, StopID = 177, Direction = Direction.Inbound, Order = 14},
				new RouteStop { ID = 516, RouteID = 15, StopID = 072, Direction = Direction.Inbound, Order = 15},
				new RouteStop { ID = 517, RouteID = 15, StopID = 176, Direction = Direction.Inbound, Order = 16},
				new RouteStop { ID = 518, RouteID = 15, StopID = 175, Direction = Direction.Inbound, Order = 17},
				new RouteStop { ID = 519, RouteID = 15, StopID = 174, Direction = Direction.Inbound, Order = 18},
				new RouteStop { ID = 520, RouteID = 15, StopID = 173, Direction = Direction.Inbound, Order = 19},
				new RouteStop { ID = 521, RouteID = 15, StopID = 087, Direction = Direction.Inbound, Order = 20},
				new RouteStop { ID = 522, RouteID = 16, StopID = 187, Direction = Direction.Outbound, Order = 1},
				new RouteStop { ID = 523, RouteID = 16, StopID = 188, Direction = Direction.Outbound, Order = 2},
				new RouteStop { ID = 524, RouteID = 16, StopID = 071, Direction = Direction.Outbound, Order = 3},
				new RouteStop { ID = 525, RouteID = 16, StopID = 189, Direction = Direction.Outbound, Order = 4},
				new RouteStop { ID = 526, RouteID = 16, StopID = 190, Direction = Direction.Outbound, Order = 5},
				new RouteStop { ID = 527, RouteID = 16, StopID = 191, Direction = Direction.Outbound, Order = 6},
				new RouteStop { ID = 528, RouteID = 16, StopID = 018, Direction = Direction.Outbound, Order = 7},
				new RouteStop { ID = 529, RouteID = 16, StopID = 094, Direction = Direction.Outbound, Order = 8},
				new RouteStop { ID = 530, RouteID = 16, StopID = 192, Direction = Direction.Outbound, Order = 9},
				new RouteStop { ID = 531, RouteID = 16, StopID = 135, Direction = Direction.Outbound, Order = 10},
				new RouteStop { ID = 532, RouteID = 16, StopID = 193, Direction = Direction.Outbound, Order = 11},
				new RouteStop { ID = 533, RouteID = 16, StopID = 136, Direction = Direction.Outbound, Order = 12},
				new RouteStop { ID = 534, RouteID = 16, StopID = 113, Direction = Direction.Outbound, Order = 13},
				new RouteStop { ID = 535, RouteID = 16, StopID = 113, Direction = Direction.Inbound, Order = 1},
				new RouteStop { ID = 536, RouteID = 16, StopID = 136, Direction = Direction.Inbound, Order = 2},
				new RouteStop { ID = 537, RouteID = 16, StopID = 193, Direction = Direction.Inbound, Order = 3},
				new RouteStop { ID = 538, RouteID = 16, StopID = 135, Direction = Direction.Inbound, Order = 4},
				new RouteStop { ID = 539, RouteID = 16, StopID = 192, Direction = Direction.Inbound, Order = 5},
				new RouteStop { ID = 540, RouteID = 16, StopID = 094, Direction = Direction.Inbound, Order = 6},
				new RouteStop { ID = 541, RouteID = 16, StopID = 018, Direction = Direction.Inbound, Order = 7},
				new RouteStop { ID = 542, RouteID = 16, StopID = 191, Direction = Direction.Inbound, Order = 8},
				new RouteStop { ID = 543, RouteID = 16, StopID = 190, Direction = Direction.Inbound, Order = 9},
				new RouteStop { ID = 544, RouteID = 16, StopID = 189, Direction = Direction.Inbound, Order = 10},
				new RouteStop { ID = 545, RouteID = 16, StopID = 071, Direction = Direction.Inbound, Order = 11},
				new RouteStop { ID = 546, RouteID = 16, StopID = 188, Direction = Direction.Inbound, Order = 12},
				new RouteStop { ID = 547, RouteID = 16, StopID = 187, Direction = Direction.Inbound, Order = 13},
				new RouteStop { ID = 548, RouteID = 17, StopID = 040, Direction = Direction.Outbound, Order = 1},
				new RouteStop { ID = 549, RouteID = 17, StopID = 057, Direction = Direction.Outbound, Order = 2},
				new RouteStop { ID = 550, RouteID = 17, StopID = 056, Direction = Direction.Outbound, Order = 3},
				new RouteStop { ID = 551, RouteID = 17, StopID = 194, Direction = Direction.Outbound, Order = 4},
				new RouteStop { ID = 552, RouteID = 17, StopID = 194, Direction = Direction.Outbound, Order = 5},
				new RouteStop { ID = 553, RouteID = 17, StopID = 195, Direction = Direction.Outbound, Order = 6},
				new RouteStop { ID = 554, RouteID = 17, StopID = 030, Direction = Direction.Outbound, Order = 7},
				new RouteStop { ID = 555, RouteID = 17, StopID = 044, Direction = Direction.Outbound, Order = 8},
				new RouteStop { ID = 556, RouteID = 17, StopID = 196, Direction = Direction.Outbound, Order = 9},
				new RouteStop { ID = 557, RouteID = 17, StopID = 197, Direction = Direction.Outbound, Order = 10},
				new RouteStop { ID = 558, RouteID = 17, StopID = 198, Direction = Direction.Outbound, Order = 11},
				new RouteStop { ID = 559, RouteID = 17, StopID = 199, Direction = Direction.Outbound, Order = 12},
				new RouteStop { ID = 560, RouteID = 17, StopID = 054, Direction = Direction.Outbound, Order = 13},
				new RouteStop { ID = 561, RouteID = 17, StopID = 054, Direction = Direction.Outbound, Order = 14},
				new RouteStop { ID = 562, RouteID = 17, StopID = 200, Direction = Direction.Outbound, Order = 15},
				new RouteStop { ID = 563, RouteID = 17, StopID = 201, Direction = Direction.Outbound, Order = 16},
				new RouteStop { ID = 564, RouteID = 17, StopID = 202, Direction = Direction.Outbound, Order = 17},
				new RouteStop { ID = 565, RouteID = 17, StopID = 203, Direction = Direction.Outbound, Order = 18},
				new RouteStop { ID = 566, RouteID = 17, StopID = 204, Direction = Direction.Outbound, Order = 19},
				new RouteStop { ID = 567, RouteID = 17, StopID = 205, Direction = Direction.Outbound, Order = 20},
				new RouteStop { ID = 568, RouteID = 17, StopID = 206, Direction = Direction.Outbound, Order = 21},
				new RouteStop { ID = 569, RouteID = 17, StopID = 207, Direction = Direction.Outbound, Order = 22},
				new RouteStop { ID = 570, RouteID = 17, StopID = 208, Direction = Direction.Outbound, Order = 23},
				new RouteStop { ID = 571, RouteID = 17, StopID = 088, Direction = Direction.Outbound, Order = 24},
				new RouteStop { ID = 572, RouteID = 17, StopID = 209, Direction = Direction.Outbound, Order = 25},
				new RouteStop { ID = 573, RouteID = 17, StopID = 210, Direction = Direction.Outbound, Order = 26},
				new RouteStop { ID = 574, RouteID = 17, StopID = 211, Direction = Direction.Outbound, Order = 27},
				new RouteStop { ID = 575, RouteID = 17, StopID = 212, Direction = Direction.Outbound, Order = 28},
				new RouteStop { ID = 576, RouteID = 17, StopID = 213, Direction = Direction.Outbound, Order = 29},
				new RouteStop { ID = 577, RouteID = 17, StopID = 214, Direction = Direction.Outbound, Order = 30},
				new RouteStop { ID = 578, RouteID = 17, StopID = 215, Direction = Direction.Outbound, Order = 31},
				new RouteStop { ID = 579, RouteID = 17, StopID = 216, Direction = Direction.Outbound, Order = 32},
				new RouteStop { ID = 580, RouteID = 17, StopID = 216, Direction = Direction.Inbound, Order = 1},
				new RouteStop { ID = 581, RouteID = 17, StopID = 215, Direction = Direction.Inbound, Order = 2},
				new RouteStop { ID = 582, RouteID = 17, StopID = 214, Direction = Direction.Inbound, Order = 3},
				new RouteStop { ID = 583, RouteID = 17, StopID = 213, Direction = Direction.Inbound, Order = 4},
				new RouteStop { ID = 584, RouteID = 17, StopID = 212, Direction = Direction.Inbound, Order = 5},
				new RouteStop { ID = 585, RouteID = 17, StopID = 211, Direction = Direction.Inbound, Order = 6},
				new RouteStop { ID = 586, RouteID = 17, StopID = 210, Direction = Direction.Inbound, Order = 7},
				new RouteStop { ID = 587, RouteID = 17, StopID = 209, Direction = Direction.Inbound, Order = 8},
				new RouteStop { ID = 588, RouteID = 17, StopID = 088, Direction = Direction.Inbound, Order = 9},
				new RouteStop { ID = 589, RouteID = 17, StopID = 208, Direction = Direction.Inbound, Order = 10},
				new RouteStop { ID = 590, RouteID = 17, StopID = 207, Direction = Direction.Inbound, Order = 11},
				new RouteStop { ID = 591, RouteID = 17, StopID = 206, Direction = Direction.Inbound, Order = 12},
				new RouteStop { ID = 592, RouteID = 17, StopID = 217, Direction = Direction.Inbound, Order = 13},
				new RouteStop { ID = 593, RouteID = 17, StopID = 205, Direction = Direction.Inbound, Order = 14},
				new RouteStop { ID = 594, RouteID = 17, StopID = 204, Direction = Direction.Inbound, Order = 15},
				new RouteStop { ID = 595, RouteID = 17, StopID = 203, Direction = Direction.Inbound, Order = 16},
				new RouteStop { ID = 596, RouteID = 17, StopID = 202, Direction = Direction.Inbound, Order = 17},
				new RouteStop { ID = 597, RouteID = 17, StopID = 201, Direction = Direction.Inbound, Order = 18},
				new RouteStop { ID = 598, RouteID = 17, StopID = 200, Direction = Direction.Inbound, Order = 19},
				new RouteStop { ID = 599, RouteID = 17, StopID = 054, Direction = Direction.Inbound, Order = 20},
				new RouteStop { ID = 600, RouteID = 17, StopID = 054, Direction = Direction.Inbound, Order = 21},
				new RouteStop { ID = 601, RouteID = 17, StopID = 199, Direction = Direction.Inbound, Order = 22},
				new RouteStop { ID = 602, RouteID = 17, StopID = 198, Direction = Direction.Inbound, Order = 23},
				new RouteStop { ID = 603, RouteID = 17, StopID = 197, Direction = Direction.Inbound, Order = 24},
				new RouteStop { ID = 604, RouteID = 17, StopID = 196, Direction = Direction.Inbound, Order = 25},
				new RouteStop { ID = 605, RouteID = 17, StopID = 044, Direction = Direction.Inbound, Order = 26},
				new RouteStop { ID = 606, RouteID = 17, StopID = 030, Direction = Direction.Inbound, Order = 27},
				new RouteStop { ID = 607, RouteID = 17, StopID = 195, Direction = Direction.Inbound, Order = 28},
				new RouteStop { ID = 608, RouteID = 17, StopID = 194, Direction = Direction.Inbound, Order = 29},
				new RouteStop { ID = 609, RouteID = 17, StopID = 056, Direction = Direction.Inbound, Order = 30},
				new RouteStop { ID = 610, RouteID = 17, StopID = 057, Direction = Direction.Inbound, Order = 31},
				new RouteStop { ID = 611, RouteID = 17, StopID = 040, Direction = Direction.Inbound, Order = 32},
				new RouteStop { ID = 612, RouteID = 18, StopID = 069, Direction = Direction.Outbound, Order = 1},
				new RouteStop { ID = 613, RouteID = 19, StopID = 069, Direction = Direction.Outbound, Order = 1},
				new RouteStop { ID = 614, RouteID = 18, StopID = 218, Direction = Direction.Outbound, Order = 2},
				new RouteStop { ID = 615, RouteID = 19, StopID = 218, Direction = Direction.Outbound, Order = 2},
				new RouteStop { ID = 616, RouteID = 18, StopID = 219, Direction = Direction.Outbound, Order = 3},
				new RouteStop { ID = 617, RouteID = 19, StopID = 219, Direction = Direction.Outbound, Order = 3},
				new RouteStop { ID = 618, RouteID = 18, StopID = 097, Direction = Direction.Outbound, Order = 4},
				new RouteStop { ID = 619, RouteID = 19, StopID = 097, Direction = Direction.Outbound, Order = 4},
				new RouteStop { ID = 620, RouteID = 18, StopID = 220, Direction = Direction.Outbound, Order = 5},
				new RouteStop { ID = 621, RouteID = 19, StopID = 220, Direction = Direction.Outbound, Order = 5},
				new RouteStop { ID = 622, RouteID = 18, StopID = 187, Direction = Direction.Outbound, Order = 6},
				new RouteStop { ID = 623, RouteID = 19, StopID = 187, Direction = Direction.Outbound, Order = 6},
				new RouteStop { ID = 624, RouteID = 18, StopID = 081, Direction = Direction.Outbound, Order = 7},
				new RouteStop { ID = 625, RouteID = 19, StopID = 081, Direction = Direction.Outbound, Order = 7},
				new RouteStop { ID = 626, RouteID = 18, StopID = 062, Direction = Direction.Outbound, Order = 8},
				new RouteStop { ID = 627, RouteID = 19, StopID = 062, Direction = Direction.Outbound, Order = 8},
				new RouteStop { ID = 628, RouteID = 18, StopID = 221, Direction = Direction.Outbound, Order = 9},
				new RouteStop { ID = 629, RouteID = 19, StopID = 221, Direction = Direction.Outbound, Order = 9},
				new RouteStop { ID = 630, RouteID = 18, StopID = 222, Direction = Direction.Outbound, Order = 10},
				new RouteStop { ID = 631, RouteID = 19, StopID = 222, Direction = Direction.Outbound, Order = 10},
				new RouteStop { ID = 632, RouteID = 18, StopID = 022, Direction = Direction.Outbound, Order = 11},
				new RouteStop { ID = 633, RouteID = 19, StopID = 022, Direction = Direction.Outbound, Order = 11},
				new RouteStop { ID = 634, RouteID = 18, StopID = 093, Direction = Direction.Outbound, Order = 12},
				new RouteStop { ID = 635, RouteID = 19, StopID = 093, Direction = Direction.Outbound, Order = 12},
				new RouteStop { ID = 636, RouteID = 18, StopID = 223, Direction = Direction.Outbound, Order = 13},
				new RouteStop { ID = 637, RouteID = 19, StopID = 223, Direction = Direction.Outbound, Order = 13},
				new RouteStop { ID = 638, RouteID = 18, StopID = 084, Direction = Direction.Outbound, Order = 14},
				new RouteStop { ID = 639, RouteID = 19, StopID = 084, Direction = Direction.Outbound, Order = 14},
				new RouteStop { ID = 640, RouteID = 18, StopID = 224, Direction = Direction.Outbound, Order = 15},
				new RouteStop { ID = 641, RouteID = 19, StopID = 224, Direction = Direction.Outbound, Order = 15},
				new RouteStop { ID = 642, RouteID = 18, StopID = 135, Direction = Direction.Outbound, Order = 16},
				new RouteStop { ID = 643, RouteID = 19, StopID = 135, Direction = Direction.Outbound, Order = 16},
				new RouteStop { ID = 644, RouteID = 18, StopID = 225, Direction = Direction.Outbound, Order = 17},
				new RouteStop { ID = 645, RouteID = 19, StopID = 225, Direction = Direction.Outbound, Order = 17},
				new RouteStop { ID = 646, RouteID = 18, StopID = 226, Direction = Direction.Outbound, Order = 18},
				new RouteStop { ID = 647, RouteID = 18, StopID = 095, Direction = Direction.Outbound, Order = 19},
				new RouteStop { ID = 648, RouteID = 19, StopID = 227, Direction = Direction.Outbound, Order = 18},
				new RouteStop { ID = 649, RouteID = 19, StopID = 014, Direction = Direction.Outbound, Order = 19},
				new RouteStop { ID = 650, RouteID = 18, StopID = 095, Direction = Direction.Inbound, Order = 1},
				new RouteStop { ID = 651, RouteID = 18, StopID = 226, Direction = Direction.Inbound, Order = 2},
				new RouteStop { ID = 652, RouteID = 19, StopID = 014, Direction = Direction.Inbound, Order = 1},
				new RouteStop { ID = 653, RouteID = 19, StopID = 227, Direction = Direction.Inbound, Order = 2},
				new RouteStop { ID = 654, RouteID = 18, StopID = 225, Direction = Direction.Inbound, Order = 3},
				new RouteStop { ID = 655, RouteID = 19, StopID = 225, Direction = Direction.Inbound, Order = 3},
				new RouteStop { ID = 656, RouteID = 18, StopID = 135, Direction = Direction.Inbound, Order = 4},
				new RouteStop { ID = 657, RouteID = 19, StopID = 135, Direction = Direction.Inbound, Order = 4},
				new RouteStop { ID = 658, RouteID = 18, StopID = 224, Direction = Direction.Inbound, Order = 5},
				new RouteStop { ID = 659, RouteID = 19, StopID = 224, Direction = Direction.Inbound, Order = 5},
				new RouteStop { ID = 660, RouteID = 18, StopID = 084, Direction = Direction.Inbound, Order = 6},
				new RouteStop { ID = 661, RouteID = 19, StopID = 084, Direction = Direction.Inbound, Order = 6},
				new RouteStop { ID = 662, RouteID = 18, StopID = 223, Direction = Direction.Inbound, Order = 7},
				new RouteStop { ID = 663, RouteID = 19, StopID = 223, Direction = Direction.Inbound, Order = 7},
				new RouteStop { ID = 664, RouteID = 18, StopID = 093, Direction = Direction.Inbound, Order = 8},
				new RouteStop { ID = 665, RouteID = 19, StopID = 093, Direction = Direction.Inbound, Order = 8},
				new RouteStop { ID = 666, RouteID = 18, StopID = 022, Direction = Direction.Inbound, Order = 9},
				new RouteStop { ID = 667, RouteID = 19, StopID = 022, Direction = Direction.Inbound, Order = 9},
				new RouteStop { ID = 668, RouteID = 18, StopID = 222, Direction = Direction.Inbound, Order = 10},
				new RouteStop { ID = 669, RouteID = 19, StopID = 222, Direction = Direction.Inbound, Order = 10},
				new RouteStop { ID = 670, RouteID = 18, StopID = 221, Direction = Direction.Inbound, Order = 11},
				new RouteStop { ID = 671, RouteID = 19, StopID = 221, Direction = Direction.Inbound, Order = 11},
				new RouteStop { ID = 672, RouteID = 18, StopID = 062, Direction = Direction.Inbound, Order = 12},
				new RouteStop { ID = 673, RouteID = 19, StopID = 062, Direction = Direction.Inbound, Order = 12},
				new RouteStop { ID = 674, RouteID = 18, StopID = 081, Direction = Direction.Inbound, Order = 13},
				new RouteStop { ID = 675, RouteID = 19, StopID = 081, Direction = Direction.Inbound, Order = 13},
				new RouteStop { ID = 676, RouteID = 18, StopID = 187, Direction = Direction.Inbound, Order = 14},
				new RouteStop { ID = 677, RouteID = 19, StopID = 187, Direction = Direction.Inbound, Order = 14},
				new RouteStop { ID = 678, RouteID = 18, StopID = 220, Direction = Direction.Inbound, Order = 15},
				new RouteStop { ID = 679, RouteID = 19, StopID = 220, Direction = Direction.Inbound, Order = 15},
				new RouteStop { ID = 680, RouteID = 18, StopID = 097, Direction = Direction.Inbound, Order = 16},
				new RouteStop { ID = 681, RouteID = 19, StopID = 097, Direction = Direction.Inbound, Order = 16},
				new RouteStop { ID = 682, RouteID = 18, StopID = 219, Direction = Direction.Inbound, Order = 17},
				new RouteStop { ID = 683, RouteID = 19, StopID = 219, Direction = Direction.Inbound, Order = 17},
				new RouteStop { ID = 684, RouteID = 18, StopID = 218, Direction = Direction.Inbound, Order = 18},
				new RouteStop { ID = 685, RouteID = 19, StopID = 218, Direction = Direction.Inbound, Order = 18},
				new RouteStop { ID = 686, RouteID = 18, StopID = 069, Direction = Direction.Inbound, Order = 19},
				new RouteStop { ID = 687, RouteID = 19, StopID = 069, Direction = Direction.Inbound, Order = 19},
				new RouteStop { ID = 688, RouteID = 20, StopID = 228, Direction = Direction.Outbound, Order = 1},
				new RouteStop { ID = 689, RouteID = 20, StopID = 229, Direction = Direction.Outbound, Order = 2},
				new RouteStop { ID = 690, RouteID = 20, StopID = 230, Direction = Direction.Outbound, Order = 3},
				new RouteStop { ID = 691, RouteID = 20, StopID = 231, Direction = Direction.Outbound, Order = 4},
				new RouteStop { ID = 692, RouteID = 20, StopID = 232, Direction = Direction.Outbound, Order = 5},
				new RouteStop { ID = 693, RouteID = 20, StopID = 233, Direction = Direction.Outbound, Order = 6},
				new RouteStop { ID = 694, RouteID = 20, StopID = 234, Direction = Direction.Outbound, Order = 7},
				new RouteStop { ID = 695, RouteID = 20, StopID = 235, Direction = Direction.Outbound, Order = 8},
				new RouteStop { ID = 696, RouteID = 20, StopID = 069, Direction = Direction.Outbound, Order = 9},
				new RouteStop { ID = 697, RouteID = 20, StopID = 236, Direction = Direction.Outbound, Order = 10},
				new RouteStop { ID = 698, RouteID = 20, StopID = 237, Direction = Direction.Outbound, Order = 11},
				new RouteStop { ID = 699, RouteID = 20, StopID = 238, Direction = Direction.Outbound, Order = 12},
				new RouteStop { ID = 700, RouteID = 20, StopID = 239, Direction = Direction.Outbound, Order = 13},
				new RouteStop { ID = 701, RouteID = 20, StopID = 240, Direction = Direction.Outbound, Order = 14},
				new RouteStop { ID = 702, RouteID = 20, StopID = 241, Direction = Direction.Outbound, Order = 15},
				new RouteStop { ID = 703, RouteID = 20, StopID = 018, Direction = Direction.Outbound, Order = 16},
				new RouteStop { ID = 704, RouteID = 20, StopID = 019, Direction = Direction.Outbound, Order = 17},
				new RouteStop { ID = 705, RouteID = 20, StopID = 020, Direction = Direction.Outbound, Order = 18},
				new RouteStop { ID = 706, RouteID = 20, StopID = 021, Direction = Direction.Outbound, Order = 19},
				new RouteStop { ID = 707, RouteID = 20, StopID = 022, Direction = Direction.Outbound, Order = 20},
				new RouteStop { ID = 708, RouteID = 20, StopID = 023, Direction = Direction.Outbound, Order = 21},
				new RouteStop { ID = 709, RouteID = 20, StopID = 024, Direction = Direction.Outbound, Order = 22},
				new RouteStop { ID = 710, RouteID = 20, StopID = 025, Direction = Direction.Outbound, Order = 23},
				new RouteStop { ID = 711, RouteID = 20, StopID = 026, Direction = Direction.Outbound, Order = 24},
				new RouteStop { ID = 712, RouteID = 20, StopID = 027, Direction = Direction.Outbound, Order = 25},
				new RouteStop { ID = 713, RouteID = 20, StopID = 028, Direction = Direction.Outbound, Order = 26},
				new RouteStop { ID = 714, RouteID = 20, StopID = 242, Direction = Direction.Outbound, Order = 27},
				new RouteStop { ID = 715, RouteID = 20, StopID = 057, Direction = Direction.Outbound, Order = 28},
				new RouteStop { ID = 716, RouteID = 20, StopID = 056, Direction = Direction.Outbound, Order = 29},
				new RouteStop { ID = 717, RouteID = 20, StopID = 194, Direction = Direction.Outbound, Order = 30},
				new RouteStop { ID = 718, RouteID = 20, StopID = 243, Direction = Direction.Outbound, Order = 31},
				new RouteStop { ID = 719, RouteID = 20, StopID = 244, Direction = Direction.Outbound, Order = 32},
				new RouteStop { ID = 720, RouteID = 20, StopID = 245, Direction = Direction.Outbound, Order = 33},
				new RouteStop { ID = 721, RouteID = 20, StopID = 246, Direction = Direction.Outbound, Order = 34},
				new RouteStop { ID = 722, RouteID = 20, StopID = 247, Direction = Direction.Outbound, Order = 35},
				new RouteStop { ID = 723, RouteID = 20, StopID = 248, Direction = Direction.Outbound, Order = 36},
				new RouteStop { ID = 724, RouteID = 20, StopID = 249, Direction = Direction.Outbound, Order = 37},
				new RouteStop { ID = 725, RouteID = 20, StopID = 250, Direction = Direction.Outbound, Order = 38},
				new RouteStop { ID = 726, RouteID = 20, StopID = 251, Direction = Direction.Outbound, Order = 39},
				new RouteStop { ID = 727, RouteID = 20, StopID = 252, Direction = Direction.Outbound, Order = 40},
				new RouteStop { ID = 728, RouteID = 20, StopID = 253, Direction = Direction.Outbound, Order = 41},
				new RouteStop { ID = 729, RouteID = 20, StopID = 254, Direction = Direction.Outbound, Order = 42},
				new RouteStop { ID = 730, RouteID = 20, StopID = 255, Direction = Direction.Outbound, Order = 43},
				new RouteStop { ID = 731, RouteID = 20, StopID = 256, Direction = Direction.Outbound, Order = 44},
				new RouteStop { ID = 732, RouteID = 20, StopID = 257, Direction = Direction.Outbound, Order = 45},
				new RouteStop { ID = 733, RouteID = 20, StopID = 258, Direction = Direction.Outbound, Order = 46},
				new RouteStop { ID = 734, RouteID = 20, StopID = 259, Direction = Direction.Outbound, Order = 47},
				new RouteStop { ID = 735, RouteID = 20, StopID = 259, Direction = Direction.Inbound, Order = 1},
				new RouteStop { ID = 736, RouteID = 20, StopID = 258, Direction = Direction.Inbound, Order = 2},
				new RouteStop { ID = 737, RouteID = 20, StopID = 257, Direction = Direction.Inbound, Order = 3},
				new RouteStop { ID = 738, RouteID = 20, StopID = 256, Direction = Direction.Inbound, Order = 4},
				new RouteStop { ID = 739, RouteID = 20, StopID = 255, Direction = Direction.Inbound, Order = 5},
				new RouteStop { ID = 740, RouteID = 20, StopID = 254, Direction = Direction.Inbound, Order = 6},
				new RouteStop { ID = 741, RouteID = 20, StopID = 252, Direction = Direction.Inbound, Order = 7},
				new RouteStop { ID = 742, RouteID = 20, StopID = 251, Direction = Direction.Inbound, Order = 8},
				new RouteStop { ID = 743, RouteID = 20, StopID = 250, Direction = Direction.Inbound, Order = 9},
				new RouteStop { ID = 744, RouteID = 20, StopID = 249, Direction = Direction.Inbound, Order = 10},
				new RouteStop { ID = 745, RouteID = 20, StopID = 248, Direction = Direction.Inbound, Order = 11},
				new RouteStop { ID = 746, RouteID = 20, StopID = 247, Direction = Direction.Inbound, Order = 12},
				new RouteStop { ID = 747, RouteID = 20, StopID = 246, Direction = Direction.Inbound, Order = 13},
				new RouteStop { ID = 748, RouteID = 20, StopID = 245, Direction = Direction.Inbound, Order = 14},
				new RouteStop { ID = 749, RouteID = 20, StopID = 244, Direction = Direction.Inbound, Order = 15},
				new RouteStop { ID = 750, RouteID = 20, StopID = 243, Direction = Direction.Inbound, Order = 16},
				new RouteStop { ID = 751, RouteID = 20, StopID = 194, Direction = Direction.Inbound, Order = 17},
				new RouteStop { ID = 752, RouteID = 20, StopID = 056, Direction = Direction.Inbound, Order = 18},
				new RouteStop { ID = 753, RouteID = 20, StopID = 057, Direction = Direction.Inbound, Order = 19},
				new RouteStop { ID = 754, RouteID = 20, StopID = 242, Direction = Direction.Inbound, Order = 20},
				new RouteStop { ID = 755, RouteID = 20, StopID = 028, Direction = Direction.Inbound, Order = 21},
				new RouteStop { ID = 756, RouteID = 20, StopID = 027, Direction = Direction.Inbound, Order = 22},
				new RouteStop { ID = 757, RouteID = 20, StopID = 026, Direction = Direction.Inbound, Order = 23},
				new RouteStop { ID = 758, RouteID = 20, StopID = 025, Direction = Direction.Inbound, Order = 24},
				new RouteStop { ID = 759, RouteID = 20, StopID = 024, Direction = Direction.Inbound, Order = 25},
				new RouteStop { ID = 760, RouteID = 20, StopID = 023, Direction = Direction.Inbound, Order = 26},
				new RouteStop { ID = 761, RouteID = 20, StopID = 022, Direction = Direction.Inbound, Order = 27},
				new RouteStop { ID = 762, RouteID = 20, StopID = 021, Direction = Direction.Inbound, Order = 28},
				new RouteStop { ID = 763, RouteID = 20, StopID = 020, Direction = Direction.Inbound, Order = 29},
				new RouteStop { ID = 764, RouteID = 20, StopID = 019, Direction = Direction.Inbound, Order = 30},
				new RouteStop { ID = 765, RouteID = 20, StopID = 018, Direction = Direction.Inbound, Order = 31},
				new RouteStop { ID = 766, RouteID = 20, StopID = 260, Direction = Direction.Inbound, Order = 32},
				new RouteStop { ID = 767, RouteID = 20, StopID = 240, Direction = Direction.Inbound, Order = 33},
				new RouteStop { ID = 768, RouteID = 20, StopID = 239, Direction = Direction.Inbound, Order = 34},
				new RouteStop { ID = 769, RouteID = 20, StopID = 237, Direction = Direction.Inbound, Order = 35},
				new RouteStop { ID = 770, RouteID = 20, StopID = 236, Direction = Direction.Inbound, Order = 36},
				new RouteStop { ID = 771, RouteID = 20, StopID = 069, Direction = Direction.Inbound, Order = 37},
				new RouteStop { ID = 772, RouteID = 20, StopID = 235, Direction = Direction.Inbound, Order = 38},
				new RouteStop { ID = 773, RouteID = 20, StopID = 234, Direction = Direction.Inbound, Order = 39},
				new RouteStop { ID = 774, RouteID = 20, StopID = 233, Direction = Direction.Inbound, Order = 40},
				new RouteStop { ID = 775, RouteID = 20, StopID = 232, Direction = Direction.Inbound, Order = 41},
				new RouteStop { ID = 776, RouteID = 20, StopID = 231, Direction = Direction.Inbound, Order = 42},
				new RouteStop { ID = 777, RouteID = 20, StopID = 230, Direction = Direction.Inbound, Order = 43},
				new RouteStop { ID = 778, RouteID = 20, StopID = 229, Direction = Direction.Inbound, Order = 44},
				new RouteStop { ID = 779, RouteID = 20, StopID = 228, Direction = Direction.Inbound, Order = 45}
				);
			#endregion
		}
	}
}