using DAL.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DAL
{
	public class TransportationContext : DbContext
	{
		public DbSet<Route> Routes { get; set; }
		public DbSet<Stop> Stops { get; set; }
		public DbSet<BoundedWalk> BoundedWalks { get; set; }
		public DbSet<Walk> Walks { get; set; }
		public DbSet<Itinerary> Itineraries { get; set; }
		public DbSet<Recording> Recordings { get; set; }
		public DbSet<RouteJourney> RouteJourneys { get; set; }
		public DbSet<RouteStop> RouteStops { get; set; }


		public TransportationContext() : base() { }

		public TransportationContext(DbContextOptions<TransportationContext> options) : base(options) { }

		protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
		{
			optionsBuilder.UseSqlServer(@"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=master;Integrated Security=True;Connect Timeout=30;Encrypt=False;Trust Server Certificate=False;Application Intent=ReadWrite;Multi Subnet Failover=False");
		}

		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			base.OnModelCreating(modelBuilder);

			modelBuilder.Entity<Route>()
				.HasMany(r => r.Stops)
				.WithMany(s => s.Routes)
				.UsingEntity<RouteStop>();

			var recordingTypeConverter = new EnumToStringConverter<RecordingType>();
			modelBuilder.Entity<Recording>()
				.Property(r => r.RecordingType)
				.HasConversion(recordingTypeConverter);

			var directionTypeConverter = new EnumToStringConverter<Direction>();
			modelBuilder.Entity<RouteStop>()
				.Property(rs => rs.Direction)
				.HasConversion(directionTypeConverter);

			#region Seeding
			modelBuilder.Entity<Route>().HasData(
				new Route { ID = 01, Provider = "BKK", RouteNumber = "7" },
				new Route { ID = 02, Provider = "BKK", RouteNumber = "7E" },
				new Route { ID = 03, Provider = "BKK", RouteNumber = "82" },
				new Route { ID = 04, Provider = "BKK", RouteNumber = "82A" },
				new Route { ID = 05, Provider = "BKK", RouteNumber = "M1" },
				new Route { ID = 06, Provider = "BKK", RouteNumber = "M2" },
				new Route { ID = 07, Provider = "BKK", RouteNumber = "M3" },
				new Route { ID = 08, Provider = "BKK", RouteNumber = "M4" },
				new Route { ID = 09, Provider = "BKK", RouteNumber = "H5" },
				new Route { ID = 10, Provider = "BKK", RouteNumber = "H6" },
				new Route { ID = 11, Provider = "BKK", RouteNumber = "H7" },
				new Route { ID = 12, Provider = "BKK", RouteNumber = "H8" },
				new Route { ID = 13, Provider = "BKK", RouteNumber = "H9" },
				new Route { ID = 14, Provider = "BKK", RouteNumber = "1" },
				new Route { ID = 15, Provider = "BKK", RouteNumber = "1A" },
				new Route { ID = 16, Provider = "BKK", RouteNumber = "2" },
				new Route { ID = 17, Provider = "BKK", RouteNumber = "3" },
				new Route { ID = 18, Provider = "BKK", RouteNumber = "4" },
				new Route { ID = 19, Provider = "BKK", RouteNumber = "6" },
				new Route { ID = 20, Provider = "BKK", RouteNumber = "5" }//,
				//new Route { ID = 21, Provider = "BKK", RouteNumber = "8E" },
				//new Route { ID = 22, Provider = "BKK", RouteNumber = "9" },
				//new Route { ID = 23, Provider = "BKK", RouteNumber = "72" },
				//new Route { ID = 24, Provider = "BKK", RouteNumber = "80" },
				//new Route { ID = 25, Provider = "BKK", RouteNumber = "77" }
				);

			modelBuilder.Entity<Stop>().HasData(
				new Stop { ID = 001, Name = "Albertfalva vasútállomás" },
				new Stop { ID = 002, Name = "Fonyód utca / Sáfrány utca" },
				new Stop { ID = 003, Name = "Herend utca" },
				new Stop { ID = 004, Name = "Nyírbátor utca" },
				new Stop { ID = 005, Name = "Csurgói utca" },
				new Stop { ID = 006, Name = "Andor utca / Tétényi utca" },
				new Stop { ID = 007, Name = "Bornemissza tér" },
				new Stop { ID = 008, Name = "Puskás Tivadar utca" },
				new Stop { ID = 009, Name = "Bikás park M" },
				new Stop { ID = 010, Name = "Tétényi út 30." },
				new Stop { ID = 011, Name = "Szent Imre Kórház" },
				new Stop { ID = 012, Name = "Karolina út" },
				new Stop { ID = 013, Name = "Kosztolány Dezső tér" },
				new Stop { ID = 014, Name = "Móricz Zsigmond körtér M" },
				new Stop { ID = 015, Name = "Gárdonyi tér" },
				new Stop { ID = 016, Name = "Szent Gellért tér - Műegyetem M" },
				new Stop { ID = 017, Name = "Rudas Gyógyfürdő" },
				new Stop { ID = 018, Name = "Március 15. tér" },
				new Stop { ID = 019, Name = "Ferenciek tere M" },
				new Stop { ID = 020, Name = "Astoria M" },
				new Stop { ID = 021, Name = "Uránia" },
				new Stop { ID = 022, Name = "Blaha Lujza tér M" },
				new Stop { ID = 023, Name = "Huszár utca" },
				new Stop { ID = 024, Name = "Keleti pályaudvar M" },
				new Stop { ID = 025, Name = "Reiner Frigyes park" },
				new Stop { ID = 026, Name = "Cházár András utca" },
				new Stop { ID = 027, Name = "Stefánia út / Thököly út" },
				new Stop { ID = 028, Name = "Zugló vasútállomás" },
				new Stop { ID = 029, Name = "Tisza István tér" },
				new Stop { ID = 030, Name = "Bosnyák tér" },
				new Stop { ID = 031, Name = "Rákospatak utca / Csömöri út" },
				new Stop { ID = 032, Name = "Miskolci utca / Csömöri út" },
				new Stop { ID = 033, Name = "Cinkotai út" },
				new Stop { ID = 034, Name = "Molnár Viktor utca" },
				new Stop { ID = 035, Name = "Apolló utca" },
				new Stop { ID = 036, Name = "Madách utca" },
				new Stop { ID = 037, Name = "Fő tér" },
				new Stop { ID = 038, Name = "Vásárcsarnok" },
				new Stop { ID = 039, Name = "Újpalota, Nyírpalota út" },
				new Stop { ID = 040, Name = "Mexikói út M" },
				new Stop { ID = 041, Name = "Kassai tér" },
				new Stop { ID = 042, Name = "Uzsoki Utcai Kórház" },
				new Stop { ID = 043, Name = "Szugló utca / Róna utca" },
				new Stop { ID = 044, Name = "Szugló utca / Nagy Lajos király útja" },
				new Stop { ID = 045, Name = "Fűrész utca / Szugló utca" },
				new Stop { ID = 046, Name = "Komócsy utca" },
				new Stop { ID = 047, Name = "Egressy út / Vezér utca" },
				new Stop { ID = 048, Name = "Mogyoródi út" },
				new Stop { ID = 049, Name = "Gödöllői utca" },
				new Stop { ID = 050, Name = "Fogarasi út" },
				new Stop { ID = 051, Name = "Tihamér utca" },
				new Stop { ID = 052, Name = "Füredi utca" },
				new Stop { ID = 053, Name = "Álmos vezér útja" },
				new Stop { ID = 054, Name = "Örs vezér tere M+H" },
				new Stop { ID = 055, Name = "Erzsébet királyné útja / Róna utca" },
				new Stop { ID = 056, Name = "Laky Adolf utca" },
				new Stop { ID = 057, Name = "Erzsébet királyné útja, aluljáró" },
				new Stop { ID = 058, Name = "Vörösmarty tér M" },
				new Stop { ID = 059, Name = "Deák Ferenc tér M" },
				new Stop { ID = 060, Name = "Bajcsy-Zsilinszky út M" },
				new Stop { ID = 061, Name = "Opera M" },
				new Stop { ID = 062, Name = "Oktogon M" },
				new Stop { ID = 063, Name = "Vörösmarty utca M" },
				new Stop { ID = 064, Name = "Kodály körönd M" },
				new Stop { ID = 065, Name = "Bajza utca M" },
				new Stop { ID = 066, Name = "Hősök tere M" },
				new Stop { ID = 067, Name = "Széchenyi fürdő M" },
				new Stop { ID = 068, Name = "Déli pályaudvar M" },
				new Stop { ID = 069, Name = "Széll Kálmán tér M" },
				new Stop { ID = 070, Name = "Batthyány tér M+H" },
				new Stop { ID = 071, Name = "Kossuth Lajos tér M" },
				new Stop { ID = 072, Name = "Puskás Ferenc Stadion M" },
				new Stop { ID = 073, Name = "Pillangó utca M" },
				new Stop { ID = 074, Name = "Újpest-központ M" },
				new Stop { ID = 075, Name = "Újpest-városkapu M" },
				new Stop { ID = 076, Name = "Gyöngyösi utca M" },
				new Stop { ID = 077, Name = "Forgách utca M" },
				new Stop { ID = 078, Name = "Göncz Árpád városközpont M" },
				new Stop { ID = 079, Name = "Dózsa György út M" },
				new Stop { ID = 080, Name = "Lehel tér M" },
				new Stop { ID = 081, Name = "Nyugati pályaudvar M" },
				new Stop { ID = 082, Name = "Arany János utca M" },
				new Stop { ID = 083, Name = "Kálvin tér M" },
				new Stop { ID = 084, Name = "Corvin-negyed M" },
				new Stop { ID = 085, Name = "Semmelweis Klinikák M" },
				new Stop { ID = 086, Name = "Nagyvárad tér M" },
				new Stop { ID = 087, Name = "Népliget M" },
				new Stop { ID = 088, Name = "Ecseri út M" },
				new Stop { ID = 089, Name = "Pöttyös utca M" },
				new Stop { ID = 090, Name = "Határ út M" },
				new Stop { ID = 091, Name = "Kőbánya-Kispest M" },
				new Stop { ID = 092, Name = "II. János Pál pápa tér M" },
				new Stop { ID = 093, Name = "Rákóczi tér M" },
				new Stop { ID = 094, Name = "Fővám tér M" },
				new Stop { ID = 095, Name = "Újbuda-központ M" },
				new Stop { ID = 096, Name = "Kelenföld vasútállomás M" },
				new Stop { ID = 097, Name = "Margit híd, budai hídfő H" },
				new Stop { ID = 098, Name = "Szépvölgyi út H" },
				new Stop { ID = 099, Name = "Tímár utca H" },
				new Stop { ID = 100, Name = "Szentlélek tér H" },
				new Stop { ID = 101, Name = "Filatorigát" },
				new Stop { ID = 102, Name = "Kaszásdűlő H" },
				new Stop { ID = 103, Name = "Aquincum H" },
				new Stop { ID = 104, Name = "Rómaifürdő H" },
				new Stop { ID = 105, Name = "Csillaghegy H" },
				new Stop { ID = 106, Name = "Békásmegyer H" },
				new Stop { ID = 107, Name = "Budakalász" },
				new Stop { ID = 108, Name = "Budakalász, Lenfonó H" },
				new Stop { ID = 109, Name = "Szentistvántelep H" },
				new Stop { ID = 110, Name = "Pomáz H" },
				new Stop { ID = 111, Name = "Pannóniatelep" },
				new Stop { ID = 112, Name = "Szentendre" },
				new Stop { ID = 113, Name = "Közvágóhíd H" },
				new Stop { ID = 114, Name = "Kén utca H" },
				new Stop { ID = 115, Name = "Pesterzsébet felső H" },
				new Stop { ID = 116, Name = "Torontál utca H" },
				new Stop { ID = 117, Name = "Soroksár felső H" },
				new Stop { ID = 118, Name = "Soroksár, Hősök tere H" },
				new Stop { ID = 119, Name = "Szent István utca H" },
				new Stop { ID = 120, Name = "Milleniumtelep H" },
				new Stop { ID = 121, Name = "Dunaharaszti felső H" },
				new Stop { ID = 122, Name = "Dunaharaszti külső H" },
				new Stop { ID = 123, Name = "Szigetszentmiklós" },
				new Stop { ID = 124, Name = "József Attila-telep" },
				new Stop { ID = 125, Name = "Szigetszentmiklós alsó H" },
				new Stop { ID = 126, Name = "Szigetszentmiklós-Gyártelep" },
				new Stop { ID = 127, Name = "Szigethalom H" },
				new Stop { ID = 128, Name = "Szigethalom alsó" },
				new Stop { ID = 129, Name = "Tököl" },
				new Stop { ID = 130, Name = "Szigetcsép" },
				new Stop { ID = 131, Name = "Szigetszentmárton-Szigetújfalu" },
				new Stop { ID = 132, Name = "Horgásztanyák" },
				new Stop { ID = 133, Name = "Angyalsziget" },
				new Stop { ID = 134, Name = "Ráckeve" },
				new Stop { ID = 135, Name = "Boráros tér H" },
				new Stop { ID = 136, Name = "Müpa - Nemzeti Színház H" },
				new Stop { ID = 137, Name = "Szabadkikötő H" },
				new Stop { ID = 138, Name = "Szent Imre tér H" },
				new Stop { ID = 139, Name = "Karácsony Sándor utca H" },
				new Stop { ID = 140, Name = "Csepel H" },
				new Stop { ID = 141, Name = "Rákosfalva H" },
				new Stop { ID = 142, Name = "Nagyicce H" },
				new Stop { ID = 143, Name = "Sashalom H" },
				new Stop { ID = 144, Name = "Mátyásföld, repülőtér H" },
				new Stop { ID = 145, Name = "Mátyásföld, Imre utca H" },
				new Stop { ID = 146, Name = "Mátyásföld alsó H" },
				new Stop { ID = 147, Name = "Cinkota H" },
				new Stop { ID = 148, Name = "Cinkota alsó H" },
				new Stop { ID = 149, Name = "Árpádföld H" },
				new Stop { ID = 150, Name = "Szabadságtelep H" },
				new Stop { ID = 151, Name = "Csömör H" },
				new Stop { ID = 152, Name = "Ilonatelep H" },
				new Stop { ID = 153, Name = "Kistarcsa, kórház H" },
				new Stop { ID = 154, Name = "Kistarcsa H" },
				new Stop { ID = 155, Name = "Zsófialiget" },
				new Stop { ID = 156, Name = "Kerepes" },
				new Stop { ID = 157, Name = "Szilasliget" },
				new Stop { ID = 158, Name = "Mogyoród" },
				new Stop { ID = 159, Name = "Szentjakab" },
				new Stop { ID = 160, Name = "Gödöllő, Erzsébet park" },
				new Stop { ID = 161, Name = "Gödöllő, Szabadság tér" },
				new Stop { ID = 162, Name = "Gödöllő, Palotakert" },
				new Stop { ID = 163, Name = "Gödöllő" },
				new Stop { ID = 164, Name = "Bártfai utca" },
				new Stop { ID = 165, Name = "Etele út / Fehérvári út" },
				new Stop { ID = 166, Name = "Hengermalom út / Szerémi út" },
				new Stop { ID = 167, Name = "Hauszmann Alajos utca / Szerémi út" },
				new Stop { ID = 168, Name = "Budafoki út / Dombóvári út" },
				new Stop { ID = 169, Name = "Infopark" },
				new Stop { ID = 170, Name = "Mester utca / Könyves Kálmán körút" },
				new Stop { ID = 171, Name = "Ferencváros vasútállomás - Málenkij Robot Emlékhely" },
				new Stop { ID = 172, Name = "Albert Flórián út" },
				new Stop { ID = 173, Name = "Vajda Péter utca" },
				new Stop { ID = 174, Name = "Kőbányai út / Könyves Kálmán körút" },
				new Stop { ID = 175, Name = "Hidegkuti Nándor Stadion" },
				new Stop { ID = 176, Name = "Hős utca" },
				new Stop { ID = 177, Name = "Egressy út / Hungária körút" },
				new Stop { ID = 178, Name = "Ajtói Dürer sor" },
				new Stop { ID = 179, Name = "Kacsóh Pongrác út" },
				new Stop { ID = 180, Name = "Vágány utca / Róbert Károly körút" },
				new Stop { ID = 181, Name = "Lehel utca / Róbert Károly körút" },
				new Stop { ID = 182, Name = "Honvédkórház" },
				new Stop { ID = 183, Name = "Népfürdő utca / Árpád híd" },
				new Stop { ID = 184, Name = "Flórián tér" },
				new Stop { ID = 185, Name = "Óbudai rendelőintézet" },
				new Stop { ID = 186, Name = "Bécsi út / Vörösvári út" },
				new Stop { ID = 187, Name = "Jászai Mari tér" },
				new Stop { ID = 188, Name = "Országház, látogatóközpont" },
				new Stop { ID = 189, Name = "Széchenyi István tér" },
				new Stop { ID = 190, Name = "Eötvös tér" },
				new Stop { ID = 191, Name = "Vigadó tér" },
				new Stop { ID = 192, Name = "Zsil utca" },
				new Stop { ID = 193, Name = "Haller utca / Soroksári utca" },
				new Stop { ID = 194, Name = "Nagy Lajos király útja / Czobor utca" },
				new Stop { ID = 195, Name = "Kerékgyártó utca" },
				new Stop { ID = 196, Name = "Egressy tér" },
				new Stop { ID = 197, Name = "Jeszenák János utca" },
				new Stop { ID = 198, Name = "Pongrátz Gergely tér" },
				new Stop { ID = 199, Name = "Tihamér utca" },
				new Stop { ID = 200, Name = "Fehér úti ipari park" },
				new Stop { ID = 201, Name = "Terebesi utca" },
				new Stop { ID = 202, Name = "Élessarok" },
				new Stop { ID = 203, Name = "Ónodi utca" },
				new Stop { ID = 204, Name = "Szent László tér" },
				new Stop { ID = 205, Name = "Kőbánya alsó vasútállomás" },
				new Stop { ID = 206, Name = "Kocsis Sándor Sportközpont" },
				new Stop { ID = 207, Name = "Fertő utca / Bihari utca" },
				new Stop { ID = 208, Name = "Balkán utca" },
				new Stop { ID = 209, Name = "Közterületfenntartó Zrt." },
				new Stop { ID = 210, Name = "Csengettyű utca" },
				new Stop { ID = 211, Name = "Epreserdő utca" },
				new Stop { ID = 212, Name = "Nagykőrösi út / Határ út" },
				new Stop { ID = 213, Name = "Mártírok útja / Határ út" },
				new Stop { ID = 214, Name = "Jókai Mór utca / Határ út" },
				new Stop { ID = 215, Name = "Ősz utca" },
				new Stop { ID = 216, Name = "Gubacsi út / Határ út" },
				new Stop { ID = 217, Name = "Kőbánya alsó vasútállomás (Mázsa tér)" },
				new Stop { ID = 218, Name = "Széna tér" },
				new Stop { ID = 219, Name = "Mechwart liget" },
				new Stop { ID = 220, Name = "Margitsziget / Margit híd" },
				new Stop { ID = 221, Name = "Király utca / Erzsébet körút" },
				new Stop { ID = 222, Name = "Wesselényi utca / Erzsébet körút" },
				new Stop { ID = 223, Name = "Harminckettesek tere" },
				new Stop { ID = 224, Name = "Mester utca / Ferenc körút" },
				new Stop { ID = 225, Name = "Petőfi híd, budai hídfő" },
				new Stop { ID = 226, Name = "Budafoki út / Szerémi sor" },
				new Stop { ID = 227, Name = "Budafoki út / Karinthy Frigyes út" },
				new Stop { ID = 228, Name = "Pasaréti tér" },
				new Stop { ID = 229, Name = "Harangvirág utca" },
				new Stop { ID = 230, Name = "Virág árok" },
				new Stop { ID = 231, Name = "Gábor Áron utca / Pasaréti út" },
				new Stop { ID = 232, Name = "Júlia utca" },
				new Stop { ID = 233, Name = "Vasas sportpálya" },
				new Stop { ID = 234, Name = "Városmajor" },
				new Stop { ID = 235, Name = "Nyúl utca" },
				new Stop { ID = 236, Name = "Körmöci utca" },
				new Stop { ID = 237, Name = "Korlát utca" },
				new Stop { ID = 238, Name = "Mikó utca" },
				new Stop { ID = 239, Name = "Alagút utca" },
				new Stop { ID = 240, Name = "Dózsa György tér" },
				new Stop { ID = 241, Name = "Döbrentei tér" },
				new Stop { ID = 242, Name = "Korong utca" },
				new Stop { ID = 243, Name = "Fűrész utca" },
				new Stop { ID = 244, Name = "Rákospatak utca" },
				new Stop { ID = 245, Name = "Miskolci utca" },
				new Stop { ID = 246, Name = "Öv utca" },
				new Stop { ID = 247, Name = "Tóth István utca" },
				new Stop { ID = 248, Name = "Vág utca" },
				new Stop { ID = 249, Name = "Opál utca" },
				new Stop { ID = 250, Name = "Széchenyi út" },
				new Stop { ID = 251, Name = "Szent Korona útja" },
				new Stop { ID = 252, Name = "Wesselényi utca" },
				new Stop { ID = 253, Name = "Szerencs utca" },
				new Stop { ID = 254, Name = "Rákos úti szakrendelő" },
				new Stop { ID = 255, Name = "Illyés Gyula utca" },
				new Stop { ID = 256, Name = "Epres sor" },
				new Stop { ID = 257, Name = "Juhos utca" },
				new Stop { ID = 258, Name = "Kossuth utca, lakótelep" },
				new Stop { ID = 259, Name = "Rákospalota, Kossuth utca" },
				new Stop { ID = 260, Name = "Szarvas tér" }//,
				//new Stop { ID = 226, Name = "" },
				);

			modelBuilder.Entity<RouteStop>().HasData(
				new RouteStop { RouteID = 01, StopID = 001, Direction = Direction.Outbound, Order = 1 },
				new RouteStop { RouteID = 01, StopID = 002, Direction = Direction.Outbound, Order = 2 },
				new RouteStop { RouteID = 01, StopID = 003, Direction = Direction.Outbound, Order = 3 },
				new RouteStop { RouteID = 01, StopID = 004, Direction = Direction.Outbound, Order = 4 },
				new RouteStop { RouteID = 01, StopID = 005, Direction = Direction.Outbound, Order = 5 },
				new RouteStop { RouteID = 01, StopID = 006, Direction = Direction.Outbound, Order = 6 },
				new RouteStop { RouteID = 01, StopID = 007, Direction = Direction.Outbound, Order = 7 },
				new RouteStop { RouteID = 01, StopID = 008, Direction = Direction.Outbound, Order = 8 },
				new RouteStop { RouteID = 01, StopID = 009, Direction = Direction.Outbound, Order = 9 },
				new RouteStop { RouteID = 01, StopID = 010, Direction = Direction.Outbound, Order = 10 },
				new RouteStop { RouteID = 01, StopID = 011, Direction = Direction.Outbound, Order = 11 },
				new RouteStop { RouteID = 01, StopID = 012, Direction = Direction.Outbound, Order = 12 },
				new RouteStop { RouteID = 01, StopID = 013, Direction = Direction.Outbound, Order = 13 },
				new RouteStop { RouteID = 01, StopID = 014, Direction = Direction.Outbound, Order = 14 },
				new RouteStop { RouteID = 01, StopID = 015, Direction = Direction.Outbound, Order = 15 },
				new RouteStop { RouteID = 01, StopID = 016, Direction = Direction.Outbound, Order = 16 },
				new RouteStop { RouteID = 01, StopID = 017, Direction = Direction.Outbound, Order = 17 },
				new RouteStop { RouteID = 01, StopID = 018, Direction = Direction.Outbound, Order = 18 },
				new RouteStop { RouteID = 01, StopID = 019, Direction = Direction.Outbound, Order = 19 },
				new RouteStop { RouteID = 01, StopID = 020, Direction = Direction.Outbound, Order = 20 },
				new RouteStop { RouteID = 01, StopID = 021, Direction = Direction.Outbound, Order = 21 },
				new RouteStop { RouteID = 01, StopID = 022, Direction = Direction.Outbound, Order = 22 },
				new RouteStop { RouteID = 01, StopID = 023, Direction = Direction.Outbound, Order = 23 },
				new RouteStop { RouteID = 01, StopID = 024, Direction = Direction.Outbound, Order = 24 },
				new RouteStop { RouteID = 01, StopID = 025, Direction = Direction.Outbound, Order = 25 },
				new RouteStop { RouteID = 01, StopID = 026, Direction = Direction.Outbound, Order = 26 },
				new RouteStop { RouteID = 01, StopID = 027, Direction = Direction.Outbound, Order = 27 },
				new RouteStop { RouteID = 01, StopID = 028, Direction = Direction.Outbound, Order = 28 },
				new RouteStop { RouteID = 01, StopID = 029, Direction = Direction.Outbound, Order = 29 },
				new RouteStop { RouteID = 01, StopID = 030, Direction = Direction.Outbound, Order = 30 },
				new RouteStop { RouteID = 01, StopID = 031, Direction = Direction.Outbound, Order = 31 },
				new RouteStop { RouteID = 01, StopID = 032, Direction = Direction.Outbound, Order = 32 },
				new RouteStop { RouteID = 01, StopID = 033, Direction = Direction.Outbound, Order = 33 },
				new RouteStop { RouteID = 01, StopID = 034, Direction = Direction.Outbound, Order = 34 },
				new RouteStop { RouteID = 01, StopID = 035, Direction = Direction.Outbound, Order = 35 },
				new RouteStop { RouteID = 01, StopID = 036, Direction = Direction.Outbound, Order = 36 },
				new RouteStop { RouteID = 01, StopID = 037, Direction = Direction.Outbound, Order = 37 },
				new RouteStop { RouteID = 01, StopID = 038, Direction = Direction.Outbound, Order = 38 },
				new RouteStop { RouteID = 01, StopID = 039, Direction = Direction.Outbound, Order = 39 },
				new RouteStop { RouteID = 01, StopID = 039, Direction = Direction.Inbound, Order = 1 },
				new RouteStop { RouteID = 01, StopID = 038, Direction = Direction.Inbound, Order = 2 },
				new RouteStop { RouteID = 01, StopID = 037, Direction = Direction.Inbound, Order = 3 },
				new RouteStop { RouteID = 01, StopID = 036, Direction = Direction.Inbound, Order = 4 },
				new RouteStop { RouteID = 01, StopID = 035, Direction = Direction.Inbound, Order = 5 },
				new RouteStop { RouteID = 01, StopID = 034, Direction = Direction.Inbound, Order = 6 },
				new RouteStop { RouteID = 01, StopID = 033, Direction = Direction.Inbound, Order = 7 },
				new RouteStop { RouteID = 01, StopID = 032, Direction = Direction.Inbound, Order = 8 },
				new RouteStop { RouteID = 01, StopID = 031, Direction = Direction.Inbound, Order = 9 },
				new RouteStop { RouteID = 01, StopID = 030, Direction = Direction.Inbound, Order = 10 },
				new RouteStop { RouteID = 01, StopID = 029, Direction = Direction.Inbound, Order = 11 },
				new RouteStop { RouteID = 01, StopID = 028, Direction = Direction.Inbound, Order = 12 },
				new RouteStop { RouteID = 01, StopID = 027, Direction = Direction.Inbound, Order = 13 },
				new RouteStop { RouteID = 01, StopID = 026, Direction = Direction.Inbound, Order = 14 },
				new RouteStop { RouteID = 01, StopID = 025, Direction = Direction.Inbound, Order = 15 },
				new RouteStop { RouteID = 01, StopID = 024, Direction = Direction.Inbound, Order = 16 },
				new RouteStop { RouteID = 01, StopID = 023, Direction = Direction.Inbound, Order = 17 },
				new RouteStop { RouteID = 01, StopID = 022, Direction = Direction.Inbound, Order = 18 },
				new RouteStop { RouteID = 01, StopID = 021, Direction = Direction.Inbound, Order = 19 },
				new RouteStop { RouteID = 01, StopID = 020, Direction = Direction.Inbound, Order = 20 },
				new RouteStop { RouteID = 01, StopID = 019, Direction = Direction.Inbound, Order = 21 },
				new RouteStop { RouteID = 01, StopID = 018, Direction = Direction.Inbound, Order = 22 },
				new RouteStop { RouteID = 01, StopID = 017, Direction = Direction.Inbound, Order = 23 },
				new RouteStop { RouteID = 01, StopID = 016, Direction = Direction.Inbound, Order = 24 },
				new RouteStop { RouteID = 01, StopID = 015, Direction = Direction.Inbound, Order = 25 },
				new RouteStop { RouteID = 01, StopID = 014, Direction = Direction.Inbound, Order = 26 },
				new RouteStop { RouteID = 01, StopID = 013, Direction = Direction.Inbound, Order = 27 },
				new RouteStop { RouteID = 01, StopID = 012, Direction = Direction.Inbound, Order = 28 },
				new RouteStop { RouteID = 01, StopID = 011, Direction = Direction.Inbound, Order = 29 },
				new RouteStop { RouteID = 01, StopID = 010, Direction = Direction.Inbound, Order = 30 },
				new RouteStop { RouteID = 01, StopID = 009, Direction = Direction.Inbound, Order = 31 },
				new RouteStop { RouteID = 01, StopID = 008, Direction = Direction.Inbound, Order = 32 },
				new RouteStop { RouteID = 01, StopID = 007, Direction = Direction.Inbound, Order = 33 },
				new RouteStop { RouteID = 01, StopID = 005, Direction = Direction.Inbound, Order = 34 },
				new RouteStop { RouteID = 01, StopID = 004, Direction = Direction.Inbound, Order = 35 },
				new RouteStop { RouteID = 01, StopID = 003, Direction = Direction.Inbound, Order = 36 },
				new RouteStop { RouteID = 01, StopID = 002, Direction = Direction.Inbound, Order = 37 },
				new RouteStop { RouteID = 01, StopID = 001, Direction = Direction.Inbound, Order = 38 },
				new RouteStop { RouteID = 02, StopID = 022, Direction = Direction.Outbound, Order = 1},
				new RouteStop { RouteID = 02, StopID = 022, Direction = Direction.Outbound, Order = 2},
				new RouteStop { RouteID = 02, StopID = 024, Direction = Direction.Outbound, Order = 3},
				new RouteStop { RouteID = 02, StopID = 028, Direction = Direction.Outbound, Order = 4},
				new RouteStop { RouteID = 02, StopID = 030, Direction = Direction.Outbound, Order = 5},
				new RouteStop { RouteID = 02, StopID = 034, Direction = Direction.Outbound, Order = 6},
				new RouteStop { RouteID = 02, StopID = 037, Direction = Direction.Outbound, Order = 7},
				new RouteStop { RouteID = 02, StopID = 038, Direction = Direction.Outbound, Order = 8},
				new RouteStop { RouteID = 02, StopID = 039, Direction = Direction.Outbound, Order = 9},
				new RouteStop { RouteID = 02, StopID = 039, Direction = Direction.Inbound, Order = 1},
				new RouteStop { RouteID = 02, StopID = 038, Direction = Direction.Inbound, Order = 2},
				new RouteStop { RouteID = 02, StopID = 037, Direction = Direction.Inbound, Order = 3},
				new RouteStop { RouteID = 02, StopID = 034, Direction = Direction.Inbound, Order = 4},
				new RouteStop { RouteID = 02, StopID = 030, Direction = Direction.Inbound, Order = 5},
				new RouteStop { RouteID = 02, StopID = 028, Direction = Direction.Inbound, Order = 6},
				new RouteStop { RouteID = 02, StopID = 024, Direction = Direction.Inbound, Order = 7},
				new RouteStop { RouteID = 02, StopID = 022, Direction = Direction.Inbound, Order = 8},
				new RouteStop { RouteID = 02, StopID = 022, Direction = Direction.Inbound, Order = 9},
				new RouteStop { RouteID = 03, StopID = 040, Direction = Direction.Outbound, Order = 1},
				new RouteStop { RouteID = 03, StopID = 041, Direction = Direction.Outbound, Order = 2},
				new RouteStop { RouteID = 03, StopID = 042, Direction = Direction.Outbound, Order = 3},
				new RouteStop { RouteID = 03, StopID = 029, Direction = Direction.Outbound, Order = 4},
				new RouteStop { RouteID = 03, StopID = 043, Direction = Direction.Outbound, Order = 5},
				new RouteStop { RouteID = 03, StopID = 044, Direction = Direction.Outbound, Order = 6},
				new RouteStop { RouteID = 03, StopID = 045, Direction = Direction.Outbound, Order = 7},
				new RouteStop { RouteID = 03, StopID = 046, Direction = Direction.Outbound, Order = 8},
				new RouteStop { RouteID = 03, StopID = 047, Direction = Direction.Outbound, Order = 9},
				new RouteStop { RouteID = 03, StopID = 048, Direction = Direction.Outbound, Order = 10},
				new RouteStop { RouteID = 03, StopID = 049, Direction = Direction.Outbound, Order = 11},
				new RouteStop { RouteID = 03, StopID = 050, Direction = Direction.Outbound, Order = 12},
				new RouteStop { RouteID = 03, StopID = 051, Direction = Direction.Outbound, Order = 13},
				new RouteStop { RouteID = 03, StopID = 052, Direction = Direction.Outbound, Order = 14},
				new RouteStop { RouteID = 03, StopID = 053, Direction = Direction.Outbound, Order = 15},
				new RouteStop { RouteID = 03, StopID = 054, Direction = Direction.Outbound, Order = 16},
				new RouteStop { RouteID = 03, StopID = 054, Direction = Direction.Inbound, Order = 1},
				new RouteStop { RouteID = 03, StopID = 053, Direction = Direction.Inbound, Order = 2},
				new RouteStop { RouteID = 03, StopID = 052, Direction = Direction.Inbound, Order = 3},
				new RouteStop { RouteID = 03, StopID = 051, Direction = Direction.Inbound, Order = 4},
				new RouteStop { RouteID = 03, StopID = 050, Direction = Direction.Inbound, Order = 5},
				new RouteStop { RouteID = 03, StopID = 049, Direction = Direction.Inbound, Order = 6},
				new RouteStop { RouteID = 03, StopID = 048, Direction = Direction.Inbound, Order = 7},
				new RouteStop { RouteID = 03, StopID = 047, Direction = Direction.Inbound, Order = 8},
				new RouteStop { RouteID = 03, StopID = 046, Direction = Direction.Inbound, Order = 9},
				new RouteStop { RouteID = 03, StopID = 045, Direction = Direction.Inbound, Order = 10},
				new RouteStop { RouteID = 03, StopID = 044, Direction = Direction.Inbound, Order = 11},
				new RouteStop { RouteID = 03, StopID = 043, Direction = Direction.Inbound, Order = 12},
				new RouteStop { RouteID = 03, StopID = 029, Direction = Direction.Inbound, Order = 13},
				new RouteStop { RouteID = 03, StopID = 042, Direction = Direction.Inbound, Order = 14},
				new RouteStop { RouteID = 03, StopID = 055, Direction = Direction.Inbound, Order = 15},
				new RouteStop { RouteID = 03, StopID = 056, Direction = Direction.Inbound, Order = 16},
				new RouteStop { RouteID = 03, StopID = 057, Direction = Direction.Inbound, Order = 17},
				new RouteStop { RouteID = 03, StopID = 040, Direction = Direction.Inbound, Order = 18},
				new RouteStop { RouteID = 04, StopID = 055, Direction = Direction.Outbound, Order = 1},
				new RouteStop { RouteID = 04, StopID = 042, Direction = Direction.Outbound, Order = 2},
				new RouteStop { RouteID = 04, StopID = 029, Direction = Direction.Outbound, Order = 3},
				new RouteStop { RouteID = 04, StopID = 043, Direction = Direction.Outbound, Order = 4},
				new RouteStop { RouteID = 04, StopID = 044, Direction = Direction.Outbound, Order = 5},
				new RouteStop { RouteID = 04, StopID = 045, Direction = Direction.Outbound, Order = 6},
				new RouteStop { RouteID = 04, StopID = 046, Direction = Direction.Outbound, Order = 7},
				new RouteStop { RouteID = 04, StopID = 047, Direction = Direction.Outbound, Order = 8},
				new RouteStop { RouteID = 04, StopID = 048, Direction = Direction.Outbound, Order = 9},
				new RouteStop { RouteID = 04, StopID = 049, Direction = Direction.Outbound, Order = 10},
				new RouteStop { RouteID = 04, StopID = 050, Direction = Direction.Outbound, Order = 11},
				new RouteStop { RouteID = 04, StopID = 051, Direction = Direction.Outbound, Order = 12},
				new RouteStop { RouteID = 04, StopID = 052, Direction = Direction.Outbound, Order = 13},
				new RouteStop { RouteID = 04, StopID = 053, Direction = Direction.Outbound, Order = 14},
				new RouteStop { RouteID = 04, StopID = 054, Direction = Direction.Outbound, Order = 15},
				new RouteStop { RouteID = 04, StopID = 054, Direction = Direction.Inbound, Order = 1},
				new RouteStop { RouteID = 04, StopID = 053, Direction = Direction.Inbound, Order = 2},
				new RouteStop { RouteID = 04, StopID = 052, Direction = Direction.Inbound, Order = 3},
				new RouteStop { RouteID = 04, StopID = 051, Direction = Direction.Inbound, Order = 4},
				new RouteStop { RouteID = 04, StopID = 050, Direction = Direction.Inbound, Order = 5},
				new RouteStop { RouteID = 04, StopID = 049, Direction = Direction.Inbound, Order = 6},
				new RouteStop { RouteID = 04, StopID = 048, Direction = Direction.Inbound, Order = 7},
				new RouteStop { RouteID = 04, StopID = 047, Direction = Direction.Inbound, Order = 8},
				new RouteStop { RouteID = 04, StopID = 046, Direction = Direction.Inbound, Order = 9},
				new RouteStop { RouteID = 04, StopID = 045, Direction = Direction.Inbound, Order = 10},
				new RouteStop { RouteID = 04, StopID = 044, Direction = Direction.Inbound, Order = 11},
				new RouteStop { RouteID = 04, StopID = 043, Direction = Direction.Inbound, Order = 12},
				new RouteStop { RouteID = 04, StopID = 029, Direction = Direction.Inbound, Order = 13},
				new RouteStop { RouteID = 04, StopID = 042, Direction = Direction.Inbound, Order = 14},
				new RouteStop { RouteID = 04, StopID = 055, Direction = Direction.Inbound, Order = 15},
				new RouteStop { RouteID = 05, StopID = 058, Direction = Direction.Outbound, Order = 1},
				new RouteStop { RouteID = 05, StopID = 059, Direction = Direction.Outbound, Order = 2},
				new RouteStop { RouteID = 05, StopID = 060, Direction = Direction.Outbound, Order = 3},
				new RouteStop { RouteID = 05, StopID = 061, Direction = Direction.Outbound, Order = 4},
				new RouteStop { RouteID = 05, StopID = 062, Direction = Direction.Outbound, Order = 5},
				new RouteStop { RouteID = 05, StopID = 063, Direction = Direction.Outbound, Order = 6},
				new RouteStop { RouteID = 05, StopID = 064, Direction = Direction.Outbound, Order = 7},
				new RouteStop { RouteID = 05, StopID = 065, Direction = Direction.Outbound, Order = 8},
				new RouteStop { RouteID = 05, StopID = 066, Direction = Direction.Outbound, Order = 9},
				new RouteStop { RouteID = 05, StopID = 067, Direction = Direction.Outbound, Order = 10},
				new RouteStop { RouteID = 05, StopID = 040, Direction = Direction.Outbound, Order = 11},
				new RouteStop { RouteID = 05, StopID = 040, Direction = Direction.Inbound, Order = 1},
				new RouteStop { RouteID = 05, StopID = 067, Direction = Direction.Inbound, Order = 2},
				new RouteStop { RouteID = 05, StopID = 066, Direction = Direction.Inbound, Order = 3},
				new RouteStop { RouteID = 05, StopID = 065, Direction = Direction.Inbound, Order = 4},
				new RouteStop { RouteID = 05, StopID = 064, Direction = Direction.Inbound, Order = 5},
				new RouteStop { RouteID = 05, StopID = 063, Direction = Direction.Inbound, Order = 6},
				new RouteStop { RouteID = 05, StopID = 062, Direction = Direction.Inbound, Order = 7},
				new RouteStop { RouteID = 05, StopID = 061, Direction = Direction.Inbound, Order = 8},
				new RouteStop { RouteID = 05, StopID = 060, Direction = Direction.Inbound, Order = 9},
				new RouteStop { RouteID = 05, StopID = 059, Direction = Direction.Inbound, Order = 10},
				new RouteStop { RouteID = 05, StopID = 058, Direction = Direction.Inbound, Order = 11},
				new RouteStop { RouteID = 06, StopID = 068, Direction = Direction.Outbound, Order = 1},
				new RouteStop { RouteID = 06, StopID = 069, Direction = Direction.Outbound, Order = 2},
				new RouteStop { RouteID = 06, StopID = 070, Direction = Direction.Outbound, Order = 3},
				new RouteStop { RouteID = 06, StopID = 071, Direction = Direction.Outbound, Order = 4},
				new RouteStop { RouteID = 06, StopID = 059, Direction = Direction.Outbound, Order = 5},
				new RouteStop { RouteID = 06, StopID = 020, Direction = Direction.Outbound, Order = 6},
				new RouteStop { RouteID = 06, StopID = 022, Direction = Direction.Outbound, Order = 7},
				new RouteStop { RouteID = 06, StopID = 024, Direction = Direction.Outbound, Order = 8},
				new RouteStop { RouteID = 06, StopID = 072, Direction = Direction.Outbound, Order = 9},
				new RouteStop { RouteID = 06, StopID = 073, Direction = Direction.Outbound, Order = 10},
				new RouteStop { RouteID = 06, StopID = 054, Direction = Direction.Outbound, Order = 11},
				new RouteStop { RouteID = 06, StopID = 054, Direction = Direction.Inbound, Order = 1},
				new RouteStop { RouteID = 06, StopID = 073, Direction = Direction.Inbound, Order = 2},
				new RouteStop { RouteID = 06, StopID = 072, Direction = Direction.Inbound, Order = 3},
				new RouteStop { RouteID = 06, StopID = 024, Direction = Direction.Inbound, Order = 4},
				new RouteStop { RouteID = 06, StopID = 022, Direction = Direction.Inbound, Order = 5},
				new RouteStop { RouteID = 06, StopID = 020, Direction = Direction.Inbound, Order = 6},
				new RouteStop { RouteID = 06, StopID = 059, Direction = Direction.Inbound, Order = 7},
				new RouteStop { RouteID = 06, StopID = 071, Direction = Direction.Inbound, Order = 8},
				new RouteStop { RouteID = 06, StopID = 070, Direction = Direction.Inbound, Order = 9},
				new RouteStop { RouteID = 06, StopID = 069, Direction = Direction.Inbound, Order = 10},
				new RouteStop { RouteID = 06, StopID = 068, Direction = Direction.Inbound, Order = 11},
				new RouteStop { RouteID = 07, StopID = 074, Direction = Direction.Outbound, Order = 1},
				new RouteStop { RouteID = 07, StopID = 075, Direction = Direction.Outbound, Order = 2},
				new RouteStop { RouteID = 07, StopID = 076, Direction = Direction.Outbound, Order = 3},
				new RouteStop { RouteID = 07, StopID = 077, Direction = Direction.Outbound, Order = 4},
				new RouteStop { RouteID = 07, StopID = 078, Direction = Direction.Outbound, Order = 5},
				new RouteStop { RouteID = 07, StopID = 079, Direction = Direction.Outbound, Order = 6},
				new RouteStop { RouteID = 07, StopID = 080, Direction = Direction.Outbound, Order = 7},
				new RouteStop { RouteID = 07, StopID = 081, Direction = Direction.Outbound, Order = 8},
				new RouteStop { RouteID = 07, StopID = 082, Direction = Direction.Outbound, Order = 9},
				new RouteStop { RouteID = 07, StopID = 059, Direction = Direction.Outbound, Order = 10},
				new RouteStop { RouteID = 07, StopID = 019, Direction = Direction.Outbound, Order = 11},
				new RouteStop { RouteID = 07, StopID = 083, Direction = Direction.Outbound, Order = 12},
				new RouteStop { RouteID = 07, StopID = 084, Direction = Direction.Outbound, Order = 13},
				new RouteStop { RouteID = 07, StopID = 085, Direction = Direction.Outbound, Order = 14},
				new RouteStop { RouteID = 07, StopID = 086, Direction = Direction.Outbound, Order = 15},
				new RouteStop { RouteID = 07, StopID = 087, Direction = Direction.Outbound, Order = 16},
				new RouteStop { RouteID = 07, StopID = 088, Direction = Direction.Outbound, Order = 17},
				new RouteStop { RouteID = 07, StopID = 089, Direction = Direction.Outbound, Order = 18},
				new RouteStop { RouteID = 07, StopID = 090, Direction = Direction.Outbound, Order = 19},
				new RouteStop { RouteID = 07, StopID = 091, Direction = Direction.Outbound, Order = 20},
				new RouteStop { RouteID = 07, StopID = 091, Direction = Direction.Inbound, Order = 1},
				new RouteStop { RouteID = 07, StopID = 090, Direction = Direction.Inbound, Order = 2},
				new RouteStop { RouteID = 07, StopID = 089, Direction = Direction.Inbound, Order = 3},
				new RouteStop { RouteID = 07, StopID = 088, Direction = Direction.Inbound, Order = 4},
				new RouteStop { RouteID = 07, StopID = 087, Direction = Direction.Inbound, Order = 5},
				new RouteStop { RouteID = 07, StopID = 086, Direction = Direction.Inbound, Order = 6},
				new RouteStop { RouteID = 07, StopID = 085, Direction = Direction.Inbound, Order = 7},
				new RouteStop { RouteID = 07, StopID = 084, Direction = Direction.Inbound, Order = 8},
				new RouteStop { RouteID = 07, StopID = 083, Direction = Direction.Inbound, Order = 9},
				new RouteStop { RouteID = 07, StopID = 019, Direction = Direction.Inbound, Order = 10},
				new RouteStop { RouteID = 07, StopID = 059, Direction = Direction.Inbound, Order = 11},
				new RouteStop { RouteID = 07, StopID = 082, Direction = Direction.Inbound, Order = 12},
				new RouteStop { RouteID = 07, StopID = 081, Direction = Direction.Inbound, Order = 13},
				new RouteStop { RouteID = 07, StopID = 080, Direction = Direction.Inbound, Order = 14},
				new RouteStop { RouteID = 07, StopID = 079, Direction = Direction.Inbound, Order = 15},
				new RouteStop { RouteID = 07, StopID = 078, Direction = Direction.Inbound, Order = 16},
				new RouteStop { RouteID = 07, StopID = 077, Direction = Direction.Inbound, Order = 17},
				new RouteStop { RouteID = 07, StopID = 076, Direction = Direction.Inbound, Order = 18},
				new RouteStop { RouteID = 07, StopID = 075, Direction = Direction.Inbound, Order = 19},
				new RouteStop { RouteID = 07, StopID = 074, Direction = Direction.Inbound, Order = 20},
				new RouteStop { RouteID = 08, StopID = 024, Direction = Direction.Outbound, Order = 1},
				new RouteStop { RouteID = 08, StopID = 092, Direction = Direction.Outbound, Order = 2},
				new RouteStop { RouteID = 08, StopID = 093, Direction = Direction.Outbound, Order = 3},
				new RouteStop { RouteID = 08, StopID = 083, Direction = Direction.Outbound, Order = 4},
				new RouteStop { RouteID = 08, StopID = 094, Direction = Direction.Outbound, Order = 5},
				new RouteStop { RouteID = 08, StopID = 016, Direction = Direction.Outbound, Order = 6},
				new RouteStop { RouteID = 08, StopID = 014, Direction = Direction.Outbound, Order = 7},
				new RouteStop { RouteID = 08, StopID = 095, Direction = Direction.Outbound, Order = 8},
				new RouteStop { RouteID = 08, StopID = 009, Direction = Direction.Outbound, Order = 9},
				new RouteStop { RouteID = 08, StopID = 096, Direction = Direction.Outbound, Order = 10},
				new RouteStop { RouteID = 08, StopID = 096, Direction = Direction.Inbound, Order = 1},
				new RouteStop { RouteID = 08, StopID = 009, Direction = Direction.Inbound, Order = 2},
				new RouteStop { RouteID = 08, StopID = 095, Direction = Direction.Inbound, Order = 3},
				new RouteStop { RouteID = 08, StopID = 014, Direction = Direction.Inbound, Order = 4},
				new RouteStop { RouteID = 08, StopID = 016, Direction = Direction.Inbound, Order = 5},
				new RouteStop { RouteID = 08, StopID = 094, Direction = Direction.Inbound, Order = 6},
				new RouteStop { RouteID = 08, StopID = 083, Direction = Direction.Inbound, Order = 7},
				new RouteStop { RouteID = 08, StopID = 093, Direction = Direction.Inbound, Order = 8},
				new RouteStop { RouteID = 08, StopID = 092, Direction = Direction.Inbound, Order = 9},
				new RouteStop { RouteID = 08, StopID = 024, Direction = Direction.Inbound, Order = 10},
				new RouteStop { RouteID = 09, StopID = 070, Direction = Direction.Outbound, Order = 1},
				new RouteStop { RouteID = 09, StopID = 097, Direction = Direction.Outbound, Order = 2},
				new RouteStop { RouteID = 09, StopID = 098, Direction = Direction.Outbound, Order = 3},
				new RouteStop { RouteID = 09, StopID = 099, Direction = Direction.Outbound, Order = 4},
				new RouteStop { RouteID = 09, StopID = 100, Direction = Direction.Outbound, Order = 5},
				new RouteStop { RouteID = 09, StopID = 101, Direction = Direction.Outbound, Order = 6},
				new RouteStop { RouteID = 09, StopID = 102, Direction = Direction.Outbound, Order = 7},
				new RouteStop { RouteID = 09, StopID = 103, Direction = Direction.Outbound, Order = 8},
				new RouteStop { RouteID = 09, StopID = 104, Direction = Direction.Outbound, Order = 9},
				new RouteStop { RouteID = 09, StopID = 105, Direction = Direction.Outbound, Order = 10},
				new RouteStop { RouteID = 09, StopID = 106, Direction = Direction.Outbound, Order = 11},
				new RouteStop { RouteID = 09, StopID = 107, Direction = Direction.Outbound, Order = 12},
				new RouteStop { RouteID = 09, StopID = 108, Direction = Direction.Outbound, Order = 13},
				new RouteStop { RouteID = 09, StopID = 109, Direction = Direction.Outbound, Order = 14},
				new RouteStop { RouteID = 09, StopID = 110, Direction = Direction.Outbound, Order = 15},
				new RouteStop { RouteID = 09, StopID = 111, Direction = Direction.Outbound, Order = 16},
				new RouteStop { RouteID = 09, StopID = 112, Direction = Direction.Outbound, Order = 17},
				new RouteStop { RouteID = 09, StopID = 112, Direction = Direction.Inbound, Order = 1},
				new RouteStop { RouteID = 09, StopID = 111, Direction = Direction.Inbound, Order = 2},
				new RouteStop { RouteID = 09, StopID = 110, Direction = Direction.Inbound, Order = 3},
				new RouteStop { RouteID = 09, StopID = 109, Direction = Direction.Inbound, Order = 4},
				new RouteStop { RouteID = 09, StopID = 108, Direction = Direction.Inbound, Order = 5},
				new RouteStop { RouteID = 09, StopID = 107, Direction = Direction.Inbound, Order = 6},
				new RouteStop { RouteID = 09, StopID = 106, Direction = Direction.Inbound, Order = 7},
				new RouteStop { RouteID = 09, StopID = 105, Direction = Direction.Inbound, Order = 8},
				new RouteStop { RouteID = 09, StopID = 104, Direction = Direction.Inbound, Order = 9},
				new RouteStop { RouteID = 09, StopID = 103, Direction = Direction.Inbound, Order = 10},
				new RouteStop { RouteID = 09, StopID = 102, Direction = Direction.Inbound, Order = 11},
				new RouteStop { RouteID = 09, StopID = 101, Direction = Direction.Inbound, Order = 12},
				new RouteStop { RouteID = 09, StopID = 100, Direction = Direction.Inbound, Order = 13},
				new RouteStop { RouteID = 09, StopID = 099, Direction = Direction.Inbound, Order = 14},
				new RouteStop { RouteID = 09, StopID = 098, Direction = Direction.Inbound, Order = 15},
				new RouteStop { RouteID = 09, StopID = 097, Direction = Direction.Inbound, Order = 16},
				new RouteStop { RouteID = 09, StopID = 070, Direction = Direction.Inbound, Order = 17},
				new RouteStop { RouteID = 10, StopID = 113, Direction = Direction.Outbound, Order = 1},
				new RouteStop { RouteID = 10, StopID = 114, Direction = Direction.Outbound, Order = 2},
				new RouteStop { RouteID = 10, StopID = 115, Direction = Direction.Outbound, Order = 3},
				new RouteStop { RouteID = 10, StopID = 116, Direction = Direction.Outbound, Order = 4},
				new RouteStop { RouteID = 10, StopID = 117, Direction = Direction.Outbound, Order = 5},
				new RouteStop { RouteID = 10, StopID = 118, Direction = Direction.Outbound, Order = 6},
				new RouteStop { RouteID = 10, StopID = 119, Direction = Direction.Outbound, Order = 7},
				new RouteStop { RouteID = 10, StopID = 120, Direction = Direction.Outbound, Order = 8},
				new RouteStop { RouteID = 10, StopID = 121, Direction = Direction.Outbound, Order = 9},
				new RouteStop { RouteID = 10, StopID = 122, Direction = Direction.Outbound, Order = 10},
				new RouteStop { RouteID = 10, StopID = 123, Direction = Direction.Outbound, Order = 11},
				new RouteStop { RouteID = 10, StopID = 124, Direction = Direction.Outbound, Order = 12},
				new RouteStop { RouteID = 10, StopID = 125, Direction = Direction.Outbound, Order = 13},
				new RouteStop { RouteID = 10, StopID = 126, Direction = Direction.Outbound, Order = 14},
				new RouteStop { RouteID = 10, StopID = 127, Direction = Direction.Outbound, Order = 15},
				new RouteStop { RouteID = 10, StopID = 128, Direction = Direction.Outbound, Order = 16},
				new RouteStop { RouteID = 10, StopID = 129, Direction = Direction.Outbound, Order = 17},
				new RouteStop { RouteID = 10, StopID = 130, Direction = Direction.Outbound, Order = 18},
				new RouteStop { RouteID = 10, StopID = 131, Direction = Direction.Outbound, Order = 19},
				new RouteStop { RouteID = 10, StopID = 132, Direction = Direction.Outbound, Order = 20},
				new RouteStop { RouteID = 10, StopID = 133, Direction = Direction.Outbound, Order = 21},
				new RouteStop { RouteID = 10, StopID = 134, Direction = Direction.Outbound, Order = 22},
				new RouteStop { RouteID = 10, StopID = 134, Direction = Direction.Inbound, Order = 1},
				new RouteStop { RouteID = 10, StopID = 133, Direction = Direction.Inbound, Order = 2},
				new RouteStop { RouteID = 10, StopID = 132, Direction = Direction.Inbound, Order = 3},
				new RouteStop { RouteID = 10, StopID = 131, Direction = Direction.Inbound, Order = 4},
				new RouteStop { RouteID = 10, StopID = 130, Direction = Direction.Inbound, Order = 5},
				new RouteStop { RouteID = 10, StopID = 129, Direction = Direction.Inbound, Order = 6},
				new RouteStop { RouteID = 10, StopID = 128, Direction = Direction.Inbound, Order = 7},
				new RouteStop { RouteID = 10, StopID = 127, Direction = Direction.Inbound, Order = 8},
				new RouteStop { RouteID = 10, StopID = 126, Direction = Direction.Inbound, Order = 9},
				new RouteStop { RouteID = 10, StopID = 125, Direction = Direction.Inbound, Order = 10},
				new RouteStop { RouteID = 10, StopID = 124, Direction = Direction.Inbound, Order = 11},
				new RouteStop { RouteID = 10, StopID = 123, Direction = Direction.Inbound, Order = 12},
				new RouteStop { RouteID = 10, StopID = 122, Direction = Direction.Inbound, Order = 13},
				new RouteStop { RouteID = 10, StopID = 121, Direction = Direction.Inbound, Order = 14},
				new RouteStop { RouteID = 10, StopID = 120, Direction = Direction.Inbound, Order = 15},
				new RouteStop { RouteID = 10, StopID = 119, Direction = Direction.Inbound, Order = 16},
				new RouteStop { RouteID = 10, StopID = 118, Direction = Direction.Inbound, Order = 17},
				new RouteStop { RouteID = 10, StopID = 117, Direction = Direction.Inbound, Order = 18},
				new RouteStop { RouteID = 10, StopID = 116, Direction = Direction.Inbound, Order = 19},
				new RouteStop { RouteID = 10, StopID = 115, Direction = Direction.Inbound, Order = 20},
				new RouteStop { RouteID = 10, StopID = 114, Direction = Direction.Inbound, Order = 21},
				new RouteStop { RouteID = 10, StopID = 113, Direction = Direction.Inbound, Order = 22},
				new RouteStop { RouteID = 11, StopID = 135, Direction = Direction.Outbound, Order = 1},
				new RouteStop { RouteID = 11, StopID = 136, Direction = Direction.Outbound, Order = 2},
				new RouteStop { RouteID = 11, StopID = 137, Direction = Direction.Outbound, Order = 3},
				new RouteStop { RouteID = 11, StopID = 138, Direction = Direction.Outbound, Order = 4},
				new RouteStop { RouteID = 11, StopID = 139, Direction = Direction.Outbound, Order = 5},
				new RouteStop { RouteID = 11, StopID = 140, Direction = Direction.Outbound, Order = 6},
				new RouteStop { RouteID = 11, StopID = 140, Direction = Direction.Inbound, Order = 1},
				new RouteStop { RouteID = 11, StopID = 139, Direction = Direction.Inbound, Order = 2},
				new RouteStop { RouteID = 11, StopID = 138, Direction = Direction.Inbound, Order = 3},
				new RouteStop { RouteID = 11, StopID = 137, Direction = Direction.Inbound, Order = 4},
				new RouteStop { RouteID = 11, StopID = 136, Direction = Direction.Inbound, Order = 5},
				new RouteStop { RouteID = 11, StopID = 135, Direction = Direction.Inbound, Order = 6},
				new RouteStop { RouteID = 12, StopID = 054, Direction = Direction.Outbound, Order = 1},
				new RouteStop { RouteID = 12, StopID = 141, Direction = Direction.Outbound, Order = 2},
				new RouteStop { RouteID = 12, StopID = 142, Direction = Direction.Outbound, Order = 3},
				new RouteStop { RouteID = 12, StopID = 143, Direction = Direction.Outbound, Order = 4},
				new RouteStop { RouteID = 12, StopID = 144, Direction = Direction.Outbound, Order = 5},
				new RouteStop { RouteID = 12, StopID = 145, Direction = Direction.Outbound, Order = 6},
				new RouteStop { RouteID = 12, StopID = 146, Direction = Direction.Outbound, Order = 7},
				new RouteStop { RouteID = 12, StopID = 147, Direction = Direction.Outbound, Order = 8},
				new RouteStop { RouteID = 12, StopID = 152, Direction = Direction.Outbound, Order = 9},
				new RouteStop { RouteID = 12, StopID = 153, Direction = Direction.Outbound, Order = 10},
				new RouteStop { RouteID = 12, StopID = 154, Direction = Direction.Outbound, Order = 11},
				new RouteStop { RouteID = 12, StopID = 155, Direction = Direction.Outbound, Order = 12},
				new RouteStop { RouteID = 12, StopID = 156, Direction = Direction.Outbound, Order = 13},
				new RouteStop { RouteID = 12, StopID = 157, Direction = Direction.Outbound, Order = 14},
				new RouteStop { RouteID = 12, StopID = 158, Direction = Direction.Outbound, Order = 15},
				new RouteStop { RouteID = 12, StopID = 159, Direction = Direction.Outbound, Order = 16},
				new RouteStop { RouteID = 12, StopID = 160, Direction = Direction.Outbound, Order = 17},
				new RouteStop { RouteID = 12, StopID = 161, Direction = Direction.Outbound, Order = 18},
				new RouteStop { RouteID = 12, StopID = 162, Direction = Direction.Outbound, Order = 19},
				new RouteStop { RouteID = 12, StopID = 163, Direction = Direction.Outbound, Order = 20},
				new RouteStop { RouteID = 12, StopID = 163, Direction = Direction.Inbound, Order = 1},
				new RouteStop { RouteID = 12, StopID = 162, Direction = Direction.Inbound, Order = 2},
				new RouteStop { RouteID = 12, StopID = 161, Direction = Direction.Inbound, Order = 3},
				new RouteStop { RouteID = 12, StopID = 160, Direction = Direction.Inbound, Order = 4},
				new RouteStop { RouteID = 12, StopID = 159, Direction = Direction.Inbound, Order = 5},
				new RouteStop { RouteID = 12, StopID = 158, Direction = Direction.Inbound, Order = 6},
				new RouteStop { RouteID = 12, StopID = 157, Direction = Direction.Inbound, Order = 7},
				new RouteStop { RouteID = 12, StopID = 156, Direction = Direction.Inbound, Order = 8},
				new RouteStop { RouteID = 12, StopID = 155, Direction = Direction.Inbound, Order = 9},
				new RouteStop { RouteID = 12, StopID = 154, Direction = Direction.Inbound, Order = 10},
				new RouteStop { RouteID = 12, StopID = 153, Direction = Direction.Inbound, Order = 11},
				new RouteStop { RouteID = 12, StopID = 152, Direction = Direction.Inbound, Order = 12},
				new RouteStop { RouteID = 12, StopID = 147, Direction = Direction.Inbound, Order = 13},
				new RouteStop { RouteID = 12, StopID = 146, Direction = Direction.Inbound, Order = 14},
				new RouteStop { RouteID = 12, StopID = 145, Direction = Direction.Inbound, Order = 15},
				new RouteStop { RouteID = 12, StopID = 144, Direction = Direction.Inbound, Order = 16},
				new RouteStop { RouteID = 12, StopID = 143, Direction = Direction.Inbound, Order = 17},
				new RouteStop { RouteID = 12, StopID = 142, Direction = Direction.Inbound, Order = 18},
				new RouteStop { RouteID = 12, StopID = 141, Direction = Direction.Inbound, Order = 19},
				new RouteStop { RouteID = 12, StopID = 054, Direction = Direction.Inbound, Order = 20},
				new RouteStop { RouteID = 13, StopID = 054, Direction = Direction.Outbound, Order = 1},
				new RouteStop { RouteID = 13, StopID = 141, Direction = Direction.Outbound, Order = 2},
				new RouteStop { RouteID = 13, StopID = 142, Direction = Direction.Outbound, Order = 3},
				new RouteStop { RouteID = 13, StopID = 143, Direction = Direction.Outbound, Order = 4},
				new RouteStop { RouteID = 13, StopID = 144, Direction = Direction.Outbound, Order = 5},
				new RouteStop { RouteID = 13, StopID = 145, Direction = Direction.Outbound, Order = 6},
				new RouteStop { RouteID = 13, StopID = 146, Direction = Direction.Outbound, Order = 7},
				new RouteStop { RouteID = 13, StopID = 147, Direction = Direction.Outbound, Order = 8},
				new RouteStop { RouteID = 13, StopID = 148, Direction = Direction.Outbound, Order = 9},
				new RouteStop { RouteID = 13, StopID = 149, Direction = Direction.Outbound, Order = 10},
				new RouteStop { RouteID = 13, StopID = 150, Direction = Direction.Outbound, Order = 11},
				new RouteStop { RouteID = 13, StopID = 151, Direction = Direction.Outbound, Order = 12},
				new RouteStop { RouteID = 13, StopID = 151, Direction = Direction.Inbound, Order = 1},
				new RouteStop { RouteID = 13, StopID = 150, Direction = Direction.Inbound, Order = 2},
				new RouteStop { RouteID = 13, StopID = 149, Direction = Direction.Inbound, Order = 3},
				new RouteStop { RouteID = 13, StopID = 148, Direction = Direction.Inbound, Order = 4},
				new RouteStop { RouteID = 13, StopID = 147, Direction = Direction.Inbound, Order = 5},
				new RouteStop { RouteID = 13, StopID = 146, Direction = Direction.Inbound, Order = 6},
				new RouteStop { RouteID = 13, StopID = 145, Direction = Direction.Inbound, Order = 7},
				new RouteStop { RouteID = 13, StopID = 144, Direction = Direction.Inbound, Order = 8},
				new RouteStop { RouteID = 13, StopID = 143, Direction = Direction.Inbound, Order = 9},
				new RouteStop { RouteID = 13, StopID = 142, Direction = Direction.Inbound, Order = 10},
				new RouteStop { RouteID = 13, StopID = 141, Direction = Direction.Inbound, Order = 11},
				new RouteStop { RouteID = 13, StopID = 054, Direction = Direction.Inbound, Order = 12},
				new RouteStop { RouteID = 14, StopID = 096, Direction = Direction.Outbound, Order = 1},
				new RouteStop { RouteID = 14, StopID = 164, Direction = Direction.Outbound, Order = 2},
				new RouteStop { RouteID = 14, StopID = 009, Direction = Direction.Outbound, Order = 3},
				new RouteStop { RouteID = 14, StopID = 165, Direction = Direction.Outbound, Order = 4},
				new RouteStop { RouteID = 14, StopID = 166, Direction = Direction.Outbound, Order = 5},
				new RouteStop { RouteID = 14, StopID = 167, Direction = Direction.Outbound, Order = 6},
				new RouteStop { RouteID = 14, StopID = 168, Direction = Direction.Outbound, Order = 7},
				new RouteStop { RouteID = 14, StopID = 169, Direction = Direction.Outbound, Order = 8},
				new RouteStop { RouteID = 14, StopID = 113, Direction = Direction.Outbound, Order = 9},
				new RouteStop { RouteID = 14, StopID = 170, Direction = Direction.Outbound, Order = 10},
				new RouteStop { RouteID = 14, StopID = 171, Direction = Direction.Outbound, Order = 11},
				new RouteStop { RouteID = 14, StopID = 172, Direction = Direction.Outbound, Order = 12},
				new RouteStop { RouteID = 14, StopID = 087, Direction = Direction.Outbound, Order = 13},
				new RouteStop { RouteID = 14, StopID = 173, Direction = Direction.Outbound, Order = 14},
				new RouteStop { RouteID = 14, StopID = 174, Direction = Direction.Outbound, Order = 15},
				new RouteStop { RouteID = 14, StopID = 175, Direction = Direction.Outbound, Order = 16},
				new RouteStop { RouteID = 14, StopID = 176, Direction = Direction.Outbound, Order = 17},
				new RouteStop { RouteID = 14, StopID = 072, Direction = Direction.Outbound, Order = 18},
				new RouteStop { RouteID = 14, StopID = 177, Direction = Direction.Outbound, Order = 19},
				new RouteStop { RouteID = 14, StopID = 028, Direction = Direction.Outbound, Order = 20},
				new RouteStop { RouteID = 14, StopID = 178, Direction = Direction.Outbound, Order = 21},
				new RouteStop { RouteID = 14, StopID = 057, Direction = Direction.Outbound, Order = 22},
				new RouteStop { RouteID = 14, StopID = 179, Direction = Direction.Outbound, Order = 23},
				new RouteStop { RouteID = 14, StopID = 180, Direction = Direction.Outbound, Order = 24},
				new RouteStop { RouteID = 14, StopID = 181, Direction = Direction.Outbound, Order = 25},
				new RouteStop { RouteID = 14, StopID = 182, Direction = Direction.Outbound, Order = 26},
				new RouteStop { RouteID = 14, StopID = 078, Direction = Direction.Outbound, Order = 27},
				new RouteStop { RouteID = 14, StopID = 183, Direction = Direction.Outbound, Order = 28},
				new RouteStop { RouteID = 14, StopID = 100, Direction = Direction.Outbound, Order = 29},
				new RouteStop { RouteID = 14, StopID = 184, Direction = Direction.Outbound, Order = 30},
				new RouteStop { RouteID = 14, StopID = 185, Direction = Direction.Outbound, Order = 31},
				new RouteStop { RouteID = 14, StopID = 186, Direction = Direction.Outbound, Order = 32},
				new RouteStop { RouteID = 14, StopID = 186, Direction = Direction.Inbound, Order = 1},
				new RouteStop { RouteID = 14, StopID = 185, Direction = Direction.Inbound, Order = 2},
				new RouteStop { RouteID = 14, StopID = 184, Direction = Direction.Inbound, Order = 3},
				new RouteStop { RouteID = 14, StopID = 100, Direction = Direction.Inbound, Order = 4},
				new RouteStop { RouteID = 14, StopID = 183, Direction = Direction.Inbound, Order = 5},
				new RouteStop { RouteID = 14, StopID = 078, Direction = Direction.Inbound, Order = 6},
				new RouteStop { RouteID = 14, StopID = 182, Direction = Direction.Inbound, Order = 7},
				new RouteStop { RouteID = 14, StopID = 181, Direction = Direction.Inbound, Order = 8},
				new RouteStop { RouteID = 14, StopID = 180, Direction = Direction.Inbound, Order = 9},
				new RouteStop { RouteID = 14, StopID = 179, Direction = Direction.Inbound, Order = 10},
				new RouteStop { RouteID = 14, StopID = 057, Direction = Direction.Inbound, Order = 11},
				new RouteStop { RouteID = 14, StopID = 178, Direction = Direction.Inbound, Order = 12},
				new RouteStop { RouteID = 14, StopID = 028, Direction = Direction.Inbound, Order = 13},
				new RouteStop { RouteID = 14, StopID = 177, Direction = Direction.Inbound, Order = 14},
				new RouteStop { RouteID = 14, StopID = 072, Direction = Direction.Inbound, Order = 15},
				new RouteStop { RouteID = 14, StopID = 176, Direction = Direction.Inbound, Order = 16},
				new RouteStop { RouteID = 14, StopID = 175, Direction = Direction.Inbound, Order = 17},
				new RouteStop { RouteID = 14, StopID = 174, Direction = Direction.Inbound, Order = 18},
				new RouteStop { RouteID = 14, StopID = 173, Direction = Direction.Inbound, Order = 19},
				new RouteStop { RouteID = 14, StopID = 087, Direction = Direction.Inbound, Order = 20},
				new RouteStop { RouteID = 14, StopID = 172, Direction = Direction.Inbound, Order = 21},
				new RouteStop { RouteID = 14, StopID = 171, Direction = Direction.Inbound, Order = 22},
				new RouteStop { RouteID = 14, StopID = 170, Direction = Direction.Inbound, Order = 23},
				new RouteStop { RouteID = 14, StopID = 113, Direction = Direction.Inbound, Order = 24},
				new RouteStop { RouteID = 14, StopID = 169, Direction = Direction.Inbound, Order = 25},
				new RouteStop { RouteID = 14, StopID = 168, Direction = Direction.Inbound, Order = 26},
				new RouteStop { RouteID = 14, StopID = 167, Direction = Direction.Inbound, Order = 27},
				new RouteStop { RouteID = 14, StopID = 166, Direction = Direction.Inbound, Order = 28},
				new RouteStop { RouteID = 14, StopID = 165, Direction = Direction.Inbound, Order = 29},
				new RouteStop { RouteID = 14, StopID = 009, Direction = Direction.Inbound, Order = 30},
				new RouteStop { RouteID = 14, StopID = 164, Direction = Direction.Inbound, Order = 31},
				new RouteStop { RouteID = 14, StopID = 096, Direction = Direction.Inbound, Order = 32},
				new RouteStop { RouteID = 15, StopID = 087, Direction = Direction.Outbound, Order = 1},
				new RouteStop { RouteID = 15, StopID = 173, Direction = Direction.Outbound, Order = 2},
				new RouteStop { RouteID = 15, StopID = 174, Direction = Direction.Outbound, Order = 3},
				new RouteStop { RouteID = 15, StopID = 175, Direction = Direction.Outbound, Order = 4},
				new RouteStop { RouteID = 15, StopID = 176, Direction = Direction.Outbound, Order = 5},
				new RouteStop { RouteID = 15, StopID = 072, Direction = Direction.Outbound, Order = 6},
				new RouteStop { RouteID = 15, StopID = 177, Direction = Direction.Outbound, Order = 7},
				new RouteStop { RouteID = 15, StopID = 028, Direction = Direction.Outbound, Order = 8},
				new RouteStop { RouteID = 15, StopID = 178, Direction = Direction.Outbound, Order = 9},
				new RouteStop { RouteID = 15, StopID = 057, Direction = Direction.Outbound, Order = 10},
				new RouteStop { RouteID = 15, StopID = 179, Direction = Direction.Outbound, Order = 11},
				new RouteStop { RouteID = 15, StopID = 180, Direction = Direction.Outbound, Order = 12},
				new RouteStop { RouteID = 15, StopID = 181, Direction = Direction.Outbound, Order = 13},
				new RouteStop { RouteID = 15, StopID = 182, Direction = Direction.Outbound, Order = 14},
				new RouteStop { RouteID = 15, StopID = 078, Direction = Direction.Outbound, Order = 15},
				new RouteStop { RouteID = 15, StopID = 183, Direction = Direction.Outbound, Order = 16},
				new RouteStop { RouteID = 15, StopID = 100, Direction = Direction.Outbound, Order = 17},
				new RouteStop { RouteID = 15, StopID = 184, Direction = Direction.Outbound, Order = 18},
				new RouteStop { RouteID = 15, StopID = 185, Direction = Direction.Outbound, Order = 19},
				new RouteStop { RouteID = 15, StopID = 186, Direction = Direction.Outbound, Order = 20},
				new RouteStop { RouteID = 15, StopID = 186, Direction = Direction.Inbound, Order = 1},
				new RouteStop { RouteID = 15, StopID = 185, Direction = Direction.Inbound, Order = 2},
				new RouteStop { RouteID = 15, StopID = 184, Direction = Direction.Inbound, Order = 3},
				new RouteStop { RouteID = 15, StopID = 100, Direction = Direction.Inbound, Order = 4},
				new RouteStop { RouteID = 15, StopID = 183, Direction = Direction.Inbound, Order = 5},
				new RouteStop { RouteID = 15, StopID = 078, Direction = Direction.Inbound, Order = 6},
				new RouteStop { RouteID = 15, StopID = 182, Direction = Direction.Inbound, Order = 7},
				new RouteStop { RouteID = 15, StopID = 181, Direction = Direction.Inbound, Order = 8},
				new RouteStop { RouteID = 15, StopID = 180, Direction = Direction.Inbound, Order = 9},
				new RouteStop { RouteID = 15, StopID = 179, Direction = Direction.Inbound, Order = 10},
				new RouteStop { RouteID = 15, StopID = 057, Direction = Direction.Inbound, Order = 11},
				new RouteStop { RouteID = 15, StopID = 178, Direction = Direction.Inbound, Order = 12},
				new RouteStop { RouteID = 15, StopID = 028, Direction = Direction.Inbound, Order = 13},
				new RouteStop { RouteID = 15, StopID = 177, Direction = Direction.Inbound, Order = 14},
				new RouteStop { RouteID = 15, StopID = 072, Direction = Direction.Inbound, Order = 15},
				new RouteStop { RouteID = 15, StopID = 176, Direction = Direction.Inbound, Order = 16},
				new RouteStop { RouteID = 15, StopID = 175, Direction = Direction.Inbound, Order = 17},
				new RouteStop { RouteID = 15, StopID = 174, Direction = Direction.Inbound, Order = 18},
				new RouteStop { RouteID = 15, StopID = 173, Direction = Direction.Inbound, Order = 19},
				new RouteStop { RouteID = 15, StopID = 087, Direction = Direction.Inbound, Order = 20},
				new RouteStop { RouteID = 16, StopID = 187, Direction = Direction.Outbound, Order = 1},
				new RouteStop { RouteID = 16, StopID = 188, Direction = Direction.Outbound, Order = 2},
				new RouteStop { RouteID = 16, StopID = 071, Direction = Direction.Outbound, Order = 3},
				new RouteStop { RouteID = 16, StopID = 189, Direction = Direction.Outbound, Order = 4},
				new RouteStop { RouteID = 16, StopID = 190, Direction = Direction.Outbound, Order = 5},
				new RouteStop { RouteID = 16, StopID = 191, Direction = Direction.Outbound, Order = 6},
				new RouteStop { RouteID = 16, StopID = 018, Direction = Direction.Outbound, Order = 7},
				new RouteStop { RouteID = 16, StopID = 094, Direction = Direction.Outbound, Order = 8},
				new RouteStop { RouteID = 16, StopID = 192, Direction = Direction.Outbound, Order = 9},
				new RouteStop { RouteID = 16, StopID = 135, Direction = Direction.Outbound, Order = 10},
				new RouteStop { RouteID = 16, StopID = 193, Direction = Direction.Outbound, Order = 11},
				new RouteStop { RouteID = 16, StopID = 136, Direction = Direction.Outbound, Order = 12},
				new RouteStop { RouteID = 16, StopID = 113, Direction = Direction.Outbound, Order = 13},
				new RouteStop { RouteID = 16, StopID = 113, Direction = Direction.Inbound, Order = 1},
				new RouteStop { RouteID = 16, StopID = 136, Direction = Direction.Inbound, Order = 2},
				new RouteStop { RouteID = 16, StopID = 193, Direction = Direction.Inbound, Order = 3},
				new RouteStop { RouteID = 16, StopID = 135, Direction = Direction.Inbound, Order = 4},
				new RouteStop { RouteID = 16, StopID = 192, Direction = Direction.Inbound, Order = 5},
				new RouteStop { RouteID = 16, StopID = 094, Direction = Direction.Inbound, Order = 6},
				new RouteStop { RouteID = 16, StopID = 018, Direction = Direction.Inbound, Order = 7},
				new RouteStop { RouteID = 16, StopID = 191, Direction = Direction.Inbound, Order = 8},
				new RouteStop { RouteID = 16, StopID = 190, Direction = Direction.Inbound, Order = 9},
				new RouteStop { RouteID = 16, StopID = 189, Direction = Direction.Inbound, Order = 10},
				new RouteStop { RouteID = 16, StopID = 071, Direction = Direction.Inbound, Order = 11},
				new RouteStop { RouteID = 16, StopID = 188, Direction = Direction.Inbound, Order = 12},
				new RouteStop { RouteID = 16, StopID = 187, Direction = Direction.Inbound, Order = 13},
				new RouteStop { RouteID = 17, StopID = 040, Direction = Direction.Outbound, Order = 1},
				new RouteStop { RouteID = 17, StopID = 057, Direction = Direction.Outbound, Order = 2},
				new RouteStop { RouteID = 17, StopID = 056, Direction = Direction.Outbound, Order = 3},
				new RouteStop { RouteID = 17, StopID = 194, Direction = Direction.Outbound, Order = 4},
				new RouteStop { RouteID = 17, StopID = 194, Direction = Direction.Outbound, Order = 5},
				new RouteStop { RouteID = 17, StopID = 195, Direction = Direction.Outbound, Order = 6},
				new RouteStop { RouteID = 17, StopID = 030, Direction = Direction.Outbound, Order = 7},
				new RouteStop { RouteID = 17, StopID = 044, Direction = Direction.Outbound, Order = 8},
				new RouteStop { RouteID = 17, StopID = 196, Direction = Direction.Outbound, Order = 9},
				new RouteStop { RouteID = 17, StopID = 197, Direction = Direction.Outbound, Order = 10},
				new RouteStop { RouteID = 17, StopID = 198, Direction = Direction.Outbound, Order = 11},
				new RouteStop { RouteID = 17, StopID = 199, Direction = Direction.Outbound, Order = 12},
				new RouteStop { RouteID = 17, StopID = 054, Direction = Direction.Outbound, Order = 13},
				new RouteStop { RouteID = 17, StopID = 054, Direction = Direction.Outbound, Order = 14},
				new RouteStop { RouteID = 17, StopID = 200, Direction = Direction.Outbound, Order = 15},
				new RouteStop { RouteID = 17, StopID = 201, Direction = Direction.Outbound, Order = 16},
				new RouteStop { RouteID = 17, StopID = 202, Direction = Direction.Outbound, Order = 17},
				new RouteStop { RouteID = 17, StopID = 203, Direction = Direction.Outbound, Order = 18},
				new RouteStop { RouteID = 17, StopID = 204, Direction = Direction.Outbound, Order = 19},
				new RouteStop { RouteID = 17, StopID = 205, Direction = Direction.Outbound, Order = 20},
				new RouteStop { RouteID = 17, StopID = 206, Direction = Direction.Outbound, Order = 21},
				new RouteStop { RouteID = 17, StopID = 207, Direction = Direction.Outbound, Order = 22},
				new RouteStop { RouteID = 17, StopID = 208, Direction = Direction.Outbound, Order = 23},
				new RouteStop { RouteID = 17, StopID = 088, Direction = Direction.Outbound, Order = 24},
				new RouteStop { RouteID = 17, StopID = 209, Direction = Direction.Outbound, Order = 25},
				new RouteStop { RouteID = 17, StopID = 210, Direction = Direction.Outbound, Order = 26},
				new RouteStop { RouteID = 17, StopID = 211, Direction = Direction.Outbound, Order = 27},
				new RouteStop { RouteID = 17, StopID = 212, Direction = Direction.Outbound, Order = 28},
				new RouteStop { RouteID = 17, StopID = 213, Direction = Direction.Outbound, Order = 29},
				new RouteStop { RouteID = 17, StopID = 214, Direction = Direction.Outbound, Order = 30},
				new RouteStop { RouteID = 17, StopID = 215, Direction = Direction.Outbound, Order = 31},
				new RouteStop { RouteID = 17, StopID = 216, Direction = Direction.Outbound, Order = 32},
				new RouteStop { RouteID = 17, StopID = 216, Direction = Direction.Inbound, Order = 1},
				new RouteStop { RouteID = 17, StopID = 215, Direction = Direction.Inbound, Order = 2},
				new RouteStop { RouteID = 17, StopID = 214, Direction = Direction.Inbound, Order = 3},
				new RouteStop { RouteID = 17, StopID = 213, Direction = Direction.Inbound, Order = 4},
				new RouteStop { RouteID = 17, StopID = 212, Direction = Direction.Inbound, Order = 5},
				new RouteStop { RouteID = 17, StopID = 211, Direction = Direction.Inbound, Order = 6},
				new RouteStop { RouteID = 17, StopID = 210, Direction = Direction.Inbound, Order = 7},
				new RouteStop { RouteID = 17, StopID = 209, Direction = Direction.Inbound, Order = 8},
				new RouteStop { RouteID = 17, StopID = 088, Direction = Direction.Inbound, Order = 9},
				new RouteStop { RouteID = 17, StopID = 208, Direction = Direction.Inbound, Order = 10},
				new RouteStop { RouteID = 17, StopID = 207, Direction = Direction.Inbound, Order = 11},
				new RouteStop { RouteID = 17, StopID = 206, Direction = Direction.Inbound, Order = 12},
				new RouteStop { RouteID = 17, StopID = 217, Direction = Direction.Inbound, Order = 13},
				new RouteStop { RouteID = 17, StopID = 205, Direction = Direction.Inbound, Order = 14},
				new RouteStop { RouteID = 17, StopID = 204, Direction = Direction.Inbound, Order = 15},
				new RouteStop { RouteID = 17, StopID = 203, Direction = Direction.Inbound, Order = 16},
				new RouteStop { RouteID = 17, StopID = 202, Direction = Direction.Inbound, Order = 17},
				new RouteStop { RouteID = 17, StopID = 201, Direction = Direction.Inbound, Order = 18},
				new RouteStop { RouteID = 17, StopID = 200, Direction = Direction.Inbound, Order = 19},
				new RouteStop { RouteID = 17, StopID = 054, Direction = Direction.Inbound, Order = 20},
				new RouteStop { RouteID = 17, StopID = 054, Direction = Direction.Inbound, Order = 21},
				new RouteStop { RouteID = 17, StopID = 199, Direction = Direction.Inbound, Order = 22},
				new RouteStop { RouteID = 17, StopID = 198, Direction = Direction.Inbound, Order = 23},
				new RouteStop { RouteID = 17, StopID = 197, Direction = Direction.Inbound, Order = 24},
				new RouteStop { RouteID = 17, StopID = 196, Direction = Direction.Inbound, Order = 25},
				new RouteStop { RouteID = 17, StopID = 044, Direction = Direction.Inbound, Order = 26},
				new RouteStop { RouteID = 17, StopID = 030, Direction = Direction.Inbound, Order = 27},
				new RouteStop { RouteID = 17, StopID = 195, Direction = Direction.Inbound, Order = 28},
				new RouteStop { RouteID = 17, StopID = 194, Direction = Direction.Inbound, Order = 29},
				new RouteStop { RouteID = 17, StopID = 056, Direction = Direction.Inbound, Order = 30},
				new RouteStop { RouteID = 17, StopID = 057, Direction = Direction.Inbound, Order = 31},
				new RouteStop { RouteID = 17, StopID = 040, Direction = Direction.Inbound, Order = 32},
				new RouteStop { RouteID = 18, StopID = 069, Direction = Direction.Outbound, Order = 1},
				new RouteStop { RouteID = 19, StopID = 069, Direction = Direction.Outbound, Order = 1},
				new RouteStop { RouteID = 18, StopID = 218, Direction = Direction.Outbound, Order = 2},
				new RouteStop { RouteID = 19, StopID = 218, Direction = Direction.Outbound, Order = 2},
				new RouteStop { RouteID = 18, StopID = 219, Direction = Direction.Outbound, Order = 3},
				new RouteStop { RouteID = 19, StopID = 219, Direction = Direction.Outbound, Order = 3},
				new RouteStop { RouteID = 18, StopID = 097, Direction = Direction.Outbound, Order = 4},
				new RouteStop { RouteID = 19, StopID = 097, Direction = Direction.Outbound, Order = 4},
				new RouteStop { RouteID = 18, StopID = 220, Direction = Direction.Outbound, Order = 5},
				new RouteStop { RouteID = 19, StopID = 220, Direction = Direction.Outbound, Order = 5},
				new RouteStop { RouteID = 18, StopID = 187, Direction = Direction.Outbound, Order = 6},
				new RouteStop { RouteID = 19, StopID = 187, Direction = Direction.Outbound, Order = 6},
				new RouteStop { RouteID = 18, StopID = 081, Direction = Direction.Outbound, Order = 7},
				new RouteStop { RouteID = 19, StopID = 081, Direction = Direction.Outbound, Order = 7},
				new RouteStop { RouteID = 18, StopID = 062, Direction = Direction.Outbound, Order = 8},
				new RouteStop { RouteID = 19, StopID = 062, Direction = Direction.Outbound, Order = 8},
				new RouteStop { RouteID = 18, StopID = 221, Direction = Direction.Outbound, Order = 9},
				new RouteStop { RouteID = 19, StopID = 221, Direction = Direction.Outbound, Order = 9},
				new RouteStop { RouteID = 18, StopID = 222, Direction = Direction.Outbound, Order = 10},
				new RouteStop { RouteID = 19, StopID = 222, Direction = Direction.Outbound, Order = 10},
				new RouteStop { RouteID = 18, StopID = 022, Direction = Direction.Outbound, Order = 11},
				new RouteStop { RouteID = 19, StopID = 022, Direction = Direction.Outbound, Order = 11},
				new RouteStop { RouteID = 18, StopID = 093, Direction = Direction.Outbound, Order = 12},
				new RouteStop { RouteID = 19, StopID = 093, Direction = Direction.Outbound, Order = 12},
				new RouteStop { RouteID = 18, StopID = 223, Direction = Direction.Outbound, Order = 13},
				new RouteStop { RouteID = 19, StopID = 223, Direction = Direction.Outbound, Order = 13},
				new RouteStop { RouteID = 18, StopID = 084, Direction = Direction.Outbound, Order = 14},
				new RouteStop { RouteID = 19, StopID = 084, Direction = Direction.Outbound, Order = 14},
				new RouteStop { RouteID = 18, StopID = 224, Direction = Direction.Outbound, Order = 15},
				new RouteStop { RouteID = 19, StopID = 224, Direction = Direction.Outbound, Order = 15},
				new RouteStop { RouteID = 18, StopID = 135, Direction = Direction.Outbound, Order = 16},
				new RouteStop { RouteID = 19, StopID = 135, Direction = Direction.Outbound, Order = 16},
				new RouteStop { RouteID = 18, StopID = 225, Direction = Direction.Outbound, Order = 17},
				new RouteStop { RouteID = 19, StopID = 225, Direction = Direction.Outbound, Order = 17},
				new RouteStop { RouteID = 18, StopID = 226, Direction = Direction.Outbound, Order = 18},
				new RouteStop { RouteID = 18, StopID = 095, Direction = Direction.Outbound, Order = 19},
				new RouteStop { RouteID = 19, StopID = 227, Direction = Direction.Outbound, Order = 18},
				new RouteStop { RouteID = 19, StopID = 014, Direction = Direction.Outbound, Order = 19},
				new RouteStop { RouteID = 18, StopID = 095, Direction = Direction.Inbound, Order = 1},
				new RouteStop { RouteID = 18, StopID = 226, Direction = Direction.Inbound, Order = 2},
				new RouteStop { RouteID = 19, StopID = 014, Direction = Direction.Inbound, Order = 1},
				new RouteStop { RouteID = 19, StopID = 227, Direction = Direction.Inbound, Order = 2},
				new RouteStop { RouteID = 18, StopID = 225, Direction = Direction.Inbound, Order = 3},
				new RouteStop { RouteID = 19, StopID = 225, Direction = Direction.Inbound, Order = 3},
				new RouteStop { RouteID = 18, StopID = 135, Direction = Direction.Inbound, Order = 4},
				new RouteStop { RouteID = 19, StopID = 135, Direction = Direction.Inbound, Order = 4},
				new RouteStop { RouteID = 18, StopID = 224, Direction = Direction.Inbound, Order = 5},
				new RouteStop { RouteID = 19, StopID = 224, Direction = Direction.Inbound, Order = 5},
				new RouteStop { RouteID = 18, StopID = 084, Direction = Direction.Inbound, Order = 6},
				new RouteStop { RouteID = 19, StopID = 084, Direction = Direction.Inbound, Order = 6},
				new RouteStop { RouteID = 18, StopID = 223, Direction = Direction.Inbound, Order = 7},
				new RouteStop { RouteID = 19, StopID = 223, Direction = Direction.Inbound, Order = 7},
				new RouteStop { RouteID = 18, StopID = 093, Direction = Direction.Inbound, Order = 8},
				new RouteStop { RouteID = 19, StopID = 093, Direction = Direction.Inbound, Order = 8},
				new RouteStop { RouteID = 18, StopID = 022, Direction = Direction.Inbound, Order = 9},
				new RouteStop { RouteID = 19, StopID = 022, Direction = Direction.Inbound, Order = 9},
				new RouteStop { RouteID = 18, StopID = 222, Direction = Direction.Inbound, Order = 10},
				new RouteStop { RouteID = 19, StopID = 222, Direction = Direction.Inbound, Order = 10},
				new RouteStop { RouteID = 18, StopID = 221, Direction = Direction.Inbound, Order = 11},
				new RouteStop { RouteID = 19, StopID = 221, Direction = Direction.Inbound, Order = 11},
				new RouteStop { RouteID = 18, StopID = 062, Direction = Direction.Inbound, Order = 12},
				new RouteStop { RouteID = 19, StopID = 062, Direction = Direction.Inbound, Order = 12},
				new RouteStop { RouteID = 18, StopID = 081, Direction = Direction.Inbound, Order = 13},
				new RouteStop { RouteID = 19, StopID = 081, Direction = Direction.Inbound, Order = 13},
				new RouteStop { RouteID = 18, StopID = 187, Direction = Direction.Inbound, Order = 14},
				new RouteStop { RouteID = 19, StopID = 187, Direction = Direction.Inbound, Order = 14},
				new RouteStop { RouteID = 18, StopID = 220, Direction = Direction.Inbound, Order = 15},
				new RouteStop { RouteID = 19, StopID = 220, Direction = Direction.Inbound, Order = 15},
				new RouteStop { RouteID = 18, StopID = 097, Direction = Direction.Inbound, Order = 16},
				new RouteStop { RouteID = 19, StopID = 097, Direction = Direction.Inbound, Order = 16},
				new RouteStop { RouteID = 18, StopID = 219, Direction = Direction.Inbound, Order = 17},
				new RouteStop { RouteID = 19, StopID = 219, Direction = Direction.Inbound, Order = 17},
				new RouteStop { RouteID = 18, StopID = 218, Direction = Direction.Inbound, Order = 18},
				new RouteStop { RouteID = 19, StopID = 218, Direction = Direction.Inbound, Order = 18},
				new RouteStop { RouteID = 18, StopID = 069, Direction = Direction.Inbound, Order = 19},
				new RouteStop { RouteID = 19, StopID = 069, Direction = Direction.Inbound, Order = 19},
				new RouteStop { RouteID = 20, StopID = 228, Direction = Direction.Outbound, Order = 1},
				new RouteStop { RouteID = 20, StopID = 229, Direction = Direction.Outbound, Order = 2},
				new RouteStop { RouteID = 20, StopID = 230, Direction = Direction.Outbound, Order = 3},
				new RouteStop { RouteID = 20, StopID = 231, Direction = Direction.Outbound, Order = 4},
				new RouteStop { RouteID = 20, StopID = 232, Direction = Direction.Outbound, Order = 5},
				new RouteStop { RouteID = 20, StopID = 233, Direction = Direction.Outbound, Order = 6},
				new RouteStop { RouteID = 20, StopID = 234, Direction = Direction.Outbound, Order = 7},
				new RouteStop { RouteID = 20, StopID = 235, Direction = Direction.Outbound, Order = 8},
				new RouteStop { RouteID = 20, StopID = 069, Direction = Direction.Outbound, Order = 9},
				new RouteStop { RouteID = 20, StopID = 236, Direction = Direction.Outbound, Order = 10},
				new RouteStop { RouteID = 20, StopID = 237, Direction = Direction.Outbound, Order = 11},
				new RouteStop { RouteID = 20, StopID = 238, Direction = Direction.Outbound, Order = 12},
				new RouteStop { RouteID = 20, StopID = 239, Direction = Direction.Outbound, Order = 13},
				new RouteStop { RouteID = 20, StopID = 240, Direction = Direction.Outbound, Order = 14},
				new RouteStop { RouteID = 20, StopID = 241, Direction = Direction.Outbound, Order = 15},
				new RouteStop { RouteID = 20, StopID = 018, Direction = Direction.Outbound, Order = 16},
				new RouteStop { RouteID = 20, StopID = 019, Direction = Direction.Outbound, Order = 17},
				new RouteStop { RouteID = 20, StopID = 020, Direction = Direction.Outbound, Order = 18},
				new RouteStop { RouteID = 20, StopID = 021, Direction = Direction.Outbound, Order = 19},
				new RouteStop { RouteID = 20, StopID = 022, Direction = Direction.Outbound, Order = 20},
				new RouteStop { RouteID = 20, StopID = 023, Direction = Direction.Outbound, Order = 21},
				new RouteStop { RouteID = 20, StopID = 024, Direction = Direction.Outbound, Order = 22},
				new RouteStop { RouteID = 20, StopID = 025, Direction = Direction.Outbound, Order = 23},
				new RouteStop { RouteID = 20, StopID = 026, Direction = Direction.Outbound, Order = 24},
				new RouteStop { RouteID = 20, StopID = 027, Direction = Direction.Outbound, Order = 25},
				new RouteStop { RouteID = 20, StopID = 028, Direction = Direction.Outbound, Order = 26},
				new RouteStop { RouteID = 20, StopID = 242, Direction = Direction.Outbound, Order = 27},
				new RouteStop { RouteID = 20, StopID = 057, Direction = Direction.Outbound, Order = 28},
				new RouteStop { RouteID = 20, StopID = 056, Direction = Direction.Outbound, Order = 29},
				new RouteStop { RouteID = 20, StopID = 194, Direction = Direction.Outbound, Order = 30},
				new RouteStop { RouteID = 20, StopID = 243, Direction = Direction.Outbound, Order = 31},
				new RouteStop { RouteID = 20, StopID = 244, Direction = Direction.Outbound, Order = 32},
				new RouteStop { RouteID = 20, StopID = 245, Direction = Direction.Outbound, Order = 33},
				new RouteStop { RouteID = 20, StopID = 246, Direction = Direction.Outbound, Order = 34},
				new RouteStop { RouteID = 20, StopID = 247, Direction = Direction.Outbound, Order = 35},
				new RouteStop { RouteID = 20, StopID = 248, Direction = Direction.Outbound, Order = 36},
				new RouteStop { RouteID = 20, StopID = 249, Direction = Direction.Outbound, Order = 37},
				new RouteStop { RouteID = 20, StopID = 250, Direction = Direction.Outbound, Order = 38},
				new RouteStop { RouteID = 20, StopID = 251, Direction = Direction.Outbound, Order = 39},
				new RouteStop { RouteID = 20, StopID = 252, Direction = Direction.Outbound, Order = 40},
				new RouteStop { RouteID = 20, StopID = 253, Direction = Direction.Outbound, Order = 41},
				new RouteStop { RouteID = 20, StopID = 254, Direction = Direction.Outbound, Order = 42},
				new RouteStop { RouteID = 20, StopID = 255, Direction = Direction.Outbound, Order = 43},
				new RouteStop { RouteID = 20, StopID = 256, Direction = Direction.Outbound, Order = 44},
				new RouteStop { RouteID = 20, StopID = 257, Direction = Direction.Outbound, Order = 45},
				new RouteStop { RouteID = 20, StopID = 258, Direction = Direction.Outbound, Order = 46},
				new RouteStop { RouteID = 20, StopID = 259, Direction = Direction.Outbound, Order = 47},
				new RouteStop { RouteID = 20, StopID = 259, Direction = Direction.Inbound, Order = 1},
				new RouteStop { RouteID = 20, StopID = 258, Direction = Direction.Inbound, Order = 2},
				new RouteStop { RouteID = 20, StopID = 257, Direction = Direction.Inbound, Order = 3},
				new RouteStop { RouteID = 20, StopID = 256, Direction = Direction.Inbound, Order = 4},
				new RouteStop { RouteID = 20, StopID = 255, Direction = Direction.Inbound, Order = 5},
				new RouteStop { RouteID = 20, StopID = 254, Direction = Direction.Inbound, Order = 6},
				new RouteStop { RouteID = 20, StopID = 252, Direction = Direction.Inbound, Order = 7},
				new RouteStop { RouteID = 20, StopID = 251, Direction = Direction.Inbound, Order = 8},
				new RouteStop { RouteID = 20, StopID = 250, Direction = Direction.Inbound, Order = 9},
				new RouteStop { RouteID = 20, StopID = 249, Direction = Direction.Inbound, Order = 10},
				new RouteStop { RouteID = 20, StopID = 248, Direction = Direction.Inbound, Order = 11},
				new RouteStop { RouteID = 20, StopID = 247, Direction = Direction.Inbound, Order = 12},
				new RouteStop { RouteID = 20, StopID = 246, Direction = Direction.Inbound, Order = 13},
				new RouteStop { RouteID = 20, StopID = 245, Direction = Direction.Inbound, Order = 14},
				new RouteStop { RouteID = 20, StopID = 244, Direction = Direction.Inbound, Order = 15},
				new RouteStop { RouteID = 20, StopID = 243, Direction = Direction.Inbound, Order = 16},
				new RouteStop { RouteID = 20, StopID = 194, Direction = Direction.Inbound, Order = 17},
				new RouteStop { RouteID = 20, StopID = 056, Direction = Direction.Inbound, Order = 18},
				new RouteStop { RouteID = 20, StopID = 057, Direction = Direction.Inbound, Order = 19},
				new RouteStop { RouteID = 20, StopID = 242, Direction = Direction.Inbound, Order = 20},
				new RouteStop { RouteID = 20, StopID = 028, Direction = Direction.Inbound, Order = 21},
				new RouteStop { RouteID = 20, StopID = 027, Direction = Direction.Inbound, Order = 22},
				new RouteStop { RouteID = 20, StopID = 026, Direction = Direction.Inbound, Order = 23},
				new RouteStop { RouteID = 20, StopID = 025, Direction = Direction.Inbound, Order = 24},
				new RouteStop { RouteID = 20, StopID = 024, Direction = Direction.Inbound, Order = 25},
				new RouteStop { RouteID = 20, StopID = 023, Direction = Direction.Inbound, Order = 26},
				new RouteStop { RouteID = 20, StopID = 022, Direction = Direction.Inbound, Order = 27},
				new RouteStop { RouteID = 20, StopID = 021, Direction = Direction.Inbound, Order = 28},
				new RouteStop { RouteID = 20, StopID = 020, Direction = Direction.Inbound, Order = 29},
				new RouteStop { RouteID = 20, StopID = 019, Direction = Direction.Inbound, Order = 30},
				new RouteStop { RouteID = 20, StopID = 018, Direction = Direction.Inbound, Order = 31},
				new RouteStop { RouteID = 20, StopID = 260, Direction = Direction.Inbound, Order = 32},
				new RouteStop { RouteID = 20, StopID = 240, Direction = Direction.Inbound, Order = 33},
				new RouteStop { RouteID = 20, StopID = 239, Direction = Direction.Inbound, Order = 34},
				new RouteStop { RouteID = 20, StopID = 237, Direction = Direction.Inbound, Order = 35},
				new RouteStop { RouteID = 20, StopID = 236, Direction = Direction.Inbound, Order = 36},
				new RouteStop { RouteID = 20, StopID = 069, Direction = Direction.Inbound, Order = 37},
				new RouteStop { RouteID = 20, StopID = 235, Direction = Direction.Inbound, Order = 38},
				new RouteStop { RouteID = 20, StopID = 234, Direction = Direction.Inbound, Order = 39},
				new RouteStop { RouteID = 20, StopID = 233, Direction = Direction.Inbound, Order = 40},
				new RouteStop { RouteID = 20, StopID = 232, Direction = Direction.Inbound, Order = 41},
				new RouteStop { RouteID = 20, StopID = 231, Direction = Direction.Inbound, Order = 42},
				new RouteStop { RouteID = 20, StopID = 230, Direction = Direction.Inbound, Order = 43},
				new RouteStop { RouteID = 20, StopID = 229, Direction = Direction.Inbound, Order = 44},
				new RouteStop { RouteID = 20, StopID = 228, Direction = Direction.Inbound, Order = 45},

				);
			#endregion
		}
	}
}